// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: tmp.proto

package message

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Custom_Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row    *uint32 `protobuf:"varint,1,opt,name=row,proto3,oneof" json:"row,omitempty"`
	Column *uint32 `protobuf:"varint,2,opt,name=column,proto3,oneof" json:"column,omitempty"`
}

func (x *Custom_Block) Reset() {
	*x = Custom_Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Custom_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_Block) ProtoMessage() {}

func (x *Custom_Block) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_Block.ProtoReflect.Descriptor instead.
func (*Custom_Block) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{0}
}

func (x *Custom_Block) GetRow() uint32 {
	if x != nil && x.Row != nil {
		return *x.Row
	}
	return 0
}

func (x *Custom_Block) GetColumn() uint32 {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return 0
}

type Custom_Plate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column []*Custom_ColumnData `protobuf:"bytes,1,rep,name=column,proto3" json:"column,omitempty"`
	Win    *float64             `protobuf:"fixed64,2,opt,name=win,proto3,oneof" json:"win,omitempty"`
	Award  []*Custom_Award      `protobuf:"bytes,3,rep,name=award,proto3" json:"award,omitempty"`
}

func (x *Custom_Plate) Reset() {
	*x = Custom_Plate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Custom_Plate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_Plate) ProtoMessage() {}

func (x *Custom_Plate) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_Plate.ProtoReflect.Descriptor instead.
func (*Custom_Plate) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{1}
}

func (x *Custom_Plate) GetColumn() []*Custom_ColumnData {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *Custom_Plate) GetWin() float64 {
	if x != nil && x.Win != nil {
		return *x.Win
	}
	return 0
}

func (x *Custom_Plate) GetAward() []*Custom_Award {
	if x != nil {
		return x.Award
	}
	return nil
}

type Custom_Award struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    *int32   `protobuf:"varint,1,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	Win       *float64 `protobuf:"fixed64,2,opt,name=win,proto3,oneof" json:"win,omitempty"`
	MaxColumn *int64   `protobuf:"varint,3,opt,name=maxColumn,proto3,oneof" json:"maxColumn,omitempty"`
	Connect   *int64   `protobuf:"varint,4,opt,name=connect,proto3,oneof" json:"connect,omitempty"`
}

func (x *Custom_Award) Reset() {
	*x = Custom_Award{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Custom_Award) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_Award) ProtoMessage() {}

func (x *Custom_Award) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_Award.ProtoReflect.Descriptor instead.
func (*Custom_Award) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{2}
}

func (x *Custom_Award) GetSymbol() int32 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *Custom_Award) GetWin() float64 {
	if x != nil && x.Win != nil {
		return *x.Win
	}
	return 0
}

func (x *Custom_Award) GetMaxColumn() int64 {
	if x != nil && x.MaxColumn != nil {
		return *x.MaxColumn
	}
	return 0
}

func (x *Custom_Award) GetConnect() int64 {
	if x != nil && x.Connect != nil {
		return *x.Connect
	}
	return 0
}

type Custom_AllPlate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plate     []*Custom_Plate `protobuf:"bytes,1,rep,name=plate,proto3" json:"plate,omitempty"`
	FreeCount *int64          `protobuf:"varint,2,opt,name=freeCount,proto3,oneof" json:"freeCount,omitempty"`
	FreeRate  *int64          `protobuf:"varint,3,opt,name=freeRate,proto3,oneof" json:"freeRate,omitempty"`
}

func (x *Custom_AllPlate) Reset() {
	*x = Custom_AllPlate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Custom_AllPlate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_AllPlate) ProtoMessage() {}

func (x *Custom_AllPlate) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_AllPlate.ProtoReflect.Descriptor instead.
func (*Custom_AllPlate) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{3}
}

func (x *Custom_AllPlate) GetPlate() []*Custom_Plate {
	if x != nil {
		return x.Plate
	}
	return nil
}

func (x *Custom_AllPlate) GetFreeCount() int64 {
	if x != nil && x.FreeCount != nil {
		return *x.FreeCount
	}
	return 0
}

func (x *Custom_AllPlate) GetFreeRate() int64 {
	if x != nil && x.FreeRate != nil {
		return *x.FreeRate
	}
	return 0
}

type Custom_ColumnData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row []*Custom_Cell `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
}

func (x *Custom_ColumnData) Reset() {
	*x = Custom_ColumnData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Custom_ColumnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_ColumnData) ProtoMessage() {}

func (x *Custom_ColumnData) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_ColumnData.ProtoReflect.Descriptor instead.
func (*Custom_ColumnData) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{4}
}

func (x *Custom_ColumnData) GetRow() []*Custom_Cell {
	if x != nil {
		return x.Row
	}
	return nil
}

type Custom_Cell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol    *int32 `protobuf:"varint,1,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
	IsConnect *bool  `protobuf:"varint,2,opt,name=isConnect,proto3,oneof" json:"isConnect,omitempty"`
}

func (x *Custom_Cell) Reset() {
	*x = Custom_Cell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Custom_Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Custom_Cell) ProtoMessage() {}

func (x *Custom_Cell) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Custom_Cell.ProtoReflect.Descriptor instead.
func (*Custom_Cell) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{5}
}

func (x *Custom_Cell) GetSymbol() int32 {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return 0
}

func (x *Custom_Cell) GetIsConnect() bool {
	if x != nil && x.IsConnect != nil {
		return *x.IsConnect
	}
	return false
}

var File_tmp_proto protoreflect.FileDescriptor

var file_tmp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x15, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x00, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x06, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x72, 0x6f, 0x77,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x8e, 0x01, 0x0a, 0x0c,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x12, 0x15, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52,
	0x03, 0x77, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2b, 0x0a, 0x05, 0x61, 0x77, 0x61, 0x72, 0x64,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x41, 0x77, 0x61, 0x72, 0x64, 0x52, 0x05, 0x61,
	0x77, 0x61, 0x72, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x77, 0x69, 0x6e, 0x22, 0xb1, 0x01, 0x0a,
	0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x41, 0x77, 0x61, 0x72, 0x64, 0x12, 0x1b, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x15, 0x0a, 0x03, 0x77, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x03, 0x77, 0x69, 0x6e, 0x88, 0x01,
	0x01, 0x12, 0x21, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x02, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x03, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x42, 0x06,
	0x0a, 0x04, 0x5f, 0x77, 0x69, 0x6e, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6d, 0x61, 0x78, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x22, 0x9d, 0x01, 0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x41, 0x6c, 0x6c, 0x50,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x12, 0x21, 0x0a, 0x09, 0x66, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x66, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x66, 0x72, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x08, 0x66, 0x72, 0x65, 0x65, 0x52, 0x61,
	0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x66, 0x72, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65,
	0x22, 0x3b, 0x0a, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x26, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x63, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x5f, 0x43, 0x65, 0x6c, 0x6c, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x22, 0x66, 0x0a,
	0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x43, 0x65, 0x6c, 0x6c, 0x12, 0x1b, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x09, 0x69, 0x73, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x09,
	0x69, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07,
	0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x73, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_tmp_proto_rawDescOnce sync.Once
	file_tmp_proto_rawDescData = file_tmp_proto_rawDesc
)

func file_tmp_proto_rawDescGZIP() []byte {
	file_tmp_proto_rawDescOnce.Do(func() {
		file_tmp_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmp_proto_rawDescData)
	})
	return file_tmp_proto_rawDescData
}

var file_tmp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tmp_proto_goTypes = []interface{}{
	(*Custom_Block)(nil),      // 0: message.custom_Block
	(*Custom_Plate)(nil),      // 1: message.custom_Plate
	(*Custom_Award)(nil),      // 2: message.custom_Award
	(*Custom_AllPlate)(nil),   // 3: message.custom_AllPlate
	(*Custom_ColumnData)(nil), // 4: message.custom_ColumnData
	(*Custom_Cell)(nil),       // 5: message.custom_Cell
}
var file_tmp_proto_depIdxs = []int32{
	4, // 0: message.custom_Plate.column:type_name -> message.custom_ColumnData
	2, // 1: message.custom_Plate.award:type_name -> message.custom_Award
	1, // 2: message.custom_AllPlate.plate:type_name -> message.custom_Plate
	5, // 3: message.custom_ColumnData.row:type_name -> message.custom_Cell
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tmp_proto_init() }
func file_tmp_proto_init() {
	if File_tmp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tmp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Custom_Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Custom_Plate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Custom_Award); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Custom_AllPlate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Custom_ColumnData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Custom_Cell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tmp_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_tmp_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_tmp_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_tmp_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_tmp_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmp_proto_goTypes,
		DependencyIndexes: file_tmp_proto_depIdxs,
		MessageInfos:      file_tmp_proto_msgTypes,
	}.Build()
	File_tmp_proto = out.File
	file_tmp_proto_rawDesc = nil
	file_tmp_proto_goTypes = nil
	file_tmp_proto_depIdxs = nil
}
