// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pb/stats/stats.proto

package stats

import (
	_ "game/pb/_gen/pb"
	slots "game/pb/_gen/pb/slots"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=Data,proto3" `
}

func (x *JsonData) Reset() {
	*x = JsonData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonData) ProtoMessage() {}

func (x *JsonData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonData.ProtoReflect.Descriptor instead.
func (*JsonData) Descriptor() ([]byte, []int) {
	return file_pb_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *JsonData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetLast10DayRunTimeDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Game string `protobuf:"bytes,1,opt,name=Game,proto3" `
}

func (x *GetLast10DayRunTimeDataReq) Reset() {
	*x = GetLast10DayRunTimeDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLast10DayRunTimeDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLast10DayRunTimeDataReq) ProtoMessage() {}

func (x *GetLast10DayRunTimeDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLast10DayRunTimeDataReq.ProtoReflect.Descriptor instead.
func (*GetLast10DayRunTimeDataReq) Descriptor() ([]byte, []int) {
	return file_pb_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GetLast10DayRunTimeDataReq) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type GetLast10DayRunTimeDataResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	General *slots.ThreeMonkeyRunTimeResp  `protobuf:"bytes,1,opt,name=General,proto3" `
	BuyGame []*slots.SlotsStatsBuyGame_Doc `protobuf:"bytes,2,rep,name=BuyGame,proto3" `
}

func (x *GetLast10DayRunTimeDataResp) Reset() {
	*x = GetLast10DayRunTimeDataResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLast10DayRunTimeDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLast10DayRunTimeDataResp) ProtoMessage() {}

func (x *GetLast10DayRunTimeDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLast10DayRunTimeDataResp.ProtoReflect.Descriptor instead.
func (*GetLast10DayRunTimeDataResp) Descriptor() ([]byte, []int) {
	return file_pb_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetLast10DayRunTimeDataResp) GetGeneral() *slots.ThreeMonkeyRunTimeResp {
	if x != nil {
		return x.General
	}
	return nil
}

func (x *GetLast10DayRunTimeDataResp) GetBuyGame() []*slots.SlotsStatsBuyGame_Doc {
	if x != nil {
		return x.BuyGame
	}
	return nil
}

type GetTotalExpenseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Days int64  `protobuf:"varint,1,opt,name=Days,proto3" `
	Game string `protobuf:"bytes,2,opt,name=Game,proto3" `
}

func (x *GetTotalExpenseReq) Reset() {
	*x = GetTotalExpenseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalExpenseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalExpenseReq) ProtoMessage() {}

func (x *GetTotalExpenseReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalExpenseReq.ProtoReflect.Descriptor instead.
func (*GetTotalExpenseReq) Descriptor() ([]byte, []int) {
	return file_pb_stats_stats_proto_rawDescGZIP(), []int{3}
}

func (x *GetTotalExpenseReq) GetDays() int64 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *GetTotalExpenseReq) GetGame() string {
	if x != nil {
		return x.Game
	}
	return ""
}

type GetTotalExpenseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalExpense int64 `protobuf:"varint,1,opt,name=TotalExpense,proto3" ` // 总流水
	TotalIncome  int64 `protobuf:"varint,2,opt,name=TotalIncome,proto3" `   // 总产出
}

func (x *GetTotalExpenseResp) Reset() {
	*x = GetTotalExpenseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_stats_stats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTotalExpenseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalExpenseResp) ProtoMessage() {}

func (x *GetTotalExpenseResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_stats_stats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalExpenseResp.ProtoReflect.Descriptor instead.
func (*GetTotalExpenseResp) Descriptor() ([]byte, []int) {
	return file_pb_stats_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetTotalExpenseResp) GetTotalExpense() int64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

func (x *GetTotalExpenseResp) GetTotalIncome() int64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

var File_pb_stats_stats_proto protoreflect.FileDescriptor

var file_pb_stats_stats_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x1a, 0x13, 0x70,
	0x62, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x62, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x08, 0x4a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x30, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x31, 0x30, 0x44,
	0x61, 0x79, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x47, 0x61, 0x6d, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74,
	0x31, 0x30, 0x44, 0x61, 0x79, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x2e, 0x54, 0x68,
	0x72, 0x65, 0x65, 0x4d, 0x6f, 0x6e, 0x6b, 0x65, 0x79, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x36, 0x0a,
	0x07, 0x42, 0x75, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x73, 0x6c, 0x6f, 0x74, 0x73, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x42, 0x75, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x44, 0x6f, 0x63, 0x52, 0x07, 0x42, 0x75,
	0x79, 0x47, 0x61, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x44, 0x61, 0x79, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x47,
	0x61, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45,
	0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x65,
	0x32, 0xa8, 0x01, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x70, 0x63, 0x12, 0x4d, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x31, 0x30, 0x44,
	0x61, 0x79, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x2e,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x31, 0x30, 0x44,
	0x61, 0x79, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x48, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x78, 0x70,
	0x65, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x45, 0x78, 0x70, 0x65, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42, 0x62, 0x0a, 0x09, 0x63,
	0x6f, 0x6d, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x42, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x15, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x2f,
	0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0xa2, 0x02, 0x03,
	0x53, 0x58, 0x58, 0xaa, 0x02, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0xca, 0x02, 0x05, 0x53, 0x74,
	0x61, 0x74, 0x73, 0xe2, 0x02, 0x11, 0x53, 0x74, 0x61, 0x74, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_stats_stats_proto_rawDescOnce sync.Once
	file_pb_stats_stats_proto_rawDescData = file_pb_stats_stats_proto_rawDesc
)

func file_pb_stats_stats_proto_rawDescGZIP() []byte {
	file_pb_stats_stats_proto_rawDescOnce.Do(func() {
		file_pb_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_stats_stats_proto_rawDescData)
	})
	return file_pb_stats_stats_proto_rawDescData
}

var file_pb_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_stats_stats_proto_goTypes = []interface{}{
	(*JsonData)(nil),                     // 0: stats.JsonData
	(*GetLast10DayRunTimeDataReq)(nil),   // 1: stats.GetLast10DayRunTimeDataReq
	(*GetLast10DayRunTimeDataResp)(nil),  // 2: stats.GetLast10DayRunTimeDataResp
	(*GetTotalExpenseReq)(nil),           // 3: stats.GetTotalExpenseReq
	(*GetTotalExpenseResp)(nil),          // 4: stats.GetTotalExpenseResp
	(*slots.ThreeMonkeyRunTimeResp)(nil), // 5: slots.ThreeMonkeyRunTimeResp
	(*slots.SlotsStatsBuyGame_Doc)(nil),  // 6: slots.SlotsStatsBuyGame.Doc
}
var file_pb_stats_stats_proto_depIdxs = []int32{
	5, // 0: stats.GetLast10DayRunTimeDataResp.General:type_name -> slots.ThreeMonkeyRunTimeResp
	6, // 1: stats.GetLast10DayRunTimeDataResp.BuyGame:type_name -> slots.SlotsStatsBuyGame.Doc
	1, // 2: stats.AdminStatsRpc.GetLast10DayRunTimeData:input_type -> stats.GetLast10DayRunTimeDataReq
	3, // 3: stats.AdminStatsRpc.GetTotalExpense:input_type -> stats.GetTotalExpenseReq
	0, // 4: stats.AdminStatsRpc.GetLast10DayRunTimeData:output_type -> stats.JsonData
	4, // 5: stats.AdminStatsRpc.GetTotalExpense:output_type -> stats.GetTotalExpenseResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_stats_stats_proto_init() }
func file_pb_stats_stats_proto_init() {
	if File_pb_stats_stats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_stats_stats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stats_stats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLast10DayRunTimeDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stats_stats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLast10DayRunTimeDataResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stats_stats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalExpenseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_stats_stats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTotalExpenseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_stats_stats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_stats_stats_proto_goTypes,
		DependencyIndexes: file_pb_stats_stats_proto_depIdxs,
		MessageInfos:      file_pb_stats_stats_proto_msgTypes,
	}.Build()
	File_pb_stats_stats_proto = out.File
	file_pb_stats_stats_proto_rawDesc = nil
	file_pb_stats_stats_proto_goTypes = nil
	file_pb_stats_stats_proto_depIdxs = nil
}
