// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: tmp.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []int32                `protobuf:"varint,1,rep,packed,name=Row,proto3" json:"Row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_tmp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetRow() []int32 {
	if x != nil {
		return x.Row
	}
	return nil
}

type AwardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        int32                  `protobuf:"varint,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=Line,proto3" json:"Line,omitempty"`
	Win           float64                `protobuf:"fixed64,4,opt,name=Win,proto3" json:"Win,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwardData) Reset() {
	*x = AwardData{}
	mi := &file_tmp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwardData) ProtoMessage() {}

func (x *AwardData) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwardData.ProtoReflect.Descriptor instead.
func (*AwardData) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{1}
}

func (x *AwardData) GetSymbol() int32 {
	if x != nil {
		return x.Symbol
	}
	return 0
}

func (x *AwardData) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AwardData) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *AwardData) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

type RoundInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlateSymbol        []*Column              `protobuf:"bytes,1,rep,name=Plate_symbol,json=PlateSymbol,proto3" json:"Plate_symbol,omitempty"`
	AwardDataVec       []*AwardData           `protobuf:"bytes,2,rep,name=Award_data_vec,json=AwardDataVec,proto3" json:"Award_data_vec,omitempty"`
	AwardTypeFlag      int32                  `protobuf:"varint,3,opt,name=Award_type_flag,json=AwardTypeFlag,proto3" json:"Award_type_flag,omitempty"`
	FreeRemainRound    int32                  `protobuf:"varint,4,opt,name=Free_remain_round,json=FreeRemainRound,proto3" json:"Free_remain_round,omitempty"`
	FreeNowRound       int32                  `protobuf:"varint,5,opt,name=Free_now_round,json=FreeNowRound,proto3" json:"Free_now_round,omitempty"`
	FreeTotalRound     int32                  `protobuf:"varint,6,opt,name=Free_total_round,json=FreeTotalRound,proto3" json:"Free_total_round,omitempty"`
	AddRound           int32                  `protobuf:"varint,7,opt,name=Add_round,json=AddRound,proto3" json:"Add_round,omitempty"`
	RoundWin           float64                `protobuf:"fixed64,8,opt,name=Round_win,json=RoundWin,proto3" json:"Round_win,omitempty"`
	TotalMult          float64                `protobuf:"fixed64,9,opt,name=Total_mult,json=TotalMult,proto3" json:"Total_mult,omitempty"`
	WildExpandTimes    []int32                `protobuf:"varint,10,rep,packed,name=Wild_expand_times,json=WildExpandTimes,proto3" json:"Wild_expand_times,omitempty"`
	MaxFlag            bool                   `protobuf:"varint,11,opt,name=Max_flag,json=MaxFlag,proto3" json:"Max_flag,omitempty"`
	PlateSymbolChanged []*Column              `protobuf:"bytes,12,rep,name=Plate_symbol_changed,json=PlateSymbolChanged,proto3" json:"Plate_symbol_changed,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RoundInfo) Reset() {
	*x = RoundInfo{}
	mi := &file_tmp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundInfo) ProtoMessage() {}

func (x *RoundInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundInfo.ProtoReflect.Descriptor instead.
func (*RoundInfo) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{2}
}

func (x *RoundInfo) GetPlateSymbol() []*Column {
	if x != nil {
		return x.PlateSymbol
	}
	return nil
}

func (x *RoundInfo) GetAwardDataVec() []*AwardData {
	if x != nil {
		return x.AwardDataVec
	}
	return nil
}

func (x *RoundInfo) GetAwardTypeFlag() int32 {
	if x != nil {
		return x.AwardTypeFlag
	}
	return 0
}

func (x *RoundInfo) GetFreeRemainRound() int32 {
	if x != nil {
		return x.FreeRemainRound
	}
	return 0
}

func (x *RoundInfo) GetFreeNowRound() int32 {
	if x != nil {
		return x.FreeNowRound
	}
	return 0
}

func (x *RoundInfo) GetFreeTotalRound() int32 {
	if x != nil {
		return x.FreeTotalRound
	}
	return 0
}

func (x *RoundInfo) GetAddRound() int32 {
	if x != nil {
		return x.AddRound
	}
	return 0
}

func (x *RoundInfo) GetRoundWin() float64 {
	if x != nil {
		return x.RoundWin
	}
	return 0
}

func (x *RoundInfo) GetTotalMult() float64 {
	if x != nil {
		return x.TotalMult
	}
	return 0
}

func (x *RoundInfo) GetWildExpandTimes() []int32 {
	if x != nil {
		return x.WildExpandTimes
	}
	return nil
}

func (x *RoundInfo) GetMaxFlag() bool {
	if x != nil {
		return x.MaxFlag
	}
	return false
}

func (x *RoundInfo) GetPlateSymbolChanged() []*Column {
	if x != nil {
		return x.PlateSymbolChanged
	}
	return nil
}

type SpinAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundQueue    []*RoundInfo           `protobuf:"bytes,1,rep,name=Round_queue,json=RoundQueue,proto3" json:"Round_queue,omitempty"`
	FreeTotalWin  float64                `protobuf:"fixed64,2,opt,name=Free_total_win,json=FreeTotalWin,proto3" json:"Free_total_win,omitempty"`
	TotalWin      float64                `protobuf:"fixed64,3,opt,name=Total_win,json=TotalWin,proto3" json:"Total_win,omitempty"`
	ShowIndex     string                 `protobuf:"bytes,4,opt,name=Show_index,json=ShowIndex,proto3" json:"Show_index,omitempty"`
	NowMoney      float64                `protobuf:"fixed64,5,opt,name=Now_money,json=NowMoney,proto3" json:"Now_money,omitempty"`
	AckType       int32                  `protobuf:"varint,6,opt,name=Ack_type,json=AckType,proto3" json:"Ack_type,omitempty"`
	Bet           float64                `protobuf:"fixed64,7,opt,name=Bet,proto3" json:"Bet,omitempty"`
	RTP           float64                `protobuf:"fixed64,8,opt,name=RT_p,json=RTP,proto3" json:"RT_p,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinAck) Reset() {
	*x = SpinAck{}
	mi := &file_tmp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinAck) ProtoMessage() {}

func (x *SpinAck) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinAck.ProtoReflect.Descriptor instead.
func (*SpinAck) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{3}
}

func (x *SpinAck) GetRoundQueue() []*RoundInfo {
	if x != nil {
		return x.RoundQueue
	}
	return nil
}

func (x *SpinAck) GetFreeTotalWin() float64 {
	if x != nil {
		return x.FreeTotalWin
	}
	return 0
}

func (x *SpinAck) GetTotalWin() float64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *SpinAck) GetShowIndex() string {
	if x != nil {
		return x.ShowIndex
	}
	return ""
}

func (x *SpinAck) GetNowMoney() float64 {
	if x != nil {
		return x.NowMoney
	}
	return 0
}

func (x *SpinAck) GetAckType() int32 {
	if x != nil {
		return x.AckType
	}
	return 0
}

func (x *SpinAck) GetBet() float64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *SpinAck) GetRTP() float64 {
	if x != nil {
		return x.RTP
	}
	return 0
}

type GameInfoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowExtra     bool                   `protobuf:"varint,1,opt,name=Show_extra,json=ShowExtra,proto3" json:"Show_extra,omitempty"`
	Mul           []float64              `protobuf:"fixed64,2,rep,packed,name=Mul,proto3" json:"Mul,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInfoData) Reset() {
	*x = GameInfoData{}
	mi := &file_tmp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoData) ProtoMessage() {}

func (x *GameInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoData.ProtoReflect.Descriptor instead.
func (*GameInfoData) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{4}
}

func (x *GameInfoData) GetShowExtra() bool {
	if x != nil {
		return x.ShowExtra
	}
	return false
}

func (x *GameInfoData) GetMul() []float64 {
	if x != nil {
		return x.Mul
	}
	return nil
}

var File_tmp_proto protoreflect.FileDescriptor

const file_tmp_proto_rawDesc = "" +
	"\n" +
	"\ttmp.proto\x12\amessage\"\x1a\n" +
	"\x06Column\x12\x10\n" +
	"\x03Row\x18\x01 \x03(\x05R\x03Row\"_\n" +
	"\tAwardData\x12\x16\n" +
	"\x06Symbol\x18\x01 \x01(\x05R\x06Symbol\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x05R\x05Count\x12\x12\n" +
	"\x04Line\x18\x03 \x01(\x05R\x04Line\x12\x10\n" +
	"\x03Win\x18\x04 \x01(\x01R\x03Win\"\x80\x04\n" +
	"\tRoundInfo\x122\n" +
	"\fPlate_symbol\x18\x01 \x03(\v2\x0f.message.ColumnR\vPlateSymbol\x128\n" +
	"\x0eAward_data_vec\x18\x02 \x03(\v2\x12.message.AwardDataR\fAwardDataVec\x12&\n" +
	"\x0fAward_type_flag\x18\x03 \x01(\x05R\rAwardTypeFlag\x12*\n" +
	"\x11Free_remain_round\x18\x04 \x01(\x05R\x0fFreeRemainRound\x12$\n" +
	"\x0eFree_now_round\x18\x05 \x01(\x05R\fFreeNowRound\x12(\n" +
	"\x10Free_total_round\x18\x06 \x01(\x05R\x0eFreeTotalRound\x12\x1b\n" +
	"\tAdd_round\x18\a \x01(\x05R\bAddRound\x12\x1b\n" +
	"\tRound_win\x18\b \x01(\x01R\bRoundWin\x12\x1d\n" +
	"\n" +
	"Total_mult\x18\t \x01(\x01R\tTotalMult\x12*\n" +
	"\x11Wild_expand_times\x18\n" +
	" \x03(\x05R\x0fWildExpandTimes\x12\x19\n" +
	"\bMax_flag\x18\v \x01(\bR\aMaxFlag\x12A\n" +
	"\x14Plate_symbol_changed\x18\f \x03(\v2\x0f.message.ColumnR\x12PlateSymbolChanged\"\xfd\x01\n" +
	"\aSpinAck\x123\n" +
	"\vRound_queue\x18\x01 \x03(\v2\x12.message.RoundInfoR\n" +
	"RoundQueue\x12$\n" +
	"\x0eFree_total_win\x18\x02 \x01(\x01R\fFreeTotalWin\x12\x1b\n" +
	"\tTotal_win\x18\x03 \x01(\x01R\bTotalWin\x12\x1d\n" +
	"\n" +
	"Show_index\x18\x04 \x01(\tR\tShowIndex\x12\x1b\n" +
	"\tNow_money\x18\x05 \x01(\x01R\bNowMoney\x12\x19\n" +
	"\bAck_type\x18\x06 \x01(\x05R\aAckType\x12\x10\n" +
	"\x03Bet\x18\a \x01(\x01R\x03Bet\x12\x11\n" +
	"\x04RT_p\x18\b \x01(\x01R\x03RTP\"?\n" +
	"\fGameInfoData\x12\x1d\n" +
	"\n" +
	"Show_extra\x18\x01 \x01(\bR\tShowExtra\x12\x10\n" +
	"\x03Mul\x18\x02 \x03(\x01R\x03MulB'Z%serve/servicejili/jili_324_ed/messageb\x06proto3"

var (
	file_tmp_proto_rawDescOnce sync.Once
	file_tmp_proto_rawDescData []byte
)

func file_tmp_proto_rawDescGZIP() []byte {
	file_tmp_proto_rawDescOnce.Do(func() {
		file_tmp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tmp_proto_rawDesc), len(file_tmp_proto_rawDesc)))
	})
	return file_tmp_proto_rawDescData
}

var file_tmp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tmp_proto_goTypes = []any{
	(*Column)(nil),       // 0: message.Column
	(*AwardData)(nil),    // 1: message.AwardData
	(*RoundInfo)(nil),    // 2: message.RoundInfo
	(*SpinAck)(nil),      // 3: message.SpinAck
	(*GameInfoData)(nil), // 4: message.GameInfoData
}
var file_tmp_proto_depIdxs = []int32{
	0, // 0: message.RoundInfo.Plate_symbol:type_name -> message.Column
	1, // 1: message.RoundInfo.Award_data_vec:type_name -> message.AwardData
	0, // 2: message.RoundInfo.Plate_symbol_changed:type_name -> message.Column
	2, // 3: message.SpinAck.Round_queue:type_name -> message.RoundInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tmp_proto_init() }
func file_tmp_proto_init() {
	if File_tmp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tmp_proto_rawDesc), len(file_tmp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmp_proto_goTypes,
		DependencyIndexes: file_tmp_proto_depIdxs,
		MessageInfos:      file_tmp_proto_msgTypes,
	}.Build()
	File_tmp_proto = out.File
	file_tmp_proto_goTypes = nil
	file_tmp_proto_depIdxs = nil
}
