// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc2
// source: mcp.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SinglePlate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol []int32 `protobuf:"varint,1,rep,packed,name=Symbol,proto3" json:"Symbol,omitempty"`
}

func (x *SinglePlate) Reset() {
	*x = SinglePlate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SinglePlate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePlate) ProtoMessage() {}

func (x *SinglePlate) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePlate.ProtoReflect.Descriptor instead.
func (*SinglePlate) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *SinglePlate) GetSymbol() []int32 {
	if x != nil {
		return x.Symbol
	}
	return nil
}

type SpinAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlateSymbol []*SinglePlate `protobuf:"bytes,1,rep,name=Plate_symbol,json=PlateSymbol,proto3" json:"Plate_symbol,omitempty"`
	MainWin     float64        `protobuf:"fixed64,2,opt,name=Main_win,json=MainWin,proto3" json:"Main_win,omitempty"`
	ReSpinWin   float64        `protobuf:"fixed64,3,opt,name=Re_spin_win,json=ReSpinWin,proto3" json:"Re_spin_win,omitempty"`
	WheelWin    float64        `protobuf:"fixed64,4,opt,name=Wheel_win,json=WheelWin,proto3" json:"Wheel_win,omitempty"`
	TotalWin    float64        `protobuf:"fixed64,5,opt,name=Total_win,json=TotalWin,proto3" json:"Total_win,omitempty"`
	ShowIndex   string         `protobuf:"bytes,6,opt,name=Show_index,json=ShowIndex,proto3" json:"Show_index,omitempty"`
	NowMoney    float64        `protobuf:"fixed64,7,opt,name=Now_money,json=NowMoney,proto3" json:"Now_money,omitempty"`
	AckType     int32          `protobuf:"varint,8,opt,name=Ack_type,json=AckType,proto3" json:"Ack_type,omitempty"`
	RTP         float64        `protobuf:"fixed64,9,opt,name=RT_p,json=RTP,proto3" json:"RT_p,omitempty"`
	ShowType    int32          `protobuf:"varint,10,opt,name=Show_type,json=ShowType,proto3" json:"Show_type,omitempty"`
}

func (x *SpinAck) Reset() {
	*x = SpinAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpinAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinAck) ProtoMessage() {}

func (x *SpinAck) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinAck.ProtoReflect.Descriptor instead.
func (*SpinAck) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *SpinAck) GetPlateSymbol() []*SinglePlate {
	if x != nil {
		return x.PlateSymbol
	}
	return nil
}

func (x *SpinAck) GetMainWin() float64 {
	if x != nil {
		return x.MainWin
	}
	return 0
}

func (x *SpinAck) GetReSpinWin() float64 {
	if x != nil {
		return x.ReSpinWin
	}
	return 0
}

func (x *SpinAck) GetWheelWin() float64 {
	if x != nil {
		return x.WheelWin
	}
	return 0
}

func (x *SpinAck) GetTotalWin() float64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *SpinAck) GetShowIndex() string {
	if x != nil {
		return x.ShowIndex
	}
	return ""
}

func (x *SpinAck) GetNowMoney() float64 {
	if x != nil {
		return x.NowMoney
	}
	return 0
}

func (x *SpinAck) GetAckType() int32 {
	if x != nil {
		return x.AckType
	}
	return 0
}

func (x *SpinAck) GetRTP() float64 {
	if x != nil {
		return x.RTP
	}
	return 0
}

func (x *SpinAck) GetShowType() int32 {
	if x != nil {
		return x.ShowType
	}
	return 0
}

type GameInfoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WheelList  []*Wheel  `protobuf:"bytes,7,rep,name=Wheel_list,json=WheelList,proto3" json:"Wheel_list,omitempty"`
	AllBetList []float64 `protobuf:"fixed64,8,rep,packed,name=All_bet_list,json=AllBetList,proto3" json:"All_bet_list,omitempty"`
}

func (x *GameInfoData) Reset() {
	*x = GameInfoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfoData) ProtoMessage() {}

func (x *GameInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfoData.ProtoReflect.Descriptor instead.
func (*GameInfoData) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *GameInfoData) GetWheelList() []*Wheel {
	if x != nil {
		return x.WheelList
	}
	return nil
}

func (x *GameInfoData) GetAllBetList() []float64 {
	if x != nil {
		return x.AllBetList
	}
	return nil
}

type Wheel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mul []float64 `protobuf:"fixed64,1,rep,packed,name=Mul,proto3" json:"Mul,omitempty"`
}

func (x *Wheel) Reset() {
	*x = Wheel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mcp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wheel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wheel) ProtoMessage() {}

func (x *Wheel) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wheel.ProtoReflect.Descriptor instead.
func (*Wheel) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{3}
}

func (x *Wheel) GetMul() []float64 {
	if x != nil {
		return x.Mul
	}
	return nil
}

var File_mcp_proto protoreflect.FileDescriptor

var file_mcp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x63, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x6c,
	0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0xbe, 0x02, 0x0a, 0x07,
	0x53, 0x70, 0x69, 0x6e, 0x41, 0x63, 0x6b, 0x12, 0x37, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x6c,
	0x61, 0x74, 0x65, 0x52, 0x0b, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x19, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6e, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x07, 0x4d, 0x61, 0x69, 0x6e, 0x57, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0b, 0x52,
	0x65, 0x5f, 0x73, 0x70, 0x69, 0x6e, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x52, 0x65, 0x53, 0x70, 0x69, 0x6e, 0x57, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x57,
	0x68, 0x65, 0x65, 0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x57, 0x68, 0x65, 0x65, 0x6c, 0x57, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x57, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x68, 0x6f, 0x77, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x4e, 0x6f, 0x77, 0x5f, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x4e, 0x6f, 0x77, 0x4d, 0x6f, 0x6e, 0x65,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x41, 0x63, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x04,
	0x52, 0x54, 0x5f, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x52, 0x54, 0x50, 0x12,
	0x1b, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x77, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x53, 0x68, 0x6f, 0x77, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5f, 0x0a, 0x0c,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x0a,
	0x57, 0x68, 0x65, 0x65, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x57, 0x68, 0x65, 0x65, 0x6c,
	0x52, 0x09, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x41,
	0x6c, 0x6c, 0x5f, 0x62, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x0a, 0x41, 0x6c, 0x6c, 0x42, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x19, 0x0a,
	0x05, 0x57, 0x68, 0x65, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x75, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x01, 0x52, 0x03, 0x4d, 0x75, 0x6c, 0x42, 0x28, 0x5a, 0x26, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x6a, 0x69, 0x6c, 0x69, 0x2f, 0x6a, 0x69,
	0x6c, 0x69, 0x5f, 0x33, 0x30, 0x32, 0x5f, 0x6d, 0x63, 0x70, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mcp_proto_rawDescOnce sync.Once
	file_mcp_proto_rawDescData = file_mcp_proto_rawDesc
)

func file_mcp_proto_rawDescGZIP() []byte {
	file_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(file_mcp_proto_rawDescData)
	})
	return file_mcp_proto_rawDescData
}

var file_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mcp_proto_goTypes = []any{
	(*SinglePlate)(nil),  // 0: message.SinglePlate
	(*SpinAck)(nil),      // 1: message.SpinAck
	(*GameInfoData)(nil), // 2: message.GameInfoData
	(*Wheel)(nil),        // 3: message.Wheel
}
var file_mcp_proto_depIdxs = []int32{
	0, // 0: message.SpinAck.Plate_symbol:type_name -> message.SinglePlate
	3, // 1: message.GameInfoData.Wheel_list:type_name -> message.Wheel
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mcp_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SinglePlate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mcp_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SpinAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mcp_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GameInfoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mcp_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Wheel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mcp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
		MessageInfos:      file_mcp_proto_msgTypes,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_rawDesc = nil
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
