// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: serve/service_fish/application/lobbysetting/proto/lobby_setting.proto

package lobby_setting_proto

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	proto1 "serve/fish_comm/common/proto"
	proto2 "serve/service_fish/domain/auth/proto"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ConfigCall struct {
	Msgid           proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.proto.EMSGID" json:"msgid,omitempty"`
	Token           string        `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	GameId          string        `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ClearPowerCycle bool          `protobuf:"varint,4,opt,name=clear_power_cycle,json=clearPowerCycle,proto3" json:"clear_power_cycle,omitempty"`
	Version         uint32        `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	GameVersion     uint32        `protobuf:"varint,6,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`
	SubgameId       uint32        `protobuf:"varint,7,opt,name=subgame_id,json=subgameId,proto3" json:"subgame_id,omitempty"`
}

func (m *ConfigCall) Reset()         { *m = ConfigCall{} }
func (m *ConfigCall) String() string { return proto.CompactTextString(m) }
func (*ConfigCall) ProtoMessage()    {}
func (*ConfigCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_48c1a4a5af52133e, []int{0}
}
func (m *ConfigCall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigCall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigCall.Merge(m, src)
}
func (m *ConfigCall) XXX_Size() int {
	return m.Size()
}
func (m *ConfigCall) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigCall.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigCall proto.InternalMessageInfo

func (m *ConfigCall) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *ConfigCall) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ConfigCall) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *ConfigCall) GetClearPowerCycle() bool {
	if m != nil {
		return m.ClearPowerCycle
	}
	return false
}

func (m *ConfigCall) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ConfigCall) GetGameVersion() uint32 {
	if m != nil {
		return m.GameVersion
	}
	return 0
}

func (m *ConfigCall) GetSubgameId() uint32 {
	if m != nil {
		return m.SubgameId
	}
	return 0
}

type ConfigRecall struct {
	Msgid      proto1.EMSGID            `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.proto.EMSGID" json:"msgid,omitempty"`
	StatusCode proto1.Status_Code       `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3,enum=common.proto.Status_Code" json:"status_code,omitempty"`
	PlayerInfo *proto2.UserInfo         `protobuf:"bytes,3,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	RoomInfo   []*ConfigRecall_RoomInfo `protobuf:"bytes,4,rep,name=room_info,json=roomInfo,proto3" json:"room_info,omitempty"`
}

func (m *ConfigRecall) Reset()         { *m = ConfigRecall{} }
func (m *ConfigRecall) String() string { return proto.CompactTextString(m) }
func (*ConfigRecall) ProtoMessage()    {}
func (*ConfigRecall) Descriptor() ([]byte, []int) {
	return fileDescriptor_48c1a4a5af52133e, []int{1}
}
func (m *ConfigRecall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigRecall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigRecall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigRecall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRecall.Merge(m, src)
}
func (m *ConfigRecall) XXX_Size() int {
	return m.Size()
}
func (m *ConfigRecall) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRecall.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRecall proto.InternalMessageInfo

func (m *ConfigRecall) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *ConfigRecall) GetStatusCode() proto1.Status_Code {
	if m != nil {
		return m.StatusCode
	}
	return proto1.Status_kSuccess
}

func (m *ConfigRecall) GetPlayerInfo() *proto2.UserInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

func (m *ConfigRecall) GetRoomInfo() []*ConfigRecall_RoomInfo {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

type ConfigRecall_Bets struct {
	Bet []uint32 `protobuf:"varint,1,rep,packed,name=bet,proto3" json:"bet,omitempty"`
}

func (m *ConfigRecall_Bets) Reset()         { *m = ConfigRecall_Bets{} }
func (m *ConfigRecall_Bets) String() string { return proto.CompactTextString(m) }
func (*ConfigRecall_Bets) ProtoMessage()    {}
func (*ConfigRecall_Bets) Descriptor() ([]byte, []int) {
	return fileDescriptor_48c1a4a5af52133e, []int{1, 0}
}
func (m *ConfigRecall_Bets) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigRecall_Bets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigRecall_Bets.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigRecall_Bets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRecall_Bets.Merge(m, src)
}
func (m *ConfigRecall_Bets) XXX_Size() int {
	return m.Size()
}
func (m *ConfigRecall_Bets) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRecall_Bets.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRecall_Bets proto.InternalMessageInfo

func (m *ConfigRecall_Bets) GetBet() []uint32 {
	if m != nil {
		return m.Bet
	}
	return nil
}

type ConfigRecall_RoomInfo struct {
	GameId                string               `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	SubgameId             uint32               `protobuf:"varint,2,opt,name=subgame_id,json=subgameId,proto3" json:"subgame_id,omitempty"`
	Levels                []*ConfigRecall_Bets `protobuf:"bytes,3,rep,name=levels,proto3" json:"levels,omitempty"`
	Line                  []uint32             `protobuf:"varint,4,rep,packed,name=line,proto3" json:"line,omitempty"`
	Rates                 []uint32             `protobuf:"varint,5,rep,packed,name=rates,proto3" json:"rates,omitempty"`
	Languages             []string             `protobuf:"bytes,6,rep,name=languages,proto3" json:"languages,omitempty"`
	LanguagesDefaultIndex uint32               `protobuf:"varint,7,opt,name=languages_default_index,json=languagesDefaultIndex,proto3" json:"languages_default_index,omitempty"`
}

func (m *ConfigRecall_RoomInfo) Reset()         { *m = ConfigRecall_RoomInfo{} }
func (m *ConfigRecall_RoomInfo) String() string { return proto.CompactTextString(m) }
func (*ConfigRecall_RoomInfo) ProtoMessage()    {}
func (*ConfigRecall_RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48c1a4a5af52133e, []int{1, 1}
}
func (m *ConfigRecall_RoomInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigRecall_RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigRecall_RoomInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigRecall_RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRecall_RoomInfo.Merge(m, src)
}
func (m *ConfigRecall_RoomInfo) XXX_Size() int {
	return m.Size()
}
func (m *ConfigRecall_RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRecall_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRecall_RoomInfo proto.InternalMessageInfo

func (m *ConfigRecall_RoomInfo) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *ConfigRecall_RoomInfo) GetSubgameId() uint32 {
	if m != nil {
		return m.SubgameId
	}
	return 0
}

func (m *ConfigRecall_RoomInfo) GetLevels() []*ConfigRecall_Bets {
	if m != nil {
		return m.Levels
	}
	return nil
}

func (m *ConfigRecall_RoomInfo) GetLine() []uint32 {
	if m != nil {
		return m.Line
	}
	return nil
}

func (m *ConfigRecall_RoomInfo) GetRates() []uint32 {
	if m != nil {
		return m.Rates
	}
	return nil
}

func (m *ConfigRecall_RoomInfo) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *ConfigRecall_RoomInfo) GetLanguagesDefaultIndex() uint32 {
	if m != nil {
		return m.LanguagesDefaultIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfigCall)(nil), "lobby.setting.proto.ConfigCall")
	proto.RegisterType((*ConfigRecall)(nil), "lobby.setting.proto.ConfigRecall")
	proto.RegisterType((*ConfigRecall_Bets)(nil), "lobby.setting.proto.ConfigRecall.Bets")
	proto.RegisterType((*ConfigRecall_RoomInfo)(nil), "lobby.setting.proto.ConfigRecall.RoomInfo")
}

func init() {
	proto.RegisterFile("serve/service_fish/application/lobbysetting/proto/lobby_setting.proto", fileDescriptor_48c1a4a5af52133e)
}

var fileDescriptor_48c1a4a5af52133e = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xeb, 0xe6, 0x4f, 0x9b, 0x49, 0xdb, 0xdf, 0x8f, 0xa5, 0xa8, 0xa6, 0x82, 0xc8, 0xf4,
	0x80, 0xac, 0x4a, 0x5d, 0xd3, 0x20, 0x38, 0x70, 0x40, 0xa8, 0x29, 0xaa, 0x72, 0x40, 0x42, 0xae,
	0xe0, 0x6a, 0x6d, 0xec, 0x89, 0xbb, 0xea, 0x7a, 0x37, 0xf2, 0x6e, 0x02, 0xbd, 0xf2, 0x04, 0x5c,
	0x78, 0x27, 0x8e, 0x3d, 0x72, 0x44, 0xed, 0x03, 0xf0, 0x0a, 0x68, 0xd7, 0x4e, 0x9b, 0x00, 0x12,
	0xe2, 0x36, 0xf3, 0x99, 0xef, 0xcc, 0xce, 0xec, 0x0c, 0x0c, 0xc6, 0x5c, 0x9f, 0x1d, 0xe4, 0xac,
	0xc0, 0x03, 0x8d, 0xe5, 0x0c, 0xcb, 0x88, 0x4d, 0x26, 0x82, 0xa7, 0xcc, 0x70, 0x25, 0x23, 0xa1,
	0x46, 0xa3, 0x0b, 0x8d, 0xc6, 0x70, 0x99, 0x47, 0x93, 0x52, 0x19, 0x55, 0xa1, 0xa4, 0x66, 0xd4,
	0x31, 0x72, 0xd7, 0x41, 0xba, 0x04, 0x77, 0x87, 0x93, 0xf3, 0x3c, 0x2a, 0x54, 0x16, 0xe5, 0xdc,
	0x08, 0x36, 0xa2, 0x7c, 0x22, 0xd8, 0x85, 0x36, 0xac, 0xa4, 0x12, 0x4d, 0xb4, 0xf8, 0x62, 0xaa,
	0x8a, 0x42, 0xc9, 0x57, 0xb3, 0x27, 0xf4, 0x90, 0x1e, 0xd6, 0xcf, 0x54, 0xac, 0x2e, 0x75, 0xf0,
	0x5b, 0x93, 0x99, 0x2a, 0x18, 0x97, 0x11, 0x9b, 0x9a, 0xb3, 0x3a, 0xc1, 0x9a, 0x95, 0x7c, 0xef,
	0x87, 0x07, 0x30, 0x50, 0x72, 0xcc, 0xf3, 0x01, 0x13, 0x82, 0xec, 0x43, 0xab, 0xd0, 0x39, 0xcf,
	0x7c, 0x2f, 0xf0, 0xc2, 0xad, 0xfe, 0x36, 0x5d, 0xac, 0x4d, 0x5f, 0xbf, 0x39, 0x3d, 0x19, 0x1e,
	0xc7, 0x95, 0x84, 0x6c, 0x43, 0xcb, 0xa8, 0x73, 0x94, 0xfe, 0x6a, 0xe0, 0x85, 0x9d, 0xb8, 0x72,
	0xc8, 0x0e, 0xac, 0xd9, 0xc7, 0x13, 0x9e, 0xf9, 0x0d, 0xc7, 0xdb, 0xd6, 0x1d, 0x66, 0x64, 0x1f,
	0xee, 0xa4, 0x02, 0x59, 0x99, 0x4c, 0xd4, 0x07, 0x2c, 0x93, 0xf4, 0x22, 0x15, 0xe8, 0x37, 0x03,
	0x2f, 0x5c, 0x8f, 0xff, 0x73, 0x81, 0xb7, 0x96, 0x0f, 0x2c, 0x26, 0x3e, 0xac, 0xcd, 0xb0, 0xd4,
	0x5c, 0x49, 0xbf, 0x15, 0x78, 0xe1, 0x66, 0x3c, 0x77, 0xc9, 0x23, 0xd8, 0x70, 0xe5, 0xe7, 0xe1,
	0xb6, 0x0b, 0x77, 0x2d, 0x7b, 0x5f, 0x4b, 0x1e, 0x02, 0xe8, 0xe9, 0x68, 0xde, 0xc4, 0x9a, 0x13,
	0x74, 0x6a, 0x32, 0xcc, 0xf6, 0xbe, 0x34, 0x61, 0xa3, 0x9a, 0x38, 0xc6, 0xf4, 0x5f, 0x67, 0x7e,
	0x01, 0x5d, 0x6d, 0x98, 0x99, 0xea, 0x24, 0x55, 0x19, 0xba, 0xc9, 0xb7, 0xfa, 0xf7, 0x97, 0x33,
	0x4e, 0x9d, 0x80, 0x0e, 0x54, 0x86, 0x31, 0x54, 0x6a, 0x6b, 0x93, 0x67, 0xd0, 0xb5, 0x6b, 0xc5,
	0x32, 0xe1, 0x72, 0xac, 0xdc, 0xef, 0x74, 0xfb, 0xdb, 0xf4, 0x76, 0x19, 0xf4, 0x9d, 0xc6, 0x72,
	0x28, 0xc7, 0x2a, 0x86, 0x4a, 0x68, 0x6d, 0x72, 0x02, 0x9d, 0x52, 0xa9, 0xa2, 0x4a, 0x6a, 0x06,
	0x8d, 0xb0, 0xdb, 0xdf, 0xa7, 0x7f, 0x38, 0x22, 0xba, 0x38, 0x14, 0x8d, 0x95, 0x2a, 0x5c, 0xa9,
	0xf5, 0xb2, 0xb6, 0x76, 0x7d, 0x68, 0x1e, 0xa1, 0xd1, 0xe4, 0x7f, 0x68, 0x8c, 0xd0, 0xf8, 0x5e,
	0xd0, 0x08, 0x37, 0x63, 0x6b, 0xee, 0x7e, 0x5a, 0x85, 0xf5, 0x79, 0xc2, 0xe2, 0x02, 0xbd, 0xa5,
	0x05, 0x2e, 0xff, 0xeb, 0xea, 0x2f, 0xff, 0x4a, 0x5e, 0x42, 0x5b, 0xe0, 0x0c, 0x85, 0xf6, 0x1b,
	0xae, 0xc9, 0xc7, 0x7f, 0x6f, 0xd2, 0xb6, 0x13, 0xd7, 0x59, 0x84, 0x40, 0x53, 0x70, 0x89, 0x6e,
	0xc4, 0xcd, 0xd8, 0xd9, 0xf6, 0xc4, 0x4a, 0x66, 0x50, 0xfb, 0x2d, 0x07, 0x2b, 0x87, 0x3c, 0x80,
	0x8e, 0x60, 0x32, 0x9f, 0xb2, 0x1c, 0xb5, 0xdf, 0x0e, 0x1a, 0x61, 0x27, 0xbe, 0x05, 0xe4, 0x39,
	0xec, 0xdc, 0x38, 0x49, 0x86, 0x63, 0x36, 0x15, 0x26, 0xe1, 0x32, 0xc3, 0x8f, 0xf5, 0x2d, 0xdc,
	0xbb, 0x09, 0x1f, 0x57, 0xd1, 0xa1, 0x0d, 0x1e, 0xf9, 0x5f, 0xaf, 0x7a, 0xde, 0xe5, 0x55, 0xcf,
	0xfb, 0x7e, 0xd5, 0xf3, 0x3e, 0x5f, 0xf7, 0x56, 0x2e, 0xaf, 0x7b, 0x2b, 0xdf, 0xae, 0x7b, 0x2b,
	0xa3, 0xb6, 0x6b, 0xfd, 0xe9, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x57, 0x6f, 0xfc, 0x00,
	0x04, 0x00, 0x00,
}

func (m *ConfigCall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SubgameId != 0 {
		i = encodeVarintLobbySetting(dAtA, i, uint64(m.SubgameId))
		i--
		dAtA[i] = 0x38
	}
	if m.GameVersion != 0 {
		i = encodeVarintLobbySetting(dAtA, i, uint64(m.GameVersion))
		i--
		dAtA[i] = 0x30
	}
	if m.Version != 0 {
		i = encodeVarintLobbySetting(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x28
	}
	if m.ClearPowerCycle {
		i--
		if m.ClearPowerCycle {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.GameId) > 0 {
		i -= len(m.GameId)
		copy(dAtA[i:], m.GameId)
		i = encodeVarintLobbySetting(dAtA, i, uint64(len(m.GameId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintLobbySetting(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintLobbySetting(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConfigRecall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigRecall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigRecall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RoomInfo) > 0 {
		for iNdEx := len(m.RoomInfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RoomInfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLobbySetting(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.PlayerInfo != nil {
		{
			size, err := m.PlayerInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintLobbySetting(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.StatusCode != 0 {
		i = encodeVarintLobbySetting(dAtA, i, uint64(m.StatusCode))
		i--
		dAtA[i] = 0x10
	}
	if m.Msgid != 0 {
		i = encodeVarintLobbySetting(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConfigRecall_Bets) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigRecall_Bets) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigRecall_Bets) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Bet) > 0 {
		dAtA3 := make([]byte, len(m.Bet)*10)
		var j2 int
		for _, num := range m.Bet {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintLobbySetting(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConfigRecall_RoomInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigRecall_RoomInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConfigRecall_RoomInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LanguagesDefaultIndex != 0 {
		i = encodeVarintLobbySetting(dAtA, i, uint64(m.LanguagesDefaultIndex))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Languages) > 0 {
		for iNdEx := len(m.Languages) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Languages[iNdEx])
			copy(dAtA[i:], m.Languages[iNdEx])
			i = encodeVarintLobbySetting(dAtA, i, uint64(len(m.Languages[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.Rates) > 0 {
		dAtA5 := make([]byte, len(m.Rates)*10)
		var j4 int
		for _, num := range m.Rates {
			for num >= 1<<7 {
				dAtA5[j4] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j4++
			}
			dAtA5[j4] = uint8(num)
			j4++
		}
		i -= j4
		copy(dAtA[i:], dAtA5[:j4])
		i = encodeVarintLobbySetting(dAtA, i, uint64(j4))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Line) > 0 {
		dAtA7 := make([]byte, len(m.Line)*10)
		var j6 int
		for _, num := range m.Line {
			for num >= 1<<7 {
				dAtA7[j6] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j6++
			}
			dAtA7[j6] = uint8(num)
			j6++
		}
		i -= j6
		copy(dAtA[i:], dAtA7[:j6])
		i = encodeVarintLobbySetting(dAtA, i, uint64(j6))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Levels) > 0 {
		for iNdEx := len(m.Levels) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Levels[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLobbySetting(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.SubgameId != 0 {
		i = encodeVarintLobbySetting(dAtA, i, uint64(m.SubgameId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.GameId) > 0 {
		i -= len(m.GameId)
		copy(dAtA[i:], m.GameId)
		i = encodeVarintLobbySetting(dAtA, i, uint64(len(m.GameId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLobbySetting(dAtA []byte, offset int, v uint64) int {
	offset -= sovLobbySetting(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ConfigCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovLobbySetting(uint64(m.Msgid))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovLobbySetting(uint64(l))
	}
	l = len(m.GameId)
	if l > 0 {
		n += 1 + l + sovLobbySetting(uint64(l))
	}
	if m.ClearPowerCycle {
		n += 2
	}
	if m.Version != 0 {
		n += 1 + sovLobbySetting(uint64(m.Version))
	}
	if m.GameVersion != 0 {
		n += 1 + sovLobbySetting(uint64(m.GameVersion))
	}
	if m.SubgameId != 0 {
		n += 1 + sovLobbySetting(uint64(m.SubgameId))
	}
	return n
}

func (m *ConfigRecall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovLobbySetting(uint64(m.Msgid))
	}
	if m.StatusCode != 0 {
		n += 1 + sovLobbySetting(uint64(m.StatusCode))
	}
	if m.PlayerInfo != nil {
		l = m.PlayerInfo.Size()
		n += 1 + l + sovLobbySetting(uint64(l))
	}
	if len(m.RoomInfo) > 0 {
		for _, e := range m.RoomInfo {
			l = e.Size()
			n += 1 + l + sovLobbySetting(uint64(l))
		}
	}
	return n
}

func (m *ConfigRecall_Bets) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Bet) > 0 {
		l = 0
		for _, e := range m.Bet {
			l += sovLobbySetting(uint64(e))
		}
		n += 1 + sovLobbySetting(uint64(l)) + l
	}
	return n
}

func (m *ConfigRecall_RoomInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GameId)
	if l > 0 {
		n += 1 + l + sovLobbySetting(uint64(l))
	}
	if m.SubgameId != 0 {
		n += 1 + sovLobbySetting(uint64(m.SubgameId))
	}
	if len(m.Levels) > 0 {
		for _, e := range m.Levels {
			l = e.Size()
			n += 1 + l + sovLobbySetting(uint64(l))
		}
	}
	if len(m.Line) > 0 {
		l = 0
		for _, e := range m.Line {
			l += sovLobbySetting(uint64(e))
		}
		n += 1 + sovLobbySetting(uint64(l)) + l
	}
	if len(m.Rates) > 0 {
		l = 0
		for _, e := range m.Rates {
			l += sovLobbySetting(uint64(e))
		}
		n += 1 + sovLobbySetting(uint64(l)) + l
	}
	if len(m.Languages) > 0 {
		for _, s := range m.Languages {
			l = len(s)
			n += 1 + l + sovLobbySetting(uint64(l))
		}
	}
	if m.LanguagesDefaultIndex != 0 {
		n += 1 + sovLobbySetting(uint64(m.LanguagesDefaultIndex))
	}
	return n
}

func sovLobbySetting(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLobbySetting(x uint64) (n int) {
	return sovLobbySetting(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConfigCall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLobbySetting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigCall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigCall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLobbySetting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLobbySetting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClearPowerCycle", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ClearPowerCycle = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameVersion", wireType)
			}
			m.GameVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GameVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubgameId", wireType)
			}
			m.SubgameId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubgameId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLobbySetting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigRecall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLobbySetting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigRecall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigRecall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			m.StatusCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusCode |= proto1.Status_Code(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLobbySetting
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PlayerInfo == nil {
				m.PlayerInfo = &proto2.UserInfo{}
			}
			if err := m.PlayerInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLobbySetting
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomInfo = append(m.RoomInfo, &ConfigRecall_RoomInfo{})
			if err := m.RoomInfo[len(m.RoomInfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLobbySetting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigRecall_Bets) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLobbySetting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Bets: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Bets: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLobbySetting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Bet = append(m.Bet, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLobbySetting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthLobbySetting
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthLobbySetting
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Bet) == 0 {
					m.Bet = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLobbySetting
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Bet = append(m.Bet, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Bet", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLobbySetting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigRecall_RoomInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLobbySetting
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoomInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoomInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLobbySetting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubgameId", wireType)
			}
			m.SubgameId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubgameId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Levels", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLobbySetting
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Levels = append(m.Levels, &ConfigRecall_Bets{})
			if err := m.Levels[len(m.Levels)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLobbySetting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Line = append(m.Line, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLobbySetting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthLobbySetting
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthLobbySetting
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Line) == 0 {
					m.Line = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLobbySetting
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Line = append(m.Line, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Line", wireType)
			}
		case 5:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLobbySetting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.Rates = append(m.Rates, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowLobbySetting
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthLobbySetting
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthLobbySetting
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.Rates) == 0 {
					m.Rates = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowLobbySetting
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.Rates = append(m.Rates, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field Rates", wireType)
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Languages", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLobbySetting
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Languages = append(m.Languages, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LanguagesDefaultIndex", wireType)
			}
			m.LanguagesDefaultIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LanguagesDefaultIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLobbySetting(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthLobbySetting
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLobbySetting(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLobbySetting
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLobbySetting
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLobbySetting
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLobbySetting
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLobbySetting
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLobbySetting        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLobbySetting          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLobbySetting = fmt.Errorf("proto: unexpected end of group")
)
