// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pb/gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid int64 `protobuf:"varint,1,opt,name=Pid,proto3" `
}

func (x *OnlineReq) Reset() {
	*x = OnlineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReq) ProtoMessage() {}

func (x *OnlineReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReq.ProtoReflect.Descriptor instead.
func (*OnlineReq) Descriptor() ([]byte, []int) {
	return file_pb_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineReq) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type OnlineResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineResp) Reset() {
	*x = OnlineResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineResp) ProtoMessage() {}

func (x *OnlineResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineResp.ProtoReflect.Descriptor instead.
func (*OnlineResp) Descriptor() ([]byte, []int) {
	return file_pb_gateway_proto_rawDescGZIP(), []int{1}
}

var File_pb_gateway_proto protoreflect.FileDescriptor

var file_pb_gateway_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x09, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x69,
	0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32,
	0x50, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x21, 0x0a, 0x06, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0a, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x0b, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x07, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0a, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x42, 0x21, 0x42, 0x0c, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x0f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x5f, 0x67, 0x65,
	0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_gateway_proto_rawDescOnce sync.Once
	file_pb_gateway_proto_rawDescData = file_pb_gateway_proto_rawDesc
)

func file_pb_gateway_proto_rawDescGZIP() []byte {
	file_pb_gateway_proto_rawDescOnce.Do(func() {
		file_pb_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_gateway_proto_rawDescData)
	})
	return file_pb_gateway_proto_rawDescData
}

var file_pb_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_gateway_proto_goTypes = []interface{}{
	(*OnlineReq)(nil),  // 0: OnlineReq
	(*OnlineResp)(nil), // 1: OnlineResp
}
var file_pb_gateway_proto_depIdxs = []int32{
	0, // 0: General.Online:input_type -> OnlineReq
	0, // 1: General.Offline:input_type -> OnlineReq
	1, // 2: General.Online:output_type -> OnlineResp
	1, // 3: General.Offline:output_type -> OnlineResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_gateway_proto_init() }
func file_pb_gateway_proto_init() {
	if File_pb_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_gateway_proto_goTypes,
		DependencyIndexes: file_pb_gateway_proto_depIdxs,
		MessageInfos:      file_pb_gateway_proto_msgTypes,
	}.Build()
	File_pb_gateway_proto = out.File
	file_pb_gateway_proto_rawDesc = nil
	file_pb_gateway_proto_goTypes = nil
	file_pb_gateway_proto_depIdxs = nil
}
