export const COUNTRY_LIST =[
    {
        label:"全部",
        value: "ALL"
    },
    {
        label:"阿富汗",
        value: "Afghanistan"
    },
    {
        label:"阿尔巴尼亚",
        value:"Albania"
    },
    {
        label:"阿尔及利亚",
        value:"Algeria"
    },
    {
        label:"安道尔",
        value:"Andorra"
    },
    {
        label:"安哥拉",
        value:"Angola"
    },
    {
        label:"安提瓜和巴布达",
        value:"Antigua_and_Barbuda"
    },
    {
        label:"阿根廷",
        value:"Argentina"
    },
    {
        label:"亚美尼亚",
        value:"Armenia"
    },
    {
        label:"澳大利亚",
        value:"Australia"
    },
    {
        label:"奥地利",
        value:"Austria"
    },
    {
        label:"阿塞拜疆",
        value:"Azerbaijan"
    },
    {
        label:"巴哈马",
        value:"Bahamas"
    },
    {
        label:"巴林",
        value:"Bahrain"
    },
    {
        label:"孟加拉国",
        value:"Bangladesh"
    },
    {
        label:"巴巴多斯",
        value:"Barbados"
    },
    {
        label:"白俄罗斯",
        value:"Belarus"
    },
    {
        label:"比利时",
        value:"Belgium"
    },
    {
        label:"伯利兹",
        value:"Belize"
    },
    {
        label:"贝宁",
        value:"Benin"
    },
    {
        label:"不丹",
        value:"Bhutan"
    },
    {
        label:"玻利维亚",
        value:"Bolivia"
    },
    {
        label:"波黑",
        value:"Bosnia_and_Herzegovina"
    },
    {
        label:"博茨瓦纳",
        value:"Botswana"
    },
    {
        label:"巴西",
        value:"Brazil"
    },
    {
        label:"文莱",
        value:"Brunei"
    },
    {
        label:"保加利亚",
        value:"Bulgaria"
    },
    {
        label:"布基纳法索",
        value:"Burkina_Faso"
    },
    {
        label:"布隆迪",
        value:"Burundi"
    },
    {
        label:"佛得角",
        value:"Cabo_Verde"
    },
    {
        label:"柬埔寨",
        value:"Cambodia"
    },
    {
        label:"喀麦隆",
        value:"Cameroon"
    },
    {
        label:"加拿大",
        value:"Canada"
    },
    {
        label:"中非共和国",
        value:"Central_African_Republic"
    },
    {
        label:"乍得",
        value:"Chad"
    },
    {
        label:"智利",
        value:"Chile"
    },
    {
        label:"中国",
        value:"China"
    },
    {
        label:"哥伦比亚",
        value:"Colombia"
    },
    {
        label:"科摩罗",
        value:"Comoros"
    },
    {
        label:"刚果民主共和国",
        value:"Congo_Democratic_Republic_of_the"
    },
    {
        label:"刚果共和国",
        value:"Congo_Republic_of_the"
    },
    {
        label:"哥斯达黎加",
        value:"Costa_Rica"
    },
    {
        label:"克罗地亚",
        value:"Croatia"
    },
    {
        label:"古巴",
        value:"Cuba"
    },
    {
        label:"塞浦路斯",
        value:"Cyprus"
    },
    {
        label:"捷克",
        value:"Czech_Republic"
    },
    {
        label:"丹麦",
        value:"Denmark"
    },
    {
        label:"吉布提",
        value:"Djibouti"
    },
    {
        label:"多米尼克",
        value:"Dominica"
    },
    {
        label:"多米尼加共和国",
        value:"Dominican_Republic"
    },
    {
        label:"东帝汶",
        value:"Leste"
    },
    {
        label:"厄瓜多尔",
        value:"Ecuador"
    },
    {
        label:"埃及",
        value:"Egypt"
    },
    {
        label:"萨尔瓦多",
        value:"El_Salvador"
    },
    {
        label:"赤道几内亚",
        value:"Equatorial_Guinea"
    },
    {
        label:"厄立特里亚",
        value:"Eritrea"
    },
    {
        label:"爱沙尼亚",
        value:"Estonia"
    },
    {
        label:"埃斯瓦蒂尼",
        value:"Eswatini"
    },
    {
        label:"埃塞俄比亚",
        value:"Ethiopia"
    },
    {
        label:"斐济",
        value:"Fiji"
    },
    {
        label:"芬兰",
        value:"Finland"
    },
    {
        label:"法国",
        value:"France"
    },
    {
        label:"加蓬",
        value:"Gabon"
    },
    {
        label:"冈比亚",
        value:"Gambia"
    },
    {
        label:"格鲁吉亚",
        value:"Georgia"
    },
    {
        label:"德国",
        value:"Germany"
    },
    {
        label:"加纳",
        value:"Ghana"
    },
    {
        label:"希腊",
        value:"Greece"
    },
    {
        label:"格林纳达",
        value:"Grenada"
    },
    {
        label:"危地马拉",
        value:"Guatemala"
    },
    {
        label:"几内亚",
        value:"Guinea"
    },
    {
        label:"几内亚比绍",
        value:"Bissau"
    },
    {
        label:"圭亚那",
        value:"Guyana"
    },
    {
        label:"海地",
        value:"Haiti"
    },
    {
        label:"洪都拉斯",
        value:"Honduras"
    },
    {
        label:"匈牙利",
        value:"Hungary"
    },
    {
        label:"冰岛",
        value:"Iceland"
    },
    {
        label:"印度",
        value:"India"
    },
    {
        label:"印度尼西亚",
        value:"Indonesia"
    },
    {
        label:"伊朗",
        value:"Iran"
    },
    {
        label:"伊拉克",
        value:"Iraq"
    },
    {
        label:"爱尔兰",
        value:"Ireland"
    },
    {
        label:"以色列",
        value:"Israel"
    },
    {
        label:"意大利",
        value:"Italy"
    },
    {
        label:"牙买加",
        value:"Jamaica"
    },
    {
        label:"日本",
        value:"Japan"
    },
    {
        label:"约旦",
        value:"Jordan"
    },
    {
        label:"哈萨克斯坦",
        value:"Kazakhstan"
    },
    {
        label:"肯尼亚",
        value:"Kenya"
    },
    {
        label:"基里巴斯",
        value:"Kiribati"
    },
    {
        label:"朝鲜",
        value:"North_Korea"
    },
    {
        label:"韩国",
        value:"South_Korea"
    },
    {
        label:"科威特",
        value:"Kuwait"
    },
    {
        label:"吉尔吉斯斯坦",
        value:"Kyrgyzstan"
    },
    {
        label:"老挝",
        value:"Laos"
    },
    {
        label:"拉脱维亚",
        value:"Latvia"
    },
    {
        label:"黎巴嫩",
        value:"Lebanon"
    },
    {
        label:"莱索托",
        value:"Lesotho"
    },
    {
        label:"利比里亚",
        value:"Liberia"
    },
    {
        label:"利比亚",
        value:"Libya"
    },
    {
        label:"列支敦士登",
        value:"Liechtenstein"
    },
    {
        label:"立陶宛",
        value:"Lithuania"
    },
    {
        label:"卢森堡",
        value:"Luxembourg"
    },
    {
        label:"马达加斯加",
        value:"Madagascar"
    },
    {
        label:"马拉维",
        value:"Malawi"
    },
    {
        label:"马来西亚",
        value:"Malaysia"
    },
    {
        label:"马尔代夫",
        value:"Maldives"
    },
    {
        label:"马里",
        value:"Mali"
    },
    {
        label:"马耳他",
        value:"Malta"
    },
    {
        label:"马绍尔群岛",
        value:"Marshall_Islands"
    },
    {
        label:"毛里塔尼亚",
        value:"Mauritania"
    },
    {
        label:"毛里求斯",
        value:"Mauritius"
    },
    {
        label:"墨西哥",
        value:"Mexico"
    },
    {
        label:"密克罗尼西亚",
        value:"Micronesia"
    },
    {
        label:"摩尔多瓦",
        value:"Moldova"
    },
    {
        label:"摩纳哥",
        value:"Monaco"
    },
    {
        label:"蒙古",
        value:"Mongolia"
    },
    {
        label:"黑山",
        value:"Montenegro"
    },
    {
        label:"摩洛哥",
        value:"Morocco"
    },
    {
        label:"莫桑比克",
        value:"Mozambique"
    },
    {
        label:"缅甸",
        value:"Myanmar"
    },
    {
        label:"纳米比亚",
        value:"Namibia"
    },
    {
        label:"瑙鲁",
        value:"Nauru"
    },
    {
        label:"尼泊尔",
        value:"Nepal"
    },
    {
        label:"荷兰",
        value:"Netherlands"
    },
    {
        label:"新西兰",
        value:"New_Zealand"
    },
    {
        label:"尼加拉瓜",
        value:"Nicaragua"
    },
    {
        label:"尼日尔",
        value:"Niger"
    },
    {
        label:"尼日利亚",
        value:"Nigeria"
    },
    {
        label:"挪威",
        value:"Norway"
    },
    {
        label:"阿曼",
        value:"Oman"
    },
    {
        label:"巴基斯坦",
        value:"Pakistan"
    },
    {
        label:"帕劳",
        value:"Palau"
    },
    {
        label:"巴勒斯坦",
        value:"Palestine"
    },
    {
        label:"巴拿马",
        value:"Panama"
    },
    {
        label:"巴布亚新几内亚",
        value:"Papua_New_Guinea"
    },
    {
        label:"巴拉圭",
        value:"Paraguay"
    },
    {
        label:"秘鲁",
        value:"Peru"
    },
    {
        label:"菲律宾",
        value:"Philippines"
    },
    {
        label:"波兰",
        value:"Poland"
    },
    {
        label:"葡萄牙",
        value:"Portugal"
    },
    {
        label:"卡塔尔",
        value:"Qatar"
    },
    {
        label:"罗马尼亚",
        value:"Romania"
    },
    {
        label:"俄罗斯",
        value:"Russia"
    },
    {
        label:"卢旺达",
        value:"Rwanda"
    },
    {
        label:"圣基茨和尼维斯",
        value:"Saint_Kitts_and_Nevis"
    },
    {
        label:"圣卢西亚",
        value:"Saint_Lucia"
    },
    {
        label:"圣文森特和格林纳丁斯",
        value:"Saint_Vincent_and_the_Grenadines"
    },
    {
        label:"萨摩亚",
        value:"Samoa"
    },
    {
        label:"圣马力诺",
        value:"San_Marino"
    },
    {
        label:"圣多美和普林西比",
        value:"Sao_Tome_and_Principe"
    },
    {
        label:"沙特阿拉伯",
        value:"Saudi_Arabia"
    },
    {
        label:"塞内加尔",
        value:"Senegal"
    },
    {
        label:"塞尔维亚",
        value:"Serbia"
    },
    {
        label:"塞舌尔",
        value:"Seychelles"
    },
    {
        label:"塞拉利昂",
        value:"Sierra_Leone"
    },
    {
        label:"新加坡",
        value:"Singapore"
    },
    {
        label:"斯洛伐克",
        value:"Slovakia"
    },
    {
        label:"斯洛文尼亚",
        value:"Slovenia"
    },
    {
        label:"所罗门群岛",
        value:"Solomon_Islands"
    },
    {
        label:"索马里",
        value:"Somalia"
    },
    {
        label:"南非",
        value:"South_Africa"
    },
    {
        label:"南苏丹",
        value:"South_Sudan"
    },
    {
        label:"西班牙",
        value:"Spain"
    },
    {
        label:"斯里兰卡",
        value:"Sri_Lanka"
    },
    {
        label:"苏丹",
        value:"Sudan"
    },
    {
        label:"苏里南",
        value:"Suriname"
    },
    {
        label:"瑞典",
        value:"Sweden"
    },
    {
        label:"瑞士",
        value:"Switzerland"
    },
    {
        label:"叙利亚",
        value:"Syria"
    },
    {
        label:"塔吉克斯坦",
        value:"Tajikistan"
    },
    {
        label:"坦桑尼亚",
        value:"Tanzania"
    },
    {
        label:"泰国",
        value:"Thailand"
    },
    {
        label:"多哥",
        value:"Togo"
    },
    {
        label:"汤加",
        value:"Tonga"
    },
    {
        label:"特立尼达和多巴哥",
        value:"Trinidad_and_Tobago"
    },
    {
        label:"突尼斯",
        value:"Tunisia"
    },
    {
        label:"土耳其",
        value:"Turkey"
    },
    {
        label:"土库曼斯坦",
        value:"Turkmenistan"
    },
    {
        label:"图瓦卢",
        value:"Tuvalu"
    },
    {
        label:"乌干达",
        value:"Uganda"
    },
    {
        label:"乌克兰",
        value:"Ukraine"
    },
    {
        label:"阿拉伯联合酋长国",
        value:"United_Arab_Emirates"
    },
    {
        label:"英国",
        value:"United_Kingdom"
    },
    {
        label:"美国",
        value:"United_States"
    },
    {
        label:"乌拉圭",
        value:"Uruguay"
    },
    {
        label:"乌兹别克斯坦",
        value:"Uzbekistan"
    },
    {
        label:"瓦努阿图",
        value:"Vanuatu"
    },
    {
        label:"梵蒂冈",
        value:"Vatican_City"
    },
    {
        label:"委内瑞拉",
        value:"Venezuela"
    },
    {
        label:"越南",
        value:"Vietnam"
    },
    {
        label:"也门",
        value:"Yemen"
    },
    {
        label:"赞比亚",
        value:"Zambia"
    },
    {
        label:"津巴布韦",
        value:"Zimbabwe"
    }
]


export const BALANCE_OPERATOR_TYPE = [
    {
        label:"充值",
        value: 1,
    },
    {
        label:"扣款",
        value: 2,
    }
]




export const BALANCE_THRESHOLD = [
    {
        label:"不提醒",
        value: 0
    },
    {
        label:"每次登录提示",
        value: 1
    },
    {
        label:"每日登录",
        value: 2
    }
]


export const ARREARS_HINT_INTERVAL = [

    {
        label:"不提醒",
        value: 2100000000
    },
    {
        label:"1小时",
        value: 3600000
    },
    {
        label:"30分钟",
        value: 1800000
    },
    {
        label:"10分钟",
        value: 600000
    }
]

export const CREATE_MERCHANT_RULE = [
    {
        label:"需要审核",
        value: 0
    },
    {
        label:"无需审核",
        value: 1
    },
    {
        label:"不可开户",
        value: 2
    }
]


export const LANG_LIST = [
    {label: "中文", value: "zh"},
    {label: "泰文", value: "th"},
    {label: "英文", value: "en"},
    {label: "印尼语", value: "idr"},
    {label: "意大利", value: "it"},
    {label: "西班牙", value: "es"},

]
