// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pb/gamepb/customer.proto

package gamepb

import (
	pb "game/pb/_gen/pb"
	mongodb "game/duck/mongodb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameType int32

const (
	GameType_Slot  GameType = 0 // 拉霸游戏
	GameType_Fish  GameType = 1 // 捕鱼游戏
	GameType_Poker GameType = 3 // 棋牌游戏
)

// Enum value maps for GameType.
var (
	GameType_name = map[int32]string{
		0: "Slot",
		1: "Fish",
		3: "Poker",
	}
	GameType_value = map[string]int32{
		"Slot":  0,
		"Fish":  1,
		"Poker": 3,
	}
)

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}

func (x GameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_gamepb_customer_proto_enumTypes[0].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
	return &file_pb_gamepb_customer_proto_enumTypes[0]
}

func (x GameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{0}
}

type GameStatus int32

const (
	GameStatus_Open        GameStatus = 0 // 正常
	GameStatus_Maintenance GameStatus = 1 // 维护中（列表中出现）
	GameStatus_Hide        GameStatus = 2 // 隐藏（列表中不出现）
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "Open",
		1: "Maintenance",
		2: "Hide",
	}
	GameStatus_value = map[string]int32{
		"Open":        0,
		"Maintenance": 1,
		"Hide":        2,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_gamepb_customer_proto_enumTypes[1].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_pb_gamepb_customer_proto_enumTypes[1]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{1}
}

type DocBetLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         *mongodb.ObjectID  `protobuf:"bytes,1,opt,name=ID,proto3" bson:"_id"`
	Pid        int64              `protobuf:"varint,2,opt,name=Pid,proto3" `              // 内部玩家ID
	UserID     string             `protobuf:"bytes,3,opt,name=UserID,proto3" `         // 外部玩家ID
	GameID     string             `protobuf:"bytes,4,opt,name=GameID,proto3" `         // 游戏ID
	RoundID    string             `protobuf:"bytes,5,opt,name=RoundID,proto3" `       // 对局ID，方便查询
	Bet        int64              `protobuf:"varint,6,opt,name=Bet,proto3" `              // 下注
	Win        int64              `protobuf:"varint,7,opt,name=Win,proto3" `              // 输赢
	Comment    string             `protobuf:"bytes,8,opt,name=Comment,proto3" `       // 注释
	InsertTime *mongodb.TimeStamp `protobuf:"bytes,9,opt,name=InsertTime,proto3" ` // 数据插入时间
	AppID      string             `protobuf:"bytes,10,opt,name=AppID,proto3" `          //
	Balance    int64              `protobuf:"varint,11,opt,name=Balance,proto3" `     // 余额
}

func (x *DocBetLog) Reset() {
	*x = DocBetLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocBetLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocBetLog) ProtoMessage() {}

func (x *DocBetLog) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocBetLog.ProtoReflect.Descriptor instead.
func (*DocBetLog) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{0}
}

func (x *DocBetLog) GetID() *mongodb.ObjectID {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *DocBetLog) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DocBetLog) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DocBetLog) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

func (x *DocBetLog) GetRoundID() string {
	if x != nil {
		return x.RoundID
	}
	return ""
}

func (x *DocBetLog) GetBet() int64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *DocBetLog) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *DocBetLog) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *DocBetLog) GetInsertTime() *mongodb.TimeStamp {
	if x != nil {
		return x.InsertTime
	}
	return nil
}

func (x *DocBetLog) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *DocBetLog) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type DocBetLogList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DocBetLog `protobuf:"bytes,1,rep,name=List,proto3" `
}

func (x *DocBetLogList) Reset() {
	*x = DocBetLogList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocBetLogList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocBetLogList) ProtoMessage() {}

func (x *DocBetLogList) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocBetLogList.ProtoReflect.Descriptor instead.
func (*DocBetLogList) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{1}
}

func (x *DocBetLogList) GetList() []*DocBetLog {
	if x != nil {
		return x.List
	}
	return nil
}

type GetLogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From *mongodb.TimeStamp `protobuf:"bytes,1,opt,name=From,proto3" `
}

func (x *GetLogReq) Reset() {
	*x = GetLogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogReq) ProtoMessage() {}

func (x *GetLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogReq.ProtoReflect.Descriptor instead.
func (*GetLogReq) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{2}
}

func (x *GetLogReq) GetFrom() *mongodb.TimeStamp {
	if x != nil {
		return x.From
	}
	return nil
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   string `protobuf:"bytes,1,opt,name=UserID,proto3" `     // 玩家id
	GameID   string `protobuf:"bytes,2,opt,name=GameID,proto3" `     // 游戏ID
	Language string `protobuf:"bytes,3,opt,name=Language,proto3" ` // 游戏语言
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LoginReq) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

func (x *LoginReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=Url,proto3" ` // 游戏启动链接
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string     `protobuf:"bytes,1,opt,name=ID,proto3" bson:"_id"`
	Name   string     `protobuf:"bytes,2,opt,name=Name,proto3" `
	Type   GameType   `protobuf:"varint,3,opt,name=Type,proto3,enum=GameType" `
	Status GameStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=GameStatus" `
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{5}
}

func (x *Game) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetType() GameType {
	if x != nil {
		return x.Type
	}
	return GameType_Slot
}

func (x *Game) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_Open
}

type GameListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Game `protobuf:"bytes,1,rep,name=List,proto3" `
}

func (x *GameListResp) Reset() {
	*x = GameListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameListResp) ProtoMessage() {}

func (x *GameListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameListResp.ProtoReflect.Descriptor instead.
func (*GameListResp) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{6}
}

func (x *GameListResp) GetList() []*Game {
	if x != nil {
		return x.List
	}
	return nil
}

type ModifyGoldUidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  string `protobuf:"bytes,1,opt,name=UserID,proto3" `   // 玩家ID
	Change  int64  `protobuf:"varint,2,opt,name=Change,proto3" `  // 金币变化：>0 加钱， <0 扣钱
	Comment string `protobuf:"bytes,3,opt,name=Comment,proto3" ` // 注释
}

func (x *ModifyGoldUidReq) Reset() {
	*x = ModifyGoldUidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyGoldUidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyGoldUidReq) ProtoMessage() {}

func (x *ModifyGoldUidReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyGoldUidReq.ProtoReflect.Descriptor instead.
func (*ModifyGoldUidReq) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{7}
}

func (x *ModifyGoldUidReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ModifyGoldUidReq) GetChange() int64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *ModifyGoldUidReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetBalanceUidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" `
}

func (x *GetBalanceUidReq) Reset() {
	*x = GetBalanceUidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceUidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceUidReq) ProtoMessage() {}

func (x *GetBalanceUidReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceUidReq.ProtoReflect.Descriptor instead.
func (*GetBalanceUidReq) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalanceUidReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetBalanceUidResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance int64 `protobuf:"varint,1,opt,name=Balance,proto3" `
}

func (x *GetBalanceUidResp) Reset() {
	*x = GetBalanceUidResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_customer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceUidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceUidResp) ProtoMessage() {}

func (x *GetBalanceUidResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_customer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceUidResp.ProtoReflect.Descriptor instead.
func (*GetBalanceUidResp) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_customer_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalanceUidResp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_pb_gamepb_customer_proto protoreflect.FileDescriptor

var file_pb_gamepb_customer_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2f, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70, 0x62, 0x2f, 0x64,
	0x75, 0x63, 0x6b, 0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65,
	0x53, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x62, 0x2f,
	0x64, 0x75, 0x63, 0x6b, 0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x62, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9c, 0x02, 0x0a, 0x09,
	0x44, 0x6f, 0x63, 0x42, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x19, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x49,
	0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x42, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x42,
	0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x57, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x57, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2a,
	0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x70,
	0x70, 0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x70, 0x70, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x2f, 0x0a, 0x0d, 0x44, 0x6f,
	0x63, 0x42, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x44, 0x6f, 0x63, 0x42,
	0x65, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x22, 0x56, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65,
	0x22, 0x1d, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x22,
	0x6e, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x29, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x19, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x10, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x47, 0x6f, 0x6c, 0x64, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x2d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x2a, 0x29, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x53, 0x6c, 0x6f, 0x74, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x69, 0x73,
	0x68, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x10, 0x03, 0x2a, 0x31,
	0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04,
	0x4f, 0x70, 0x65, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x69, 0x64, 0x65, 0x10,
	0x02, 0x32, 0x79, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x52, 0x70, 0x63, 0x12, 0x21, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x09, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x12, 0x0a, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x44,
	0x6f, 0x63, 0x42, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x32, 0x7e, 0x0a, 0x12,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x64, 0x52,
	0x70, 0x63, 0x12, 0x33, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x47, 0x6f, 0x6c, 0x64,
	0x12, 0x11, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x47, 0x6f, 0x6c, 0x64, 0x55, 0x69, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x29, 0x42, 0x0d,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x16, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_gamepb_customer_proto_rawDescOnce sync.Once
	file_pb_gamepb_customer_proto_rawDescData = file_pb_gamepb_customer_proto_rawDesc
)

func file_pb_gamepb_customer_proto_rawDescGZIP() []byte {
	file_pb_gamepb_customer_proto_rawDescOnce.Do(func() {
		file_pb_gamepb_customer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_gamepb_customer_proto_rawDescData)
	})
	return file_pb_gamepb_customer_proto_rawDescData
}

var file_pb_gamepb_customer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_gamepb_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_gamepb_customer_proto_goTypes = []interface{}{
	(GameType)(0),             // 0: GameType
	(GameStatus)(0),           // 1: GameStatus
	(*DocBetLog)(nil),         // 2: DocBetLog
	(*DocBetLogList)(nil),     // 3: DocBetLogList
	(*GetLogReq)(nil),         // 4: GetLogReq
	(*LoginReq)(nil),          // 5: LoginReq
	(*LoginResp)(nil),         // 6: LoginResp
	(*Game)(nil),              // 7: Game
	(*GameListResp)(nil),      // 8: GameListResp
	(*ModifyGoldUidReq)(nil),  // 9: ModifyGoldUidReq
	(*GetBalanceUidReq)(nil),  // 10: GetBalanceUidReq
	(*GetBalanceUidResp)(nil), // 11: GetBalanceUidResp
	(*mongodb.ObjectID)(nil),  // 12: ObjectID
	(*mongodb.TimeStamp)(nil), // 13: TimeStamp
	(*pb.Empty)(nil),          // 14: Empty
}
var file_pb_gamepb_customer_proto_depIdxs = []int32{
	12, // 0: DocBetLog.ID:type_name -> ObjectID
	13, // 1: DocBetLog.InsertTime:type_name -> TimeStamp
	2,  // 2: DocBetLogList.List:type_name -> DocBetLog
	13, // 3: GetLogReq.From:type_name -> TimeStamp
	0,  // 4: Game.Type:type_name -> GameType
	1,  // 5: Game.Status:type_name -> GameStatus
	7,  // 6: GameListResp.List:type_name -> Game
	14, // 7: ForCustomerRpc.GameList:input_type -> Empty
	5,  // 8: ForCustomerRpc.Login:input_type -> LoginReq
	4,  // 9: ForCustomerRpc.GetLog:input_type -> GetLogReq
	9,  // 10: CustomerOfferedRpc.ModifyGold:input_type -> ModifyGoldUidReq
	10, // 11: CustomerOfferedRpc.GetBalance:input_type -> GetBalanceUidReq
	8,  // 12: ForCustomerRpc.GameList:output_type -> GameListResp
	6,  // 13: ForCustomerRpc.Login:output_type -> LoginResp
	3,  // 14: ForCustomerRpc.GetLog:output_type -> DocBetLogList
	11, // 15: CustomerOfferedRpc.ModifyGold:output_type -> GetBalanceUidResp
	11, // 16: CustomerOfferedRpc.GetBalance:output_type -> GetBalanceUidResp
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pb_gamepb_customer_proto_init() }
func file_pb_gamepb_customer_proto_init() {
	if File_pb_gamepb_customer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_gamepb_customer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocBetLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocBetLogList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyGoldUidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceUidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_customer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceUidResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_gamepb_customer_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_gamepb_customer_proto_goTypes,
		DependencyIndexes: file_pb_gamepb_customer_proto_depIdxs,
		EnumInfos:         file_pb_gamepb_customer_proto_enumTypes,
		MessageInfos:      file_pb_gamepb_customer_proto_msgTypes,
	}.Build()
	File_pb_gamepb_customer_proto = out.File
	file_pb_gamepb_customer_proto_rawDesc = nil
	file_pb_gamepb_customer_proto_goTypes = nil
	file_pb_gamepb_customer_proto_depIdxs = nil
}
