// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pb/gamepb/game.proto

package gamepb

import (
	pb "game/pb/_gen/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid     int64  `protobuf:"varint,1,opt,name=Pid,proto3" `         // 玩家ID
	Bet     int64  `protobuf:"varint,2,opt,name=Bet,proto3" `         // 下注
	Win     int64  `protobuf:"varint,3,opt,name=Win,proto3" `         // 输赢（是指产出，不是净输赢）
	GameID  string `protobuf:"bytes,4,opt,name=GameID,proto3" `    // 游戏ID，用于标识是哪个游戏
	RoundID string `protobuf:"bytes,5,opt,name=RoundID,proto3" `  // 对局ID，方便查询
	Comment string `protobuf:"bytes,6,opt,name=Comment,proto3" `  // 注释
	Balance int64  `protobuf:"varint,7,opt,name=Balance,proto3" ` // 余额
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_game_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Log) GetBet() int64 {
	if x != nil {
		return x.Bet
	}
	return 0
}

func (x *Log) GetWin() int64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *Log) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

func (x *Log) GetRoundID() string {
	if x != nil {
		return x.RoundID
	}
	return ""
}

func (x *Log) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Log) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type AddLogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Log `protobuf:"bytes,1,rep,name=List,proto3" `
}

func (x *AddLogReq) Reset() {
	*x = AddLogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLogReq) ProtoMessage() {}

func (x *AddLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLogReq.ProtoReflect.Descriptor instead.
func (*AddLogReq) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_game_proto_rawDescGZIP(), []int{1}
}

func (x *AddLogReq) GetList() []*Log {
	if x != nil {
		return x.List
	}
	return nil
}

type GetBalanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid int64 `protobuf:"varint,1,opt,name=Pid,proto3" `
}

func (x *GetBalanceReq) Reset() {
	*x = GetBalanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceReq) ProtoMessage() {}

func (x *GetBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceReq.ProtoReflect.Descriptor instead.
func (*GetBalanceReq) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_game_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceReq) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type GetBalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Balance int64  `protobuf:"varint,1,opt,name=Balance,proto3" `
	Uid     string `protobuf:"bytes,2,opt,name=Uid,proto3" ` // 玩家外部ID
}

func (x *GetBalanceResp) Reset() {
	*x = GetBalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResp) ProtoMessage() {}

func (x *GetBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResp.ProtoReflect.Descriptor instead.
func (*GetBalanceResp) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResp) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetBalanceResp) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ModifyGoldReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid     int64  `protobuf:"varint,1,opt,name=Pid,proto3" `        // 玩家ID
	Change  int64  `protobuf:"varint,2,opt,name=Change,proto3" `  // 金币变化：>0 加钱， <0 扣钱
	Comment string `protobuf:"bytes,3,opt,name=Comment,proto3" ` // 注释
}

func (x *ModifyGoldReq) Reset() {
	*x = ModifyGoldReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyGoldReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyGoldReq) ProtoMessage() {}

func (x *ModifyGoldReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyGoldReq.ProtoReflect.Descriptor instead.
func (*ModifyGoldReq) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_game_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyGoldReq) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ModifyGoldReq) GetChange() int64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *ModifyGoldReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type TokenReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" `
}

func (x *TokenReq) Reset() {
	*x = TokenReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReq) ProtoMessage() {}

func (x *TokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReq.ProtoReflect.Descriptor instead.
func (*TokenReq) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_game_proto_rawDescGZIP(), []int{5}
}

func (x *TokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WsUrl string `protobuf:"bytes,1,opt,name=WsUrl,proto3" ` // 返回websocket 服务地址
}

func (x *TokenResp) Reset() {
	*x = TokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gamepb_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResp) ProtoMessage() {}

func (x *TokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gamepb_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResp.ProtoReflect.Descriptor instead.
func (*TokenResp) Descriptor() ([]byte, []int) {
	return file_pb_gamepb_game_proto_rawDescGZIP(), []int{6}
}

func (x *TokenResp) GetWsUrl() string {
	if x != nil {
		return x.WsUrl
	}
	return ""
}

var File_pb_gamepb_game_proto protoreflect.FileDescriptor

var file_pb_gamepb_game_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x62, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x42, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x42,
	0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x57, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x57, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x25, 0x0a, 0x09, 0x41, 0x64,
	0x64, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x21, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x50, 0x69, 0x64, 0x22, 0x3c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55,
	0x69, 0x64, 0x22, 0x53, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x47, 0x6f, 0x6c, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x08, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x21, 0x0a, 0x09, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x73, 0x55, 0x72, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x57, 0x73, 0x55, 0x72, 0x6c, 0x32, 0xa9, 0x01, 0x0a,
	0x07, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x70, 0x63, 0x12, 0x2d, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x47, 0x6f, 0x6c, 0x64, 0x12, 0x0e, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x47,
	0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67,
	0x12, 0x0a, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x09, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x25, 0x42, 0x09, 0x47, 0x61, 0x6d, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x16, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62,
	0x2f, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_gamepb_game_proto_rawDescOnce sync.Once
	file_pb_gamepb_game_proto_rawDescData = file_pb_gamepb_game_proto_rawDesc
)

func file_pb_gamepb_game_proto_rawDescGZIP() []byte {
	file_pb_gamepb_game_proto_rawDescOnce.Do(func() {
		file_pb_gamepb_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_gamepb_game_proto_rawDescData)
	})
	return file_pb_gamepb_game_proto_rawDescData
}

var file_pb_gamepb_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_gamepb_game_proto_goTypes = []interface{}{
	(*Log)(nil),            // 0: Log
	(*AddLogReq)(nil),      // 1: AddLogReq
	(*GetBalanceReq)(nil),  // 2: GetBalanceReq
	(*GetBalanceResp)(nil), // 3: GetBalanceResp
	(*ModifyGoldReq)(nil),  // 4: ModifyGoldReq
	(*TokenReq)(nil),       // 5: TokenReq
	(*TokenResp)(nil),      // 6: TokenResp
	(*pb.Empty)(nil),       // 7: Empty
}
var file_pb_gamepb_game_proto_depIdxs = []int32{
	0, // 0: AddLogReq.List:type_name -> Log
	4, // 1: GameRpc.ModifyGold:input_type -> ModifyGoldReq
	2, // 2: GameRpc.GetBalance:input_type -> GetBalanceReq
	1, // 3: GameRpc.AddLog:input_type -> AddLogReq
	5, // 4: GameRpc.ValidateToken:input_type -> TokenReq
	3, // 5: GameRpc.ModifyGold:output_type -> GetBalanceResp
	3, // 6: GameRpc.GetBalance:output_type -> GetBalanceResp
	7, // 7: GameRpc.AddLog:output_type -> Empty
	7, // 8: GameRpc.ValidateToken:output_type -> Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_gamepb_game_proto_init() }
func file_pb_gamepb_game_proto_init() {
	if File_pb_gamepb_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_gamepb_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyGoldReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gamepb_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_gamepb_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_gamepb_game_proto_goTypes,
		DependencyIndexes: file_pb_gamepb_game_proto_depIdxs,
		MessageInfos:      file_pb_gamepb_game_proto_msgTypes,
	}.Build()
	File_pb_gamepb_game_proto = out.File
	file_pb_gamepb_game_proto_rawDesc = nil
	file_pb_gamepb_game_proto_goTypes = nil
	file_pb_gamepb_game_proto_depIdxs = nil
}
