package main

import (
	"github.com/samber/lo"
	"os"
	"serve/comm/db"
	"serve/comm/lazy"
	"serve/comm/mq"
	"serve/comm/mux"
	"serve/comm/redisx"
	"serve/comm/slotsmongo"
	"serve/servicejdb/jdb_14063/internal"
	"serve/servicejdb/jdb_14063/internal/gendata"
	_ "serve/servicejdb/jdb_14063/internal/rpc"
	"serve/servicejdb/jdbcomm"
)

func main() {
	// 解码
	/*	decoded2, err := base64.StdEncoding.DecodeString("gA9jEgADAAFwEgACAAFwEgACAARjb2RlCAAMaW5pdFJlc3BvbnNlAAZlbnRpdHkKAAAPEnsibWF4QmV0Ijo5MjIzMzcyMDM2ODU0Nzc1ODA3LCJkZWZhdWx0V2F5c0JldElkeCI6LTEsInNpbmdsZUJldENvbWJpbmF0aW9ucyI6eyIxMF8xMF8xX05vRXh0cmFCZXQiOjMwLCIxMF8xXzFfTm9FeHRyYUJldCI6MywiMTBfMjBfMV9Ob0V4dHJhQmV0Ijo2MCwiMTBfMl8xX05vRXh0cmFCZXQiOjYsIjEwXzVfMV9Ob0V4dHJhQmV0IjoxNX0sIm1pbkJldCI6MCwiZ2FtYmxlVGltZXMiOjAsImRlZmF1bHRMaW5lQmV0SWR4IjowLCJkZWZhdWx0Q29ubmVjdEJldElkeCI6LTEsImRlZmF1bHRRdWFudGl0eUJldElkeCI6LTEsImdhbWVGZWF0dXJlQ291bnQiOjMsImV4ZWN1dGVTZXR0aW5nIjp7InNldHRpbmdJZCI6InYzXzE0MDYzXzA1XzAwXzAwMSIsImJldFNwZWNTZXR0aW5nIjp7InBheW1lbnRUeXBlIjoiUFRfMDI2IiwiZXh0cmFCZXRUeXBlTGlzdCI6WyJOb0V4dHJhQmV0Il0sImJldFNwZWNpZmljYXRpb24iOnsibGluZUJldExpc3QiOlsxLDIsNSwxMCwyMF0sImJldExpbmVMaXN0IjpbMV0sImJldFR5cGUiOiJMaW5lR2FtZSJ9fSwiZ2FtZVN0YXRlU2V0dGluZyI6W3siZ2FtZVN0YXRlVHlwZSI6IkdTXzEyOSIsImZyYW1lU2V0dGluZyI6eyJzY3JlZW5Db2x1bW4iOjQsInNjcmVlblJvdyI6MSwid2hlZWxVc2VQYXR0ZXJuIjoiRGVwZW5kZW50In0sInRhYmxlU2V0dGluZyI6eyJ0YWJsZUNvdW50IjoxLCJ0YWJsZUhpdFByb2JhYmlsaXR5IjpbMS4wXSwid2hlZWxEYXRhIjpbW3sid2hlZWxMZW5ndGgiOjE0LCJub1dpbkluZGV4IjpbMl0sIndoZWVsRGF0YSI6WzExLDEwLDgsNywxMCw5LDgsMTEsOCwxMCw5LDExLDgsN119LHsid2hlZWxMZW5ndGgiOjI0LCJub1dpbkluZGV4IjpbNV0sIndoZWVsRGF0YSI6WzgsNywxMCwxMSw3LDksNywxMCw5LDExLDgsMTEsOSwxMSw5LDgsMTEsMTAsOCw5LDExLDksMTAsMTFdfSx7IndoZWVsTGVuZ3RoIjoxNSwibm9XaW5JbmRleCI6WzJdLCJ3aGVlbERhdGEiOls4LDExLDksMTAsOCwxMSw5LDEwLDksNywxMSw3LDksOCwxMF19LHsid2hlZWxMZW5ndGgiOjI2LCJub1dpbkluZGV4IjpbMTFdLCJ3aGVlbERhdGEiOls1LDAsMyw1LDAsMiw1LDAsMywyLDQsMSwwLDMsNSwwLDMsNSwwLDQsMCwzLDAsMiwwLDJdfV1dfSwic3ltYm9sU2V0dGluZyI6eyJzeW1ib2xDb3VudCI6MTIsInN5bWJvbEF0dHJpYnV0ZSI6WyJCb251c0dhbWVfMDEiLCJCb251c0dhbWVfMDIiLCJCb251c0dhbWVfMDMiLCJCb251c0dhbWVfMDQiLCJCb251c0dhbWVfMDUiLCJCb251c0dhbWVfMDYiLCJGcmVlR2FtZV8wMSIsIk0xIiwiTTIiLCJNMyIsIk00IiwiTTUiXSwicGF5VGFibGUiOltbMCwwLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF0sWzAsMCwwLDBdLFswLDAsMCwwXSxbMCwwLDAsMF0sWzAsMCwxMDAwLDBdLFswLDAsMjAwLDBdLFswLDAsMTAwLDBdLFswLDAsNDAsMF0sWzAsMCwyMCwwXV0sIm1peEdyb3VwQ291bnQiOjIwLCJtaXhHcm91cFNldHRpbmciOlt7ImNvdW50IjoyLCJzeW1ib2wiOls3LDhdLCJwYXlUYWJsZSI6WzAsMCw0MCwwXX0seyJjb3VudCI6Miwic3ltYm9sIjpbNyw5XSwicGF5VGFibGUiOlswLDAsNDAsMF19LHsiY291bnQiOjIsInN5bWJvbCI6WzgsOV0sInBheVRhYmxlIjpbMCwwLDQwLDBdfSx7ImNvdW50IjozLCJzeW1ib2wiOls3LDgsOV0sInBheVRhYmxlIjpbMCwwLDQwLDBdfSx7ImNvdW50IjoyLCJzeW1ib2wiOlsxMCwxMV0sInBheVRhYmxlIjpbMCwwLDEwLDBdfSx7ImNvdW50IjoyLCJzeW1ib2wiOls3LDEwXSwicGF5VGFibGUiOlswLDAsNCwwXX0seyJjb3VudCI6Miwic3ltYm9sIjpbNywxMV0sInBheVRhYmxlIjpbMCwwLDQsMF19LHsiY291bnQiOjIsInN5bWJvbCI6WzgsMTBdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfSx7ImNvdW50IjoyLCJzeW1ib2wiOls4LDExXSwicGF5VGFibGUiOlswLDAsNCwwXX0seyJjb3VudCI6Miwic3ltYm9sIjpbOSwxMF0sInBheVRhYmxlIjpbMCwwLDQsMF19LHsiY291bnQiOjIsInN5bWJvbCI6WzksMTFdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfSx7ImNvdW50IjozLCJzeW1ib2wiOls3LDgsMTBdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfSx7ImNvdW50IjozLCJzeW1ib2wiOls3LDgsMTFdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfSx7ImNvdW50IjozLCJzeW1ib2wiOls3LDksMTBdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfSx7ImNvdW50IjozLCJzeW1ib2wiOls3LDksMTFdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfSx7ImNvdW50IjozLCJzeW1ib2wiOls4LDksMTBdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfSx7ImNvdW50IjozLCJzeW1ib2wiOls4LDksMTFdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfSx7ImNvdW50IjozLCJzeW1ib2wiOls3LDEwLDExXSwicGF5VGFibGUiOlswLDAsNCwwXX0seyJjb3VudCI6Mywic3ltYm9sIjpbOCwxMCwxMV0sInBheVRhYmxlIjpbMCwwLDQsMF19LHsiY291bnQiOjMsInN5bWJvbCI6WzksMTAsMTFdLCJwYXlUYWJsZSI6WzAsMCw0LDBdfV19LCJsaW5lU2V0dGluZyI6eyJtYXhCZXRMaW5lIjoxLCJsaW5lVGFibGUiOltbMCwwLDAsMF1dfSwiZ2FtZUhpdFBhdHRlcm5TZXR0aW5nIjp7ImdhbWVIaXRQYXR0ZXJuIjoiTGluZUdhbWVfTGVmdFRvUmlnaHQiLCJtYXhFbGltaW5hdGVUaW1lcyI6MH0sInNwZWNpYWxGZWF0dXJlU2V0dGluZyI6eyJzcGVjaWFsRmVhdHVyZUNvdW50IjowLCJzcGVjaWFsSGl0SW5mbyI6W119LCJwcm9ncmVzc1NldHRpbmciOnsidHJpZ2dlckxpbWl0VHlwZSI6Ik5vTGltaXQiLCJzdGVwU2V0dGluZyI6eyJkZWZhdWx0U3RlcCI6MSwiYWRkU3RlcCI6MCwibWF4U3RlcCI6MX0sInN0YWdlU2V0dGluZyI6eyJkZWZhdWx0U3RhZ2UiOjEsImFkZFN0YWdlIjowLCJtYXhTdGFnZSI6MX0sInJvdW5kU2V0dGluZyI6eyJkZWZhdWx0Um91bmQiOjEsImFkZFJvdW5kIjowLCJtYXhSb3VuZCI6MX19LCJkaXNwbGF5U2V0dGluZyI6eyJyZWFkeUhhbmRTZXR0aW5nIjp7InJlYWR5SGFuZExpbWl0VHlwZSI6Ik5vUmVhZHlIYW5kTGltaXQiLCJyZWFkeUhhbmRDb3VudCI6MCwicmVhZHlIYW5kVHlwZSI6W119fSwiZXh0ZW5kU2V0dGluZyI6eyJib251c0RhbXBTaXplIjozLCJib251c1R5cGUiOlsiUmVzcGlucyIsIk11bHRpcGxlIiwiTXVsdGlwbGUiLCJNdWx0aXBsZSIsIkV4dHJhIiwiRXh0cmEiLCIiLCIiLCIiLCIiLCIiLCIiXSwiYm9udXNFeHRyYSI6WzAsMCwwLDAsMTAwLDEwLDAsMCwwLDAsMCwwXSwiYm9udXNNdWx0aXBsZSI6WzEsMTAsNSwyLDEsMSwxLDEsMSwxLDEsMV0sInJlc3BpblJvdW5kV2VpZ2h0IjpbMzAsMjYsMjEsMTIsMTFdfX1dLCJkb3VibGVHYW1lU2V0dGluZyI6eyJkb3VibGVSb3VuZFVwcGVyTGltaXQiOjUsImRvdWJsZUJldFVwcGVyTGltaXQiOjEwMDAwMDAwMDAsInJ0cCI6MC45NiwidGllUmF0ZSI6MC4xfSwiYm9hcmREaXNwbGF5U2V0dGluZyI6eyJ3aW5SYW5rU2V0dGluZyI6eyJCaWdXaW4iOjkwMDAwLCJNZWdhV2luIjo5OTAwMCwiVWx0cmFXaW4iOjk5OTAwfX0sImdhbWVGbG93U2V0dGluZyI6eyJjb25kaXRpb25UYWJsZVdpdGhvdXRCb2FyZEVuZCI6W1siQ0RfRmFsc2UiLCJDRF9UcnVlIl0sWyJDRF9GYWxzZSIsIkNEX0ZhbHNlIl1dfX0sImRlbm9tcyI6WzEwXSwiZGVmYXVsdERlbm9tSWR4IjowLCJkZWZhdWx0QmV0TGluZUlkeCI6MCwiYmV0Q29tYmluYXRpb25zIjp7IjEwXzFfTm9FeHRyYUJldCI6MzAsIjFfMV9Ob0V4dHJhQmV0IjozLCIyMF8xX05vRXh0cmFCZXQiOjYwLCIyXzFfTm9FeHRyYUJldCI6NiwiNV8xX05vRXh0cmFCZXQiOjE1fSwiZ2FtYmxlTGltaXQiOjAsImJ1eUZlYXR1cmVMaW1pdCI6MjE0NzQ4MzY0NywiYnV5RmVhdHVyZSI6dHJ1ZSwiZGVmYXVsdFdheXNCZXRDb2x1bW5JZHgiOi0xfQABYwgAD2g1LmluaXRSZXNwb25zZQABYQMADQABYwIB")
		if err != nil {
			panic(err)
		}
		fmt.Printf("%x\n", decoded2)
		so, err := jdbcomm.NewFromBinaryData(decoded2)
		if err != nil {
			panic(err)
		}
		b2, err := so.ToBinary()
		fmt.Printf("%x\n", b2)*/

	lazy.Init(internal.GameID)

	mgoaddr := lo.Must(lazy.RouteFile.Get("mongo"))
	db.DialToMongo(mgoaddr, lazy.ServiceName)
	slotsmongo.RestoreSpinData()
	if len(os.Args) > 1 && os.Args[1] == "cache" {
		slotsmongo.InitData("simulate", "")
		lo.Must0(gendata.LoadCombineData())
		return
	}

	// 先准备好数据, 再监听消息
	lo.Must0(gendata.LoadCombineData())
	addr := lo.Must(lazy.RouteFile.Get("proxy.mq"))
	mqconn := lo.Must(mq.ConnectServerMust(addr))
	jdbcomm.RegistRpcToMQ(mqconn)

	mux.RegistRpcToMQ(mqconn)

	redisAddr := lo.Must(lazy.RouteFile.Get("redis"))
	redisx.RegSubscribe(lazy.ServiceName, redisAddr)
	lazy.Serve()
}
