// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: serve/service_fish/domain/auth/proto/auth.proto

package auth_proto

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	proto1 "serve/fish_comm/common/proto"
	proto2 "serve/service_fish/models/proto"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PLAYER_TYPE int32

const (
	PLAYER_TYPE_GAME PLAYER_TYPE = 0
	PLAYER_TYPE_BOT  PLAYER_TYPE = 1
)

var PLAYER_TYPE_name = map[int32]string{
	0: "GAME",
	1: "BOT",
}

var PLAYER_TYPE_value = map[string]int32{
	"GAME": 0,
	"BOT":  1,
}

func (x PLAYER_TYPE) String() string {
	return proto.EnumName(PLAYER_TYPE_name, int32(x))
}

func (PLAYER_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_844c4cd0d68e3439, []int{0}
}

type LoginCall struct {
	Msgid     proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.proto.EMSGID" json:"msgid,omitempty"`
	MemberId  string        `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Password  string        `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	MachineId string        `protobuf:"bytes,4,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	Token     string        `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *LoginCall) Reset()         { *m = LoginCall{} }
func (m *LoginCall) String() string { return proto.CompactTextString(m) }
func (*LoginCall) ProtoMessage()    {}
func (*LoginCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c4cd0d68e3439, []int{0}
}
func (m *LoginCall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginCall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginCall.Merge(m, src)
}
func (m *LoginCall) XXX_Size() int {
	return m.Size()
}
func (m *LoginCall) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginCall.DiscardUnknown(m)
}

var xxx_messageInfo_LoginCall proto.InternalMessageInfo

func (m *LoginCall) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *LoginCall) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *LoginCall) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginCall) GetMachineId() string {
	if m != nil {
		return m.MachineId
	}
	return ""
}

func (m *LoginCall) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginRecall struct {
	Msgid      proto1.EMSGID      `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.proto.EMSGID" json:"msgid,omitempty"`
	StatusCode proto1.Status_Code `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3,enum=common.proto.Status_Code" json:"status_code,omitempty"`
	Token      string             `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *LoginRecall) Reset()         { *m = LoginRecall{} }
func (m *LoginRecall) String() string { return proto.CompactTextString(m) }
func (*LoginRecall) ProtoMessage()    {}
func (*LoginRecall) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c4cd0d68e3439, []int{1}
}
func (m *LoginRecall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginRecall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginRecall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginRecall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRecall.Merge(m, src)
}
func (m *LoginRecall) XXX_Size() int {
	return m.Size()
}
func (m *LoginRecall) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRecall.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRecall proto.InternalMessageInfo

func (m *LoginRecall) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *LoginRecall) GetStatusCode() proto1.Status_Code {
	if m != nil {
		return m.StatusCode
	}
	return proto1.Status_kSuccess
}

func (m *LoginRecall) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfoAsk struct {
	Msgid  proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.proto.EMSGID" json:"msgid,omitempty"`
	Player []*UserInfo   `protobuf:"bytes,2,rep,name=player,proto3" json:"player,omitempty"`
}

func (m *UserInfoAsk) Reset()         { *m = UserInfoAsk{} }
func (m *UserInfoAsk) String() string { return proto.CompactTextString(m) }
func (*UserInfoAsk) ProtoMessage()    {}
func (*UserInfoAsk) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c4cd0d68e3439, []int{2}
}
func (m *UserInfoAsk) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserInfoAsk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserInfoAsk.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserInfoAsk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoAsk.Merge(m, src)
}
func (m *UserInfoAsk) XXX_Size() int {
	return m.Size()
}
func (m *UserInfoAsk) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoAsk.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoAsk proto.InternalMessageInfo

func (m *UserInfoAsk) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *UserInfoAsk) GetPlayer() []*UserInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

type UserInfo struct {
	PlayerId    string              `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName  string              `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PlayerCent  uint64              `protobuf:"varint,3,opt,name=player_cent,json=playerCent,proto3" json:"player_cent,omitempty"`
	SeatId      uint32              `protobuf:"varint,4,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	BetRateLine *proto2.BetRateLine `protobuf:"bytes,5,opt,name=bet_rate_line,json=betRateLine,proto3" json:"bet_rate_line,omitempty"`
	AvatarId    string              `protobuf:"bytes,6,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	Visible     *UserInfo_Column    `protobuf:"bytes,7,opt,name=visible,proto3" json:"visible,omitempty"`
	PlayerType  PLAYER_TYPE         `protobuf:"varint,8,opt,name=player_type,json=playerType,proto3,enum=auth.proto.PLAYER_TYPE" json:"player_type,omitempty"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c4cd0d68e3439, []int{3}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return m.Size()
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetPlayerId() string {
	if m != nil {
		return m.PlayerId
	}
	return ""
}

func (m *UserInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *UserInfo) GetPlayerCent() uint64 {
	if m != nil {
		return m.PlayerCent
	}
	return 0
}

func (m *UserInfo) GetSeatId() uint32 {
	if m != nil {
		return m.SeatId
	}
	return 0
}

func (m *UserInfo) GetBetRateLine() *proto2.BetRateLine {
	if m != nil {
		return m.BetRateLine
	}
	return nil
}

func (m *UserInfo) GetAvatarId() string {
	if m != nil {
		return m.AvatarId
	}
	return ""
}

func (m *UserInfo) GetVisible() *UserInfo_Column {
	if m != nil {
		return m.Visible
	}
	return nil
}

func (m *UserInfo) GetPlayerType() PLAYER_TYPE {
	if m != nil {
		return m.PlayerType
	}
	return PLAYER_TYPE_GAME
}

type UserInfo_Column struct {
	Id      bool `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    bool `protobuf:"varint,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance bool `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Avatar  bool `protobuf:"varint,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (m *UserInfo_Column) Reset()         { *m = UserInfo_Column{} }
func (m *UserInfo_Column) String() string { return proto.CompactTextString(m) }
func (*UserInfo_Column) ProtoMessage()    {}
func (*UserInfo_Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c4cd0d68e3439, []int{3, 0}
}
func (m *UserInfo_Column) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserInfo_Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserInfo_Column.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserInfo_Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo_Column.Merge(m, src)
}
func (m *UserInfo_Column) XXX_Size() int {
	return m.Size()
}
func (m *UserInfo_Column) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo_Column proto.InternalMessageInfo

func (m *UserInfo_Column) GetId() bool {
	if m != nil {
		return m.Id
	}
	return false
}

func (m *UserInfo_Column) GetName() bool {
	if m != nil {
		return m.Name
	}
	return false
}

func (m *UserInfo_Column) GetBalance() bool {
	if m != nil {
		return m.Balance
	}
	return false
}

func (m *UserInfo_Column) GetAvatar() bool {
	if m != nil {
		return m.Avatar
	}
	return false
}

type BroadcastPlayerIn struct {
	Msgid    proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	Player   []*UserInfo   `protobuf:"bytes,3,rep,name=player,proto3" json:"player,omitempty"`
}

func (m *BroadcastPlayerIn) Reset()         { *m = BroadcastPlayerIn{} }
func (m *BroadcastPlayerIn) String() string { return proto.CompactTextString(m) }
func (*BroadcastPlayerIn) ProtoMessage()    {}
func (*BroadcastPlayerIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c4cd0d68e3439, []int{4}
}
func (m *BroadcastPlayerIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BroadcastPlayerIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BroadcastPlayerIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BroadcastPlayerIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastPlayerIn.Merge(m, src)
}
func (m *BroadcastPlayerIn) XXX_Size() int {
	return m.Size()
}
func (m *BroadcastPlayerIn) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastPlayerIn.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastPlayerIn proto.InternalMessageInfo

func (m *BroadcastPlayerIn) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *BroadcastPlayerIn) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *BroadcastPlayerIn) GetPlayer() []*UserInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

type BroadcastPlayerOut struct {
	Msgid    proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	Player   *UserInfo     `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
}

func (m *BroadcastPlayerOut) Reset()         { *m = BroadcastPlayerOut{} }
func (m *BroadcastPlayerOut) String() string { return proto.CompactTextString(m) }
func (*BroadcastPlayerOut) ProtoMessage()    {}
func (*BroadcastPlayerOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_844c4cd0d68e3439, []int{5}
}
func (m *BroadcastPlayerOut) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BroadcastPlayerOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BroadcastPlayerOut.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BroadcastPlayerOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastPlayerOut.Merge(m, src)
}
func (m *BroadcastPlayerOut) XXX_Size() int {
	return m.Size()
}
func (m *BroadcastPlayerOut) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastPlayerOut.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastPlayerOut proto.InternalMessageInfo

func (m *BroadcastPlayerOut) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *BroadcastPlayerOut) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *BroadcastPlayerOut) GetPlayer() *UserInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

func init() {
	proto.RegisterEnum("auth.proto.PLAYER_TYPE", PLAYER_TYPE_name, PLAYER_TYPE_value)
	proto.RegisterType((*LoginCall)(nil), "auth.proto.LoginCall")
	proto.RegisterType((*LoginRecall)(nil), "auth.proto.LoginRecall")
	proto.RegisterType((*UserInfoAsk)(nil), "auth.proto.UserInfoAsk")
	proto.RegisterType((*UserInfo)(nil), "auth.proto.UserInfo")
	proto.RegisterType((*UserInfo_Column)(nil), "auth.proto.UserInfo.Column")
	proto.RegisterType((*BroadcastPlayerIn)(nil), "auth.proto.BroadcastPlayerIn")
	proto.RegisterType((*BroadcastPlayerOut)(nil), "auth.proto.BroadcastPlayerOut")
}

func init() {
	proto.RegisterFile("serve/service_fish/domain/auth/proto/auth.proto", fileDescriptor_844c4cd0d68e3439)
}

var fileDescriptor_844c4cd0d68e3439 = []byte{
	// 660 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x4e, 0xdb, 0x40,
	0x10, 0x8d, 0x93, 0x90, 0x38, 0x63, 0x81, 0xe8, 0x0a, 0x15, 0x17, 0xd4, 0x34, 0xca, 0x09, 0xa1,
	0xe2, 0x94, 0x54, 0x95, 0xaa, 0x9e, 0x4a, 0xd2, 0x08, 0x59, 0x82, 0x82, 0x0c, 0x1c, 0xb8, 0xd4,
	0xda, 0x64, 0x87, 0x60, 0x61, 0xef, 0x46, 0xf6, 0x3a, 0x15, 0xbf, 0x50, 0x2e, 0xfd, 0x89, 0xfe,
	0x41, 0x3f, 0xa2, 0x47, 0x8e, 0x3d, 0x56, 0xf0, 0x23, 0x95, 0x77, 0x6d, 0x12, 0xda, 0x4a, 0x2d,
	0x87, 0xde, 0x66, 0xde, 0xbe, 0x7d, 0x7e, 0xf3, 0x66, 0x0d, 0x5b, 0x67, 0x41, 0x72, 0xbe, 0x35,
	0xa6, 0x11, 0x6e, 0x25, 0x18, 0x4f, 0x31, 0xee, 0x30, 0x11, 0xd1, 0x80, 0x77, 0x68, 0x2a, 0xcf,
	0x3b, 0x93, 0x58, 0x48, 0xa1, 0x4a, 0x47, 0x95, 0x04, 0x66, 0xf5, 0x9a, 0x3b, 0xb9, 0x18, 0x77,
	0x22, 0xc1, 0x3a, 0xe3, 0x40, 0x86, 0x74, 0xe8, 0x04, 0x93, 0x90, 0x5e, 0x26, 0x92, 0xc6, 0x0e,
	0x47, 0xd9, 0x99, 0x97, 0x1c, 0x89, 0x28, 0x12, 0xfc, 0xed, 0xf4, 0x85, 0xb3, 0xed, 0x6c, 0xe7,
	0xa2, 0x1a, 0xcb, 0xa5, 0x3a, 0xbf, 0xb9, 0x88, 0x04, 0xc3, 0x30, 0xb9, 0xc7, 0xf5, 0x33, 0x92,
	0xbe, 0xd0, 0xfe, 0x62, 0x40, 0x63, 0x4f, 0x8c, 0x03, 0xde, 0xa7, 0x61, 0x48, 0x36, 0x61, 0x21,
	0x4a, 0xc6, 0x01, 0xb3, 0x8d, 0x96, 0xb1, 0xb1, 0xd4, 0x5d, 0x71, 0xe6, 0xc5, 0x9d, 0xc1, 0xfe,
	0xd1, 0xae, 0xfb, 0xce, 0xd3, 0x14, 0xb2, 0x0e, 0x8d, 0x08, 0xa3, 0x21, 0xc6, 0x7e, 0xc0, 0xec,
	0x72, 0xcb, 0xd8, 0x68, 0x78, 0xa6, 0x06, 0x5c, 0x46, 0xd6, 0xc0, 0x9c, 0xd0, 0x24, 0xf9, 0x28,
	0x62, 0x66, 0x57, 0xf4, 0x59, 0xd1, 0x93, 0xa7, 0x00, 0x11, 0x1d, 0x9d, 0x07, 0x1c, 0xb3, 0x9b,
	0x55, 0x75, 0xda, 0xc8, 0x11, 0x97, 0x91, 0x15, 0x58, 0x90, 0xe2, 0x02, 0xb9, 0xbd, 0xa0, 0x4e,
	0x74, 0xd3, 0xbe, 0x32, 0xc0, 0x52, 0x3e, 0x3d, 0x1c, 0x3d, 0xd4, 0xe9, 0x1b, 0xb0, 0x12, 0x49,
	0x65, 0x9a, 0xf8, 0x23, 0xc1, 0x50, 0x79, 0x5d, 0xea, 0x3e, 0xb9, 0x7f, 0xe3, 0x48, 0x11, 0x9c,
	0xbe, 0x60, 0xe8, 0x81, 0x66, 0x67, 0xf5, 0xcc, 0x4d, 0x65, 0xde, 0xcd, 0x18, 0xac, 0x93, 0x04,
	0x63, 0x97, 0x9f, 0x89, 0x9d, 0xe4, 0xe2, 0x41, 0x66, 0x9e, 0x43, 0x2d, 0x5b, 0x2f, 0xc6, 0x76,
	0xb9, 0x55, 0xd9, 0xb0, 0xba, 0x2b, 0xce, 0xec, 0x25, 0x38, 0x85, 0xa8, 0x97, 0x73, 0xda, 0x5f,
	0x2b, 0x60, 0x16, 0x60, 0x96, 0xb8, 0x86, 0xfd, 0xfc, 0x53, 0x59, 0xaa, 0x0a, 0x70, 0x19, 0x79,
	0x06, 0x56, 0x7e, 0xc8, 0x69, 0x84, 0xf9, 0x42, 0x40, 0x43, 0xef, 0x69, 0x84, 0x73, 0x84, 0x11,
	0x72, 0xa9, 0xe6, 0xa9, 0x16, 0x84, 0x3e, 0x72, 0x49, 0x56, 0xa1, 0x9e, 0x20, 0x95, 0xc5, 0x52,
	0x16, 0xbd, 0x5a, 0xd6, 0xba, 0x8c, 0xf4, 0x60, 0x71, 0x88, 0xd2, 0x8f, 0xa9, 0x44, 0x3f, 0x0c,
	0x38, 0xaa, 0xcd, 0x58, 0xdd, 0x66, 0x31, 0xe6, 0xec, 0x39, 0x39, 0x3d, 0x94, 0x1e, 0x95, 0xb8,
	0x17, 0x70, 0xf4, 0xac, 0xe1, 0xac, 0xc9, 0xbc, 0xd3, 0x29, 0x95, 0x54, 0x79, 0xaf, 0x69, 0xef,
	0x1a, 0x70, 0x19, 0x79, 0x05, 0xf5, 0x69, 0x90, 0x04, 0xc3, 0x10, 0xed, 0xba, 0x92, 0x5e, 0xff,
	0x53, 0x28, 0x4e, 0x5f, 0x84, 0x69, 0xc4, 0xbd, 0x82, 0x4b, 0x5e, 0xdf, 0x4d, 0x24, 0x2f, 0x27,
	0x68, 0x9b, 0x2a, 0xfc, 0xd5, 0xf9, 0xab, 0x87, 0x7b, 0x3b, 0xa7, 0x03, 0xcf, 0x3f, 0x3e, 0x3d,
	0x1c, 0x14, 0xa3, 0x1e, 0x5f, 0x4e, 0x70, 0xed, 0x03, 0xd4, 0xb4, 0x18, 0x59, 0x82, 0x72, 0x1e,
	0xa6, 0xe9, 0x95, 0x03, 0x46, 0x08, 0x54, 0xef, 0xf2, 0x33, 0x3d, 0x55, 0x13, 0x1b, 0xea, 0x43,
	0x1a, 0x52, 0x3e, 0x42, 0x95, 0x9a, 0xe9, 0x15, 0x2d, 0x79, 0x0c, 0x35, 0x3d, 0x84, 0x4a, 0xcc,
	0xf4, 0xf2, 0xae, 0xfd, 0xc9, 0x80, 0x47, 0xbd, 0x58, 0x50, 0x36, 0xa2, 0x89, 0x3c, 0xd4, 0x2b,
	0xe2, 0x0f, 0xfd, 0xbb, 0x62, 0x21, 0x22, 0x3f, 0x4d, 0x67, 0x7f, 0x57, 0x06, 0x9c, 0xa4, 0xf7,
	0xde, 0x50, 0xe5, 0x1f, 0xde, 0xd0, 0x95, 0x01, 0xe4, 0x17, 0x33, 0x07, 0xa9, 0xfc, 0x3f, 0x6e,
	0x8c, 0xbf, 0xb9, 0xd9, 0x6c, 0x81, 0x35, 0xb7, 0x15, 0x62, 0x42, 0x75, 0x77, 0x67, 0x7f, 0xb0,
	0x5c, 0x22, 0x75, 0xa8, 0xf4, 0x0e, 0x8e, 0x97, 0x8d, 0x9e, 0xfd, 0xed, 0xa6, 0x69, 0x5c, 0xdf,
	0x34, 0x8d, 0x1f, 0x37, 0x4d, 0xe3, 0xf3, 0x6d, 0xb3, 0x74, 0x7d, 0xdb, 0x2c, 0x7d, 0xbf, 0x6d,
	0x96, 0x86, 0x35, 0xa5, 0xf9, 0xf2, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xe4, 0xf5, 0xda,
	0x6c, 0x05, 0x00, 0x00,
}

func (m *LoginCall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MachineId) > 0 {
		i -= len(m.MachineId)
		copy(dAtA[i:], m.MachineId)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.MachineId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Password) > 0 {
		i -= len(m.Password)
		copy(dAtA[i:], m.Password)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.Password)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MemberId) > 0 {
		i -= len(m.MemberId)
		copy(dAtA[i:], m.MemberId)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.MemberId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LoginRecall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginRecall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginRecall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Token) > 0 {
		i -= len(m.Token)
		copy(dAtA[i:], m.Token)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.Token)))
		i--
		dAtA[i] = 0x1a
	}
	if m.StatusCode != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.StatusCode))
		i--
		dAtA[i] = 0x10
	}
	if m.Msgid != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UserInfoAsk) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserInfoAsk) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserInfoAsk) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Player) > 0 {
		for iNdEx := len(m.Player) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Player[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuth(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Msgid != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *UserInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PlayerType != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.PlayerType))
		i--
		dAtA[i] = 0x40
	}
	if m.Visible != nil {
		{
			size, err := m.Visible.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuth(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.AvatarId) > 0 {
		i -= len(m.AvatarId)
		copy(dAtA[i:], m.AvatarId)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.AvatarId)))
		i--
		dAtA[i] = 0x32
	}
	if m.BetRateLine != nil {
		{
			size, err := m.BetRateLine.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuth(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.SeatId != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.SeatId))
		i--
		dAtA[i] = 0x20
	}
	if m.PlayerCent != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.PlayerCent))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PlayerName) > 0 {
		i -= len(m.PlayerName)
		copy(dAtA[i:], m.PlayerName)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.PlayerName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PlayerId) > 0 {
		i -= len(m.PlayerId)
		copy(dAtA[i:], m.PlayerId)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.PlayerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UserInfo_Column) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserInfo_Column) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserInfo_Column) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Avatar {
		i--
		if m.Avatar {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Balance {
		i--
		if m.Balance {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Name {
		i--
		if m.Name {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Id {
		i--
		if m.Id {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BroadcastPlayerIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BroadcastPlayerIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BroadcastPlayerIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Player) > 0 {
		for iNdEx := len(m.Player) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Player[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAuth(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BroadcastPlayerOut) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BroadcastPlayerOut) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BroadcastPlayerOut) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Player != nil {
		{
			size, err := m.Player.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuth(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintAuth(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintAuth(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuth(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuth(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LoginCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovAuth(uint64(m.Msgid))
	}
	l = len(m.MemberId)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	l = len(m.MachineId)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	return n
}

func (m *LoginRecall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovAuth(uint64(m.Msgid))
	}
	if m.StatusCode != 0 {
		n += 1 + sovAuth(uint64(m.StatusCode))
	}
	l = len(m.Token)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	return n
}

func (m *UserInfoAsk) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovAuth(uint64(m.Msgid))
	}
	if len(m.Player) > 0 {
		for _, e := range m.Player {
			l = e.Size()
			n += 1 + l + sovAuth(uint64(l))
		}
	}
	return n
}

func (m *UserInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PlayerId)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	l = len(m.PlayerName)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	if m.PlayerCent != 0 {
		n += 1 + sovAuth(uint64(m.PlayerCent))
	}
	if m.SeatId != 0 {
		n += 1 + sovAuth(uint64(m.SeatId))
	}
	if m.BetRateLine != nil {
		l = m.BetRateLine.Size()
		n += 1 + l + sovAuth(uint64(l))
	}
	l = len(m.AvatarId)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	if m.Visible != nil {
		l = m.Visible.Size()
		n += 1 + l + sovAuth(uint64(l))
	}
	if m.PlayerType != 0 {
		n += 1 + sovAuth(uint64(m.PlayerType))
	}
	return n
}

func (m *UserInfo_Column) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id {
		n += 2
	}
	if m.Name {
		n += 2
	}
	if m.Balance {
		n += 2
	}
	if m.Avatar {
		n += 2
	}
	return n
}

func (m *BroadcastPlayerIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovAuth(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	if len(m.Player) > 0 {
		for _, e := range m.Player {
			l = e.Size()
			n += 1 + l + sovAuth(uint64(l))
		}
	}
	return n
}

func (m *BroadcastPlayerOut) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovAuth(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovAuth(uint64(l))
	}
	if m.Player != nil {
		l = m.Player.Size()
		n += 1 + l + sovAuth(uint64(l))
	}
	return n
}

func sovAuth(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuth(x uint64) (n int) {
	return sovAuth(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LoginCall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginCall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginCall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MachineId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MachineId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginRecall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginRecall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginRecall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusCode", wireType)
			}
			m.StatusCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StatusCode |= proto1.Status_Code(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Token = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserInfoAsk) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserInfoAsk: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserInfoAsk: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Player = append(m.Player, &UserInfo{})
			if err := m.Player[len(m.Player)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlayerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlayerName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerCent", wireType)
			}
			m.PlayerCent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerCent |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeatId", wireType)
			}
			m.SeatId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SeatId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetRateLine", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BetRateLine == nil {
				m.BetRateLine = &proto2.BetRateLine{}
			}
			if err := m.BetRateLine.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvatarId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvatarId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Visible", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Visible == nil {
				m.Visible = &UserInfo_Column{}
			}
			if err := m.Visible.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlayerType", wireType)
			}
			m.PlayerType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PlayerType |= PLAYER_TYPE(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserInfo_Column) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Column: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Column: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Id = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Name = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Balance = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Avatar = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BroadcastPlayerIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BroadcastPlayerIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BroadcastPlayerIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Player = append(m.Player, &UserInfo{})
			if err := m.Player[len(m.Player)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BroadcastPlayerOut) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BroadcastPlayerOut: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BroadcastPlayerOut: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuth
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Player == nil {
				m.Player = &UserInfo{}
			}
			if err := m.Player.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAuth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuth(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuth
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuth
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuth
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuth
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuth        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuth          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuth = fmt.Errorf("proto: unexpected end of group")
)
