package rpc

import (
	"encoding/json"
	"fmt"
	"github.com/nats-io/nats.go"
	"serve/servicehacksaw/hacksawcomm"
)

func init() {
	hacksawcomm.RegRpc("gameInfo", gameInfo)
}

var (
	gameInfoTemplate = `{
  "statusCode": "0",
  "statusMessage": "",
  "data": {
    "reelSets": [
      {
        "name": "default",
        "reels": [
          {
            "index": "0",
            "symbols": [
              "1",
              "1",
              "1",
              "5",
              "5",
              "6",
              "6",
              "4",
              "4",
              "8",
              "8",
              "3",
              "3",
              "2",
              "2",
              "2",
              "8",
              "7",
              "1",
              "9",
              "9",
              "9",
              "10",
              "10",
              "1",
              "5",
              "5",
              "5",
              "4",
              "4",
              "4",
              "2",
              "2",
              "8",
              "1",
              "4",
              "4",
              "4",
              "7",
              "9",
              "10",
              "3",
              "3",
              "3",
              "6",
              "6",
              "6",
              "9",
              "9",
              "9",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6",
              "7",
              "8",
              "9",
              "10"
            ]
          },
          {
            "index": "1",
            "symbols": [
              "10",
              "2",
              "4",
              "7",
              "7",
              "2",
              "8",
              "8",
              "6",
              "6",
              "2",
              "3",
              "8",
              "8",
              "9",
              "9",
              "9",
              "3",
              "3",
              "3",
              "1",
              "2",
              "7",
              "5",
              "2",
              "9",
              "10",
              "10",
              "7",
              "4",
              "4",
              "1",
              "1",
              "1",
              "9",
              "5",
              "5",
              "1",
              "5",
              "5",
              "8",
              "8",
              "8",
              "2",
              "2",
              "2",
              "5",
              "5",
              "2",
              "9",
              "9",
              "10",
              "7",
              "7",
              "7",
              "2",
              "2",
              "2",
              "7",
              "7",
              "7",
              "1",
              "1",
              "1"
            ]
          },
          {
            "index": "2",
            "symbols": [
              "7",
              "8",
              "8",
              "2",
              "6",
              "3",
              "1",
              "9",
              "10",
              "10",
              "10",
              "6",
              "7",
              "7",
              "7",
              "5",
              "5",
              "5",
              "9",
              "1",
              "1",
              "8",
              "4",
              "2",
              "2",
              "7",
              "7",
              "1",
              "1",
              "4",
              "9",
              "4",
              "10",
              "8",
              "1",
              "1",
              "3",
              "9",
              "9",
              "9",
              "1",
              "1",
              "1",
              "6",
              "6",
              "8",
              "8",
              "10",
              "10",
              "10",
              "6",
              "6",
              "6",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6",
              "7",
              "8",
              "9",
              "10"
            ]
          },
          {
            "index": "3",
            "symbols": [
              "2",
              "2",
              "5",
              "5",
              "4",
              "4",
              "7",
              "2",
              "1",
              "1",
              "5",
              "7",
              "7",
              "9",
              "10",
              "6",
              "6",
              "6",
              "4",
              "4",
              "8",
              "10",
              "10",
              "10",
              "2",
              "1",
              "9",
              "5",
              "10",
              "8",
              "2",
              "5",
              "5",
              "8",
              "4",
              "8",
              "8",
              "4",
              "9",
              "9",
              "9",
              "3",
              "1",
              "2",
              "2",
              "2",
              "8",
              "8",
              "6",
              "6",
              "6",
              "1",
              "1",
              "1"
            ]
          },
          {
            "index": "4",
            "symbols": [
              "6",
              "6",
              "1",
              "8",
              "8",
              "8",
              "10",
              "10",
              "9",
              "4",
              "4",
              "4",
              "7",
              "7",
              "7",
              "1",
              "9",
              "2",
              "2",
              "6",
              "4",
              "10",
              "10",
              "10",
              "4",
              "2",
              "3",
              "3",
              "8",
              "1",
              "6",
              "6",
              "7",
              "9",
              "9",
              "9",
              "2",
              "2",
              "5",
              "5",
              "10",
              "10",
              "9",
              "9",
              "9",
              "5",
              "5",
              "5",
              "7",
              "7",
              "7",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6",
              "7",
              "8",
              "9",
              "10"
            ]
          }
        ]
      },
      {
        "name": "underworld",
        "reels": [
          {
            "index": "0",
            "symbols": [
              "1",
              "1",
              "1",
              "5",
              "5",
              "6",
              "6",
              "4",
              "4",
              "8",
              "8",
              "3",
              "3",
              "2",
              "2",
              "2",
              "8",
              "8",
              "7",
              "1",
              "9",
              "9",
              "9",
              "10",
              "10",
              "1",
              "1",
              "1",
              "5",
              "5",
              "5",
              "4",
              "4",
              "4",
              "2",
              "2",
              "8",
              "1",
              "4",
              "4",
              "4",
              "7",
              "9",
              "10",
              "3",
              "3",
              "3",
              "6",
              "6",
              "6",
              "9",
              "9",
              "9",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6",
              "7",
              "8",
              "9",
              "10"
            ]
          },
          {
            "index": "1",
            "symbols": [
              "10",
              "2",
              "4",
              "7",
              "7",
              "2",
              "8",
              "8",
              "6",
              "6",
              "2",
              "3",
              "8",
              "8",
              "9",
              "9",
              "9",
              "3",
              "3",
              "3",
              "1",
              "2",
              "7",
              "5",
              "2",
              "9",
              "10",
              "10",
              "7",
              "4",
              "4",
              "3",
              "3",
              "1",
              "1",
              "1",
              "9",
              "5",
              "5",
              "1",
              "5",
              "5",
              "8",
              "8",
              "8",
              "2",
              "2",
              "2",
              "7",
              "7",
              "5",
              "5",
              "2",
              "9",
              "9",
              "10",
              "7",
              "7",
              "7",
              "2",
              "2",
              "2",
              "7",
              "7",
              "7",
              "1",
              "1",
              "1"
            ]
          },
          {
            "index": "2",
            "symbols": [
              "7",
              "8",
              "8",
              "2",
              "6",
              "3",
              "1",
              "9",
              "10",
              "10",
              "6",
              "7",
              "7",
              "7",
              "5",
              "5",
              "5",
              "9",
              "1",
              "1",
              "8",
              "4",
              "2",
              "2",
              "7",
              "7",
              "6",
              "6",
              "1",
              "1",
              "4",
              "9",
              "4",
              "4",
              "10",
              "8",
              "1",
              "1",
              "3",
              "3",
              "9",
              "2",
              "9",
              "1",
              "1",
              "1",
              "6",
              "6",
              "8",
              "8",
              "10",
              "10",
              "10",
              "6",
              "6",
              "6",
              "1",
              "2",
              "3",
              "3",
              "4",
              "5",
              "6",
              "7",
              "8",
              "9",
              "10"
            ]
          },
          {
            "index": "3",
            "symbols": [
              "2",
              "2",
              "5",
              "5",
              "4",
              "4",
              "7",
              "2",
              "1",
              "1",
              "5",
              "7",
              "7",
              "9",
              "10",
              "6",
              "6",
              "6",
              "4",
              "4",
              "8",
              "10",
              "10",
              "2",
              "2",
              "2",
              "1",
              "9",
              "5",
              "10",
              "8",
              "2",
              "5",
              "5",
              "8",
              "4",
              "8",
              "8",
              "4",
              "9",
              "9",
              "9",
              "3",
              "1",
              "2",
              "2",
              "2",
              "8",
              "8",
              "6",
              "6",
              "6",
              "1",
              "1",
              "1"
            ]
          },
          {
            "index": "4",
            "symbols": [
              "6",
              "6",
              "1",
              "8",
              "8",
              "8",
              "10",
              "10",
              "9",
              "4",
              "4",
              "4",
              "7",
              "7",
              "7",
              "1",
              "9",
              "2",
              "2",
              "6",
              "6",
              "4",
              "10",
              "10",
              "10",
              "4",
              "7",
              "2",
              "3",
              "3",
              "8",
              "1",
              "6",
              "6",
              "7",
              "9",
              "9",
              "9",
              "2",
              "2",
              "5",
              "5",
              "4",
              "4",
              "4",
              "10",
              "10",
              "9",
              "9",
              "9",
              "5",
              "5",
              "5",
              "8",
              "8",
              "7",
              "7",
              "7",
              "1",
              "2",
              "3",
              "4",
              "5",
              "6",
              "7",
              "8",
              "9",
              "10"
            ]
          }
        ]
      }
    ],
    "symbols": [
      {
        "id": "1",
        "name": "LOW_1",
        "payouts": {
          "_5": "1",
          "_6": "2",
          "_7": "3",
          "_8": "5",
          "_9": "20",
          "_10": "75",
          "_11_inf": "150"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "2",
        "name": "LOW_2",
        "payouts": {
          "_5": "1",
          "_6": "2",
          "_7": "3",
          "_8": "5",
          "_9": "20",
          "_10": "75",
          "_11_inf": "150"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "3",
        "name": "LOW_3",
        "payouts": {
          "_5": "1",
          "_6": "2",
          "_7": "3",
          "_8": "5",
          "_9": "20",
          "_10": "75",
          "_11_inf": "150"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "4",
        "name": "LOW_4",
        "payouts": {
          "_5": "1",
          "_6": "2",
          "_7": "3",
          "_8": "5",
          "_9": "20",
          "_10": "75",
          "_11_inf": "150"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "5",
        "name": "LOW_5",
        "payouts": {
          "_5": "1",
          "_6": "2",
          "_7": "3",
          "_8": "5",
          "_9": "20",
          "_10": "75",
          "_11_inf": "150"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "6",
        "name": "HIGH_1",
        "payouts": {
          "_5": "3",
          "_6": "6",
          "_7": "10",
          "_8": "20",
          "_9": "30",
          "_10": "150",
          "_11_inf": "200"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "7",
        "name": "HIGH_2",
        "payouts": {
          "_5": "3",
          "_6": "6",
          "_7": "10",
          "_8": "20",
          "_9": "30",
          "_10": "150",
          "_11_inf": "200"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "8",
        "name": "HIGH_3",
        "payouts": {
          "_5": "5",
          "_6": "10",
          "_7": "20",
          "_8": "30",
          "_9": "40",
          "_10": "175",
          "_11_inf": "400"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "9",
        "name": "HIGH_4",
        "payouts": {
          "_5": "5",
          "_6": "10",
          "_7": "20",
          "_8": "30",
          "_9": "40",
          "_10": "175",
          "_11_inf": "400"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "10",
        "name": "HIGH_5",
        "payouts": {
          "_5": "10",
          "_6": "15",
          "_7": "25",
          "_8": "40",
          "_9": "50",
          "_10": "200",
          "_11_inf": "600"
        },
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "11",
        "name": "ORB_BLUE",
        "payouts": {},
        "isWild": "1",
        "isScatter": "0"
      },
      {
        "id": "12",
        "name": "ORB_RED",
        "payouts": {},
        "isWild": "1",
        "isScatter": "0"
      },
      {
        "id": "13",
        "name": "FS",
        "payouts": {},
        "isWild": "0",
        "isScatter": "1"
      },
      {
        "id": "18",
        "name": "GLASS",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "41",
        "name": "DEAD_1",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "42",
        "name": "DEAD_2",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "43",
        "name": "DEAD_3",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "44",
        "name": "DEAD_4",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "20",
        "name": "ADD_1",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "21",
        "name": "ADD_2",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "22",
        "name": "ADD_3",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "23",
        "name": "ADD_4",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "24",
        "name": "ADD_5",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "25",
        "name": "ADD_10",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "26",
        "name": "ADD_25",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "27",
        "name": "ADD_50",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "28",
        "name": "ADD_100",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "31",
        "name": "MULT_2",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "32",
        "name": "MULT_3",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "33",
        "name": "MULT_4",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "34",
        "name": "MULT_5",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "35",
        "name": "MULT_10",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "70",
        "name": "ADD_1_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "71",
        "name": "ADD_2_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "72",
        "name": "ADD_3_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "73",
        "name": "ADD_4_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "74",
        "name": "ADD_5_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "75",
        "name": "ADD_10_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "76",
        "name": "ADD_25_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "77",
        "name": "ADD_50_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "78",
        "name": "ADD_100_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "81",
        "name": "MULT_2_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "82",
        "name": "MULT_3_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "83",
        "name": "MULT_4_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "84",
        "name": "MULT_5_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "85",
        "name": "MULT_10_EPIC",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "60",
        "name": "ACTIVATED_CUBE",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "61",
        "name": "UNDERWORLD_ACTIVATOR",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "62",
        "name": "JUDGMENT_CRUSHER",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      },
      {
        "id": "63",
        "name": "UNDERWORLD_EPIC_ACTIVATOR",
        "payouts": {},
        "isWild": "0",
        "isScatter": "0"
      }
    ],
    "lines": [],
    "baseBetLevel": "10",
    "gameSpecificInfo": null,
    "rtp": 96.24,
    "hitFrequency": 0,
    "oddsOfMaxWin": "0",
    "jackpotSizeCents": "0",
    "maximumWinMultiplier": "10000"
  }
}`
)

func gameInfo(msg *nats.Msg) (ret []byte, err error) {
	var data map[string]interface{}
	if err = json.Unmarshal([]byte(gameInfoTemplate), &data); err != nil {
		fmt.Println("Error unmarshaling JSON:", err)
	}
	modifiedJSON, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		fmt.Println("Error marshaling JSON:", err)
	}
	ret = modifiedJSON

	return
}
