// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc2
// source: tmp.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Symbol int32

const (
	Symbol_Wild    Symbol = 0
	Symbol_Bonus   Symbol = 1
	Symbol_Symbol1 Symbol = 2
	Symbol_Symbol2 Symbol = 3
	Symbol_Symbol3 Symbol = 4
	Symbol_Symbol4 Symbol = 5
	Symbol_Symbol5 Symbol = 6
	Symbol_Symbol6 Symbol = 7
	Symbol_Symbol7 Symbol = 8
	Symbol_Symbol8 Symbol = 9
	Symbol_Symbol9 Symbol = 10
)

// Enum value maps for Symbol.
var (
	Symbol_name = map[int32]string{
		0:  "Wild",
		1:  "Bonus",
		2:  "Symbol1",
		3:  "Symbol2",
		4:  "Symbol3",
		5:  "Symbol4",
		6:  "Symbol5",
		7:  "Symbol6",
		8:  "Symbol7",
		9:  "Symbol8",
		10: "Symbol9",
	}
	Symbol_value = map[string]int32{
		"Wild":    0,
		"Bonus":   1,
		"Symbol1": 2,
		"Symbol2": 3,
		"Symbol3": 4,
		"Symbol4": 5,
		"Symbol5": 6,
		"Symbol6": 7,
		"Symbol7": 8,
		"Symbol8": 9,
		"Symbol9": 10,
	}
)

func (x Symbol) Enum() *Symbol {
	p := new(Symbol)
	*p = x
	return p
}

func (x Symbol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Symbol) Descriptor() protoreflect.EnumDescriptor {
	return file_tmp_proto_enumTypes[0].Descriptor()
}

func (Symbol) Type() protoreflect.EnumType {
	return &file_tmp_proto_enumTypes[0]
}

func (x Symbol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Symbol.Descriptor instead.
func (Symbol) EnumDescriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{0}
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row    uint32 `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column uint32 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetRow() uint32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Block) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type Plate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column    []*ColumnData      `protobuf:"bytes,1,rep,name=column,proto3" json:"column,omitempty"`
	Award     []*Plate_AwardReel `protobuf:"bytes,2,rep,name=award,proto3" json:"award,omitempty"`
	Win       float64            `protobuf:"fixed64,3,opt,name=win,proto3" json:"win,omitempty"`
	BallCount uint32             `protobuf:"varint,4,opt,name=ball_count,json=ballCount,proto3" json:"ball_count,omitempty"`
	BonusWin  float64            `protobuf:"fixed64,5,opt,name=bonus_win,json=bonusWin,proto3" json:"bonus_win,omitempty"`
}

func (x *Plate) Reset() {
	*x = Plate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plate) ProtoMessage() {}

func (x *Plate) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plate.ProtoReflect.Descriptor instead.
func (*Plate) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{1}
}

func (x *Plate) GetColumn() []*ColumnData {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *Plate) GetAward() []*Plate_AwardReel {
	if x != nil {
		return x.Award
	}
	return nil
}

func (x *Plate) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

func (x *Plate) GetBallCount() uint32 {
	if x != nil {
		return x.BallCount
	}
	return 0
}

func (x *Plate) GetBonusWin() float64 {
	if x != nil {
		return x.BonusWin
	}
	return 0
}

type AllPlate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plate []*Plate `protobuf:"bytes,1,rep,name=plate,proto3" json:"plate,omitempty"`
}

func (x *AllPlate) Reset() {
	*x = AllPlate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllPlate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPlate) ProtoMessage() {}

func (x *AllPlate) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPlate.ProtoReflect.Descriptor instead.
func (*AllPlate) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{2}
}

func (x *AllPlate) GetPlate() []*Plate {
	if x != nil {
		return x.Plate
	}
	return nil
}

type ColumnData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row   []int32   `protobuf:"varint,1,rep,packed,name=row,proto3" json:"row,omitempty"`
	Bonus []float64 `protobuf:"fixed64,2,rep,packed,name=bonus,proto3" json:"bonus,omitempty"`
}

func (x *ColumnData) Reset() {
	*x = ColumnData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnData) ProtoMessage() {}

func (x *ColumnData) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnData.ProtoReflect.Descriptor instead.
func (*ColumnData) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnData) GetRow() []int32 {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *ColumnData) GetBonus() []float64 {
	if x != nil {
		return x.Bonus
	}
	return nil
}

type Plate_AwardReel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line  uint32   `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Block []*Block `protobuf:"bytes,2,rep,name=block,proto3" json:"block,omitempty"`
	Win   float64  `protobuf:"fixed64,3,opt,name=win,proto3" json:"win,omitempty"`
}

func (x *Plate_AwardReel) Reset() {
	*x = Plate_AwardReel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tmp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plate_AwardReel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plate_AwardReel) ProtoMessage() {}

func (x *Plate_AwardReel) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plate_AwardReel.ProtoReflect.Descriptor instead.
func (*Plate_AwardReel) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Plate_AwardReel) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Plate_AwardReel) GetBlock() []*Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *Plate_AwardReel) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

var File_tmp_proto protoreflect.FileDescriptor

var file_tmp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x74, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x22, 0x8b, 0x02, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x74,
	0x65, 0x12, 0x2b, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x2e,
	0x0a, 0x05, 0x61, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x41, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x65, 0x6c, 0x52, 0x05, 0x61, 0x77, 0x61, 0x72, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x77, 0x69, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x62, 0x61, 0x6c, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x57, 0x69, 0x6e, 0x1a, 0x57, 0x0a, 0x09,
	0x41, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x24, 0x0a,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x77, 0x69, 0x6e, 0x22, 0x30, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x74,
	0x65, 0x12, 0x24, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x2a, 0x92, 0x01,
	0x0a, 0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x69, 0x6c, 0x64,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x31, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x32, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x33, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x34, 0x10,
	0x05, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x35, 0x10, 0x06, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x36, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x37, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x38, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x39,
	0x10, 0x0a, 0x42, 0x2e, 0x5a, 0x2c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x6a, 0x69, 0x6c, 0x69, 0x2f, 0x6a, 0x69, 0x6c, 0x69, 0x5f, 0x31, 0x37, 0x5f,
	0x73, 0x77, 0x65, 0x65, 0x74, 0x68, 0x65, 0x61, 0x72, 0x74, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tmp_proto_rawDescOnce sync.Once
	file_tmp_proto_rawDescData = file_tmp_proto_rawDesc
)

func file_tmp_proto_rawDescGZIP() []byte {
	file_tmp_proto_rawDescOnce.Do(func() {
		file_tmp_proto_rawDescData = protoimpl.X.CompressGZIP(file_tmp_proto_rawDescData)
	})
	return file_tmp_proto_rawDescData
}

var file_tmp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tmp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_tmp_proto_goTypes = []any{
	(Symbol)(0),             // 0: message.Symbol
	(*Block)(nil),           // 1: message.Block
	(*Plate)(nil),           // 2: message.Plate
	(*AllPlate)(nil),        // 3: message.AllPlate
	(*ColumnData)(nil),      // 4: message.ColumnData
	(*Plate_AwardReel)(nil), // 5: message.Plate.AwardReel
}
var file_tmp_proto_depIdxs = []int32{
	4, // 0: message.Plate.column:type_name -> message.ColumnData
	5, // 1: message.Plate.award:type_name -> message.Plate.AwardReel
	2, // 2: message.AllPlate.plate:type_name -> message.Plate
	1, // 3: message.Plate.AwardReel.block:type_name -> message.Block
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tmp_proto_init() }
func file_tmp_proto_init() {
	if File_tmp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tmp_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Plate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AllPlate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ColumnData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tmp_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Plate_AwardReel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tmp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmp_proto_goTypes,
		DependencyIndexes: file_tmp_proto_depIdxs,
		EnumInfos:         file_tmp_proto_enumTypes,
		MessageInfos:      file_tmp_proto_msgTypes,
	}.Build()
	File_tmp_proto = out.File
	file_tmp_proto_rawDesc = nil
	file_tmp_proto_goTypes = nil
	file_tmp_proto_depIdxs = nil
}
