// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pb/adminpb/json.proto

package adminpb

import (
	pb "game/pb/_gen/pb"
	mongodb "game/duck/mongodb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=FileName,proto3" `
	Content  string `protobuf:"bytes,2,opt,name=Content,proto3" `
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_adminpb_json_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adminpb_json_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_pb_adminpb_json_proto_rawDescGZIP(), []int{0}
}

func (x *FileContent) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DBConfigFileLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *mongodb.ObjectID  `protobuf:"bytes,1,opt,name=Id,proto3" bson:"_id"`
	User     int64              `protobuf:"varint,2,opt,name=User,proto3" ` // 操作人
	FileName string             `protobuf:"bytes,3,opt,name=FileName,proto3" `
	Content  string             `protobuf:"bytes,4,opt,name=Content,proto3" `
	CreateAt *mongodb.TimeStamp `protobuf:"bytes,5,opt,name=CreateAt,proto3" ` // 操作时间
}

func (x *DBConfigFileLog) Reset() {
	*x = DBConfigFileLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_adminpb_json_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBConfigFileLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBConfigFileLog) ProtoMessage() {}

func (x *DBConfigFileLog) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adminpb_json_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBConfigFileLog.ProtoReflect.Descriptor instead.
func (*DBConfigFileLog) Descriptor() ([]byte, []int) {
	return file_pb_adminpb_json_proto_rawDescGZIP(), []int{1}
}

func (x *DBConfigFileLog) GetId() *mongodb.ObjectID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DBConfigFileLog) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *DBConfigFileLog) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DBConfigFileLog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DBConfigFileLog) GetCreateAt() *mongodb.TimeStamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

type FileHistoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DBConfigFileLog `protobuf:"bytes,1,rep,name=List,proto3" `
}

func (x *FileHistoryResp) Reset() {
	*x = FileHistoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_adminpb_json_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileHistoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHistoryResp) ProtoMessage() {}

func (x *FileHistoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adminpb_json_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHistoryResp.ProtoReflect.Descriptor instead.
func (*FileHistoryResp) Descriptor() ([]byte, []int) {
	return file_pb_adminpb_json_proto_rawDescGZIP(), []int{2}
}

func (x *FileHistoryResp) GetList() []*DBConfigFileLog {
	if x != nil {
		return x.List
	}
	return nil
}

type FileHistoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count    int64  `protobuf:"varint,1,opt,name=Count,proto3" `      // 最近多少条
	FileName string `protobuf:"bytes,2,opt,name=FileName,proto3" ` // 文件名
}

func (x *FileHistoryReq) Reset() {
	*x = FileHistoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_adminpb_json_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHistoryReq) ProtoMessage() {}

func (x *FileHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adminpb_json_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHistoryReq.ProtoReflect.Descriptor instead.
func (*FileHistoryReq) Descriptor() ([]byte, []int) {
	return file_pb_adminpb_json_proto_rawDescGZIP(), []int{3}
}

func (x *FileHistoryReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FileHistoryReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

var File_pb_adminpb_json_proto protoreflect.FileDescriptor

var file_pb_adminpb_json_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2f, 0x6a, 0x73, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x62, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x70, 0x62, 0x2f, 0x64, 0x75, 0x63, 0x6b,
	0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x44, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70, 0x62, 0x2f, 0x64, 0x75, 0x63, 0x6b,
	0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x9e, 0x01,
	0x0a, 0x0f, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f,
	0x67, 0x12, 0x19, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x55, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x37,
	0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x24, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x44, 0x42, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x6f,
	0x67, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x91, 0x01, 0x0a, 0x0f,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x22, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0c, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x0a, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x0c, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a,
	0x0c, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x0f, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x26, 0x42, 0x09, 0x4a, 0x73, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x17,
	0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x2f,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_adminpb_json_proto_rawDescOnce sync.Once
	file_pb_adminpb_json_proto_rawDescData = file_pb_adminpb_json_proto_rawDesc
)

func file_pb_adminpb_json_proto_rawDescGZIP() []byte {
	file_pb_adminpb_json_proto_rawDescOnce.Do(func() {
		file_pb_adminpb_json_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_adminpb_json_proto_rawDescData)
	})
	return file_pb_adminpb_json_proto_rawDescData
}

var file_pb_adminpb_json_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_adminpb_json_proto_goTypes = []interface{}{
	(*FileContent)(nil),       // 0: FileContent
	(*DBConfigFileLog)(nil),   // 1: DBConfigFileLog
	(*FileHistoryResp)(nil),   // 2: FileHistoryResp
	(*FileHistoryReq)(nil),    // 3: FileHistoryReq
	(*mongodb.ObjectID)(nil),  // 4: ObjectID
	(*mongodb.TimeStamp)(nil), // 5: TimeStamp
	(*pb.Empty)(nil),          // 6: Empty
}
var file_pb_adminpb_json_proto_depIdxs = []int32{
	4, // 0: DBConfigFileLog.Id:type_name -> ObjectID
	5, // 1: DBConfigFileLog.CreateAt:type_name -> TimeStamp
	1, // 2: FileHistoryResp.List:type_name -> DBConfigFileLog
	0, // 3: AdminConfigFile.SaveConfig:input_type -> FileContent
	0, // 4: AdminConfigFile.LoadConfig:input_type -> FileContent
	3, // 5: AdminConfigFile.FileHistory:input_type -> FileHistoryReq
	6, // 6: AdminConfigFile.SaveConfig:output_type -> Empty
	0, // 7: AdminConfigFile.LoadConfig:output_type -> FileContent
	2, // 8: AdminConfigFile.FileHistory:output_type -> FileHistoryResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_adminpb_json_proto_init() }
func file_pb_adminpb_json_proto_init() {
	if File_pb_adminpb_json_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_adminpb_json_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_adminpb_json_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBConfigFileLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_adminpb_json_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileHistoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_adminpb_json_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileHistoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_adminpb_json_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_adminpb_json_proto_goTypes,
		DependencyIndexes: file_pb_adminpb_json_proto_depIdxs,
		MessageInfos:      file_pb_adminpb_json_proto_msgTypes,
	}.Build()
	File_pb_adminpb_json_proto = out.File
	file_pb_adminpb_json_proto_rawDesc = nil
	file_pb_adminpb_json_proto_goTypes = nil
	file_pb_adminpb_json_proto_depIdxs = nil
}
