// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pb/adminpb/json.proto

package adminpb

import (
	context "context"
	pb "game/pb/_gen/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminConfigFileClient is the client API for AdminConfigFile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminConfigFileClient interface {
	// 保存配置
	SaveConfig(ctx context.Context, in *FileContent, opts ...grpc.CallOption) (*pb.Empty, error)
	// 读取配置 Content 不传
	LoadConfig(ctx context.Context, in *FileContent, opts ...grpc.CallOption) (*FileContent, error)
	// 查看某个文件的历史记录 最近n条
	FileHistory(ctx context.Context, in *FileHistoryReq, opts ...grpc.CallOption) (*FileHistoryResp, error)
}

type adminConfigFileClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminConfigFileClient(cc grpc.ClientConnInterface) AdminConfigFileClient {
	return &adminConfigFileClient{cc}
}

func (c *adminConfigFileClient) SaveConfig(ctx context.Context, in *FileContent, opts ...grpc.CallOption) (*pb.Empty, error) {
	out := new(pb.Empty)
	err := c.cc.Invoke(ctx, "/AdminConfigFile/SaveConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConfigFileClient) LoadConfig(ctx context.Context, in *FileContent, opts ...grpc.CallOption) (*FileContent, error) {
	out := new(FileContent)
	err := c.cc.Invoke(ctx, "/AdminConfigFile/LoadConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminConfigFileClient) FileHistory(ctx context.Context, in *FileHistoryReq, opts ...grpc.CallOption) (*FileHistoryResp, error) {
	out := new(FileHistoryResp)
	err := c.cc.Invoke(ctx, "/AdminConfigFile/FileHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminConfigFileServer is the server API for AdminConfigFile service.
// All implementations should embed UnimplementedAdminConfigFileServer
// for forward compatibility
type AdminConfigFileServer interface {
	// 保存配置
	SaveConfig(context.Context, *FileContent) (*pb.Empty, error)
	// 读取配置 Content 不传
	LoadConfig(context.Context, *FileContent) (*FileContent, error)
	// 查看某个文件的历史记录 最近n条
	FileHistory(context.Context, *FileHistoryReq) (*FileHistoryResp, error)
}

// UnimplementedAdminConfigFileServer should be embedded to have forward compatible implementations.
type UnimplementedAdminConfigFileServer struct {
}

func (UnimplementedAdminConfigFileServer) SaveConfig(context.Context, *FileContent) (*pb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveConfig not implemented")
}
func (UnimplementedAdminConfigFileServer) LoadConfig(context.Context, *FileContent) (*FileContent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadConfig not implemented")
}
func (UnimplementedAdminConfigFileServer) FileHistory(context.Context, *FileHistoryReq) (*FileHistoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileHistory not implemented")
}

// UnsafeAdminConfigFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminConfigFileServer will
// result in compilation errors.
type UnsafeAdminConfigFileServer interface {
	mustEmbedUnimplementedAdminConfigFileServer()
}

func RegisterAdminConfigFileServer(s grpc.ServiceRegistrar, srv AdminConfigFileServer) {
	s.RegisterService(&AdminConfigFile_ServiceDesc, srv)
}

func _AdminConfigFile_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConfigFileServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AdminConfigFile/SaveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConfigFileServer).SaveConfig(ctx, req.(*FileContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConfigFile_LoadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConfigFileServer).LoadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AdminConfigFile/LoadConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConfigFileServer).LoadConfig(ctx, req.(*FileContent))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminConfigFile_FileHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminConfigFileServer).FileHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AdminConfigFile/FileHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminConfigFileServer).FileHistory(ctx, req.(*FileHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminConfigFile_ServiceDesc is the grpc.ServiceDesc for AdminConfigFile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminConfigFile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AdminConfigFile",
	HandlerType: (*AdminConfigFileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveConfig",
			Handler:    _AdminConfigFile_SaveConfig_Handler,
		},
		{
			MethodName: "LoadConfig",
			Handler:    _AdminConfigFile_LoadConfig_Handler,
		},
		{
			MethodName: "FileHistory",
			Handler:    _AdminConfigFile_FileHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/adminpb/json.proto",
}
