// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pb/adminpb/menu.proto

package adminpb

import (
	pb "game/pb/_gen/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MenuList []*DBMenu `protobuf:"bytes,1,rep,name=MenuList,proto3" `
}

func (x *MenuListResp) Reset() {
	*x = MenuListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_adminpb_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MenuListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuListResp) ProtoMessage() {}

func (x *MenuListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adminpb_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuListResp.ProtoReflect.Descriptor instead.
func (*MenuListResp) Descriptor() ([]byte, []int) {
	return file_pb_adminpb_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuListResp) GetMenuList() []*DBMenu {
	if x != nil {
		return x.MenuList
	}
	return nil
}

type DelMenuReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" `
}

func (x *DelMenuReq) Reset() {
	*x = DelMenuReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_adminpb_menu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelMenuReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMenuReq) ProtoMessage() {}

func (x *DelMenuReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_adminpb_menu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMenuReq.ProtoReflect.Descriptor instead.
func (*DelMenuReq) Descriptor() ([]byte, []int) {
	return file_pb_adminpb_menu_proto_rawDescGZIP(), []int{1}
}

func (x *DelMenuReq) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_pb_adminpb_menu_proto protoreflect.FileDescriptor

var file_pb_adminpb_menu_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x6e,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x70, 0x62, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70, 0x62, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x70, 0x62, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33,
	0x0a, 0x0c, 0x4d, 0x65, 0x6e, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23,
	0x0a, 0x08, 0x4d, 0x65, 0x6e, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x07, 0x2e, 0x44, 0x42, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x08, 0x4d, 0x65, 0x6e, 0x75, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x32, 0x89, 0x01, 0x0a, 0x09, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4d, 0x65, 0x6e, 0x75, 0x12,
	0x21, 0x0a, 0x08, 0x4d, 0x65, 0x6e, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x06, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1a, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x07, 0x2e,
	0x44, 0x42, 0x4d, 0x65, 0x6e, 0x75, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x07, 0x2e, 0x44,
	0x42, 0x4d, 0x65, 0x6e, 0x75, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x1e, 0x0a,
	0x07, 0x44, 0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x0b, 0x2e, 0x44, 0x65, 0x6c, 0x4d, 0x65,
	0x6e, 0x75, 0x52, 0x65, 0x71, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x26, 0x42,
	0x09, 0x4d, 0x65, 0x6e, 0x75, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x17, 0x67, 0x61,
	0x6d, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_adminpb_menu_proto_rawDescOnce sync.Once
	file_pb_adminpb_menu_proto_rawDescData = file_pb_adminpb_menu_proto_rawDesc
)

func file_pb_adminpb_menu_proto_rawDescGZIP() []byte {
	file_pb_adminpb_menu_proto_rawDescOnce.Do(func() {
		file_pb_adminpb_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_adminpb_menu_proto_rawDescData)
	})
	return file_pb_adminpb_menu_proto_rawDescData
}

var file_pb_adminpb_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_adminpb_menu_proto_goTypes = []interface{}{
	(*MenuListResp)(nil), // 0: MenuListResp
	(*DelMenuReq)(nil),   // 1: DelMenuReq
	(*DBMenu)(nil),       // 2: DBMenu
	(*pb.Empty)(nil),     // 3: Empty
}
var file_pb_adminpb_menu_proto_depIdxs = []int32{
	2, // 0: MenuListResp.MenuList:type_name -> DBMenu
	3, // 1: AdminMenu.MenuList:input_type -> Empty
	2, // 2: AdminMenu.AddMenu:input_type -> DBMenu
	2, // 3: AdminMenu.UpdateMenu:input_type -> DBMenu
	1, // 4: AdminMenu.DelMenu:input_type -> DelMenuReq
	0, // 5: AdminMenu.MenuList:output_type -> MenuListResp
	3, // 6: AdminMenu.AddMenu:output_type -> Empty
	3, // 7: AdminMenu.UpdateMenu:output_type -> Empty
	3, // 8: AdminMenu.DelMenu:output_type -> Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_adminpb_menu_proto_init() }
func file_pb_adminpb_menu_proto_init() {
	if File_pb_adminpb_menu_proto != nil {
		return
	}
	file_pb_adminpb_info_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_adminpb_menu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MenuListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_adminpb_menu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelMenuReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_adminpb_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_adminpb_menu_proto_goTypes,
		DependencyIndexes: file_pb_adminpb_menu_proto_depIdxs,
		MessageInfos:      file_pb_adminpb_menu_proto_msgTypes,
	}.Build()
	File_pb_adminpb_menu_proto = out.File
	file_pb_adminpb_menu_proto_rawDesc = nil
	file_pb_adminpb_menu_proto_goTypes = nil
	file_pb_adminpb_menu_proto_depIdxs = nil
}
