// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: tmp.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           []int32                `protobuf:"varint,1,rep,packed,name=Row,proto3" json:"Row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_tmp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetRow() []int32 {
	if x != nil {
		return x.Row
	}
	return nil
}

type AwardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        int32                  `protobuf:"varint,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Win           float64                `protobuf:"fixed64,3,opt,name=Win,proto3" json:"Win,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwardData) Reset() {
	*x = AwardData{}
	mi := &file_tmp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwardData) ProtoMessage() {}

func (x *AwardData) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwardData.ProtoReflect.Descriptor instead.
func (*AwardData) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{1}
}

func (x *AwardData) GetSymbol() int32 {
	if x != nil {
		return x.Symbol
	}
	return 0
}

func (x *AwardData) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AwardData) GetWin() float64 {
	if x != nil {
		return x.Win
	}
	return 0
}

type SinglePlate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        []*Column              `protobuf:"bytes,1,rep,name=Symbol,proto3" json:"Symbol,omitempty"`
	SingleWin     float64                `protobuf:"fixed64,2,opt,name=Single_win,json=SingleWin,proto3" json:"Single_win,omitempty"`
	AwardDataVec  []*AwardData           `protobuf:"bytes,3,rep,name=Award_data_vec,json=AwardDataVec,proto3" json:"Award_data_vec,omitempty"`
	CrystalType   int32                  `protobuf:"varint,4,opt,name=Crystal_type,json=CrystalType,proto3" json:"Crystal_type,omitempty"`
	NeedEliminate bool                   `protobuf:"varint,5,opt,name=Need_eliminate,json=NeedEliminate,proto3" json:"Need_eliminate,omitempty"`
	Eliminate     []*Column              `protobuf:"bytes,6,rep,name=Eliminate,proto3" json:"Eliminate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinglePlate) Reset() {
	*x = SinglePlate{}
	mi := &file_tmp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinglePlate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePlate) ProtoMessage() {}

func (x *SinglePlate) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePlate.ProtoReflect.Descriptor instead.
func (*SinglePlate) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{2}
}

func (x *SinglePlate) GetSymbol() []*Column {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *SinglePlate) GetSingleWin() float64 {
	if x != nil {
		return x.SingleWin
	}
	return 0
}

func (x *SinglePlate) GetAwardDataVec() []*AwardData {
	if x != nil {
		return x.AwardDataVec
	}
	return nil
}

func (x *SinglePlate) GetCrystalType() int32 {
	if x != nil {
		return x.CrystalType
	}
	return 0
}

func (x *SinglePlate) GetNeedEliminate() bool {
	if x != nil {
		return x.NeedEliminate
	}
	return false
}

func (x *SinglePlate) GetEliminate() []*Column {
	if x != nil {
		return x.Eliminate
	}
	return nil
}

type RoundInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlateQueue     []*SinglePlate         `protobuf:"bytes,1,rep,name=Plate_queue,json=PlateQueue,proto3" json:"Plate_queue,omitempty"`
	RoundWin       float64                `protobuf:"fixed64,2,opt,name=Round_win,json=RoundWin,proto3" json:"Round_win,omitempty"`
	RoundMulShow   []float64              `protobuf:"fixed64,3,rep,packed,name=Round_mul_show,json=RoundMulShow,proto3" json:"Round_mul_show,omitempty"`
	RoundMul       float64                `protobuf:"fixed64,4,opt,name=Round_mul,json=RoundMul,proto3" json:"Round_mul,omitempty"`
	EliminateCount int32                  `protobuf:"varint,5,opt,name=Eliminate_count,json=EliminateCount,proto3" json:"Eliminate_count,omitempty"`
	AwardTypeFlag  int32                  `protobuf:"varint,6,opt,name=Award_type_flag,json=AwardTypeFlag,proto3" json:"Award_type_flag,omitempty"`
	ScatterCount   int32                  `protobuf:"varint,7,opt,name=Scatter_count,json=ScatterCount,proto3" json:"Scatter_count,omitempty"`
	ScatterWin     float64                `protobuf:"fixed64,8,opt,name=Scatter_win,json=ScatterWin,proto3" json:"Scatter_win,omitempty"`
	GetFree        bool                   `protobuf:"varint,9,opt,name=Get_free,json=GetFree,proto3" json:"Get_free,omitempty"`
	GetFreeRound   int32                  `protobuf:"varint,10,opt,name=Get_free_round,json=GetFreeRound,proto3" json:"Get_free_round,omitempty"`
	MaxFlag        bool                   `protobuf:"varint,11,opt,name=Max_flag,json=MaxFlag,proto3" json:"Max_flag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoundInfo) Reset() {
	*x = RoundInfo{}
	mi := &file_tmp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundInfo) ProtoMessage() {}

func (x *RoundInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundInfo.ProtoReflect.Descriptor instead.
func (*RoundInfo) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{3}
}

func (x *RoundInfo) GetPlateQueue() []*SinglePlate {
	if x != nil {
		return x.PlateQueue
	}
	return nil
}

func (x *RoundInfo) GetRoundWin() float64 {
	if x != nil {
		return x.RoundWin
	}
	return 0
}

func (x *RoundInfo) GetRoundMulShow() []float64 {
	if x != nil {
		return x.RoundMulShow
	}
	return nil
}

func (x *RoundInfo) GetRoundMul() float64 {
	if x != nil {
		return x.RoundMul
	}
	return 0
}

func (x *RoundInfo) GetEliminateCount() int32 {
	if x != nil {
		return x.EliminateCount
	}
	return 0
}

func (x *RoundInfo) GetAwardTypeFlag() int32 {
	if x != nil {
		return x.AwardTypeFlag
	}
	return 0
}

func (x *RoundInfo) GetScatterCount() int32 {
	if x != nil {
		return x.ScatterCount
	}
	return 0
}

func (x *RoundInfo) GetScatterWin() float64 {
	if x != nil {
		return x.ScatterWin
	}
	return 0
}

func (x *RoundInfo) GetGetFree() bool {
	if x != nil {
		return x.GetFree
	}
	return false
}

func (x *RoundInfo) GetGetFreeRound() int32 {
	if x != nil {
		return x.GetFreeRound
	}
	return 0
}

func (x *RoundInfo) GetMaxFlag() bool {
	if x != nil {
		return x.MaxFlag
	}
	return false
}

type FreeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreeQueue     []*RoundInfo           `protobuf:"bytes,1,rep,name=Free_queue,json=FreeQueue,proto3" json:"Free_queue,omitempty"`
	FreeTotalWin  float64                `protobuf:"fixed64,2,opt,name=Free_total_win,json=FreeTotalWin,proto3" json:"Free_total_win,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeData) Reset() {
	*x = FreeData{}
	mi := &file_tmp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeData) ProtoMessage() {}

func (x *FreeData) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeData.ProtoReflect.Descriptor instead.
func (*FreeData) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{4}
}

func (x *FreeData) GetFreeQueue() []*RoundInfo {
	if x != nil {
		return x.FreeQueue
	}
	return nil
}

func (x *FreeData) GetFreeTotalWin() float64 {
	if x != nil {
		return x.FreeTotalWin
	}
	return 0
}

type SpinAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainGame      *RoundInfo             `protobuf:"bytes,1,opt,name=Main_game,json=MainGame,proto3" json:"Main_game,omitempty"`
	FreeGame      *FreeData              `protobuf:"bytes,2,opt,name=Free_game,json=FreeGame,proto3" json:"Free_game,omitempty"`
	TotalWin      float64                `protobuf:"fixed64,3,opt,name=Total_win,json=TotalWin,proto3" json:"Total_win,omitempty"`
	ShowIndex     string                 `protobuf:"bytes,4,opt,name=Show_index,json=ShowIndex,proto3" json:"Show_index,omitempty"`
	NowMoney      float64                `protobuf:"fixed64,5,opt,name=Now_money,json=NowMoney,proto3" json:"Now_money,omitempty"`
	AckType       int32                  `protobuf:"varint,6,opt,name=Ack_type,json=AckType,proto3" json:"Ack_type,omitempty"`
	RTP           float64                `protobuf:"fixed64,7,opt,name=RT_p,json=RTP,proto3" json:"RT_p,omitempty"`
	LID           int32                  `protobuf:"varint,8,opt,name=LI_d,json=LID,proto3" json:"LI_d,omitempty"`
	RID           int32                  `protobuf:"varint,9,opt,name=RI_d,json=RID,proto3" json:"RI_d,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinAck) Reset() {
	*x = SpinAck{}
	mi := &file_tmp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinAck) ProtoMessage() {}

func (x *SpinAck) ProtoReflect() protoreflect.Message {
	mi := &file_tmp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinAck.ProtoReflect.Descriptor instead.
func (*SpinAck) Descriptor() ([]byte, []int) {
	return file_tmp_proto_rawDescGZIP(), []int{5}
}

func (x *SpinAck) GetMainGame() *RoundInfo {
	if x != nil {
		return x.MainGame
	}
	return nil
}

func (x *SpinAck) GetFreeGame() *FreeData {
	if x != nil {
		return x.FreeGame
	}
	return nil
}

func (x *SpinAck) GetTotalWin() float64 {
	if x != nil {
		return x.TotalWin
	}
	return 0
}

func (x *SpinAck) GetShowIndex() string {
	if x != nil {
		return x.ShowIndex
	}
	return ""
}

func (x *SpinAck) GetNowMoney() float64 {
	if x != nil {
		return x.NowMoney
	}
	return 0
}

func (x *SpinAck) GetAckType() int32 {
	if x != nil {
		return x.AckType
	}
	return 0
}

func (x *SpinAck) GetRTP() float64 {
	if x != nil {
		return x.RTP
	}
	return 0
}

func (x *SpinAck) GetLID() int32 {
	if x != nil {
		return x.LID
	}
	return 0
}

func (x *SpinAck) GetRID() int32 {
	if x != nil {
		return x.RID
	}
	return 0
}

var File_tmp_proto protoreflect.FileDescriptor

const file_tmp_proto_rawDesc = "" +
	"\n" +
	"\ttmp.proto\x12\amessage\"\x1a\n" +
	"\x06Column\x12\x10\n" +
	"\x03Row\x18\x01 \x03(\x05R\x03Row\"K\n" +
	"\tAwardData\x12\x16\n" +
	"\x06Symbol\x18\x01 \x01(\x05R\x06Symbol\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x05R\x05Count\x12\x10\n" +
	"\x03Win\x18\x03 \x01(\x01R\x03Win\"\x88\x02\n" +
	"\vSinglePlate\x12'\n" +
	"\x06Symbol\x18\x01 \x03(\v2\x0f.message.ColumnR\x06Symbol\x12\x1d\n" +
	"\n" +
	"Single_win\x18\x02 \x01(\x01R\tSingleWin\x128\n" +
	"\x0eAward_data_vec\x18\x03 \x03(\v2\x12.message.AwardDataR\fAwardDataVec\x12!\n" +
	"\fCrystal_type\x18\x04 \x01(\x05R\vCrystalType\x12%\n" +
	"\x0eNeed_eliminate\x18\x05 \x01(\bR\rNeedEliminate\x12-\n" +
	"\tEliminate\x18\x06 \x03(\v2\x0f.message.ColumnR\tEliminate\"\x95\x03\n" +
	"\tRoundInfo\x125\n" +
	"\vPlate_queue\x18\x01 \x03(\v2\x14.message.SinglePlateR\n" +
	"PlateQueue\x12\x1b\n" +
	"\tRound_win\x18\x02 \x01(\x01R\bRoundWin\x12$\n" +
	"\x0eRound_mul_show\x18\x03 \x03(\x01R\fRoundMulShow\x12\x1b\n" +
	"\tRound_mul\x18\x04 \x01(\x01R\bRoundMul\x12'\n" +
	"\x0fEliminate_count\x18\x05 \x01(\x05R\x0eEliminateCount\x12&\n" +
	"\x0fAward_type_flag\x18\x06 \x01(\x05R\rAwardTypeFlag\x12#\n" +
	"\rScatter_count\x18\a \x01(\x05R\fScatterCount\x12\x1f\n" +
	"\vScatter_win\x18\b \x01(\x01R\n" +
	"ScatterWin\x12\x19\n" +
	"\bGet_free\x18\t \x01(\bR\aGetFree\x12$\n" +
	"\x0eGet_free_round\x18\n" +
	" \x01(\x05R\fGetFreeRound\x12\x19\n" +
	"\bMax_flag\x18\v \x01(\bR\aMaxFlag\"c\n" +
	"\bFreeData\x121\n" +
	"\n" +
	"Free_queue\x18\x01 \x03(\v2\x12.message.RoundInfoR\tFreeQueue\x12$\n" +
	"\x0eFree_total_win\x18\x02 \x01(\x01R\fFreeTotalWin\"\x97\x02\n" +
	"\aSpinAck\x12/\n" +
	"\tMain_game\x18\x01 \x01(\v2\x12.message.RoundInfoR\bMainGame\x12.\n" +
	"\tFree_game\x18\x02 \x01(\v2\x11.message.FreeDataR\bFreeGame\x12\x1b\n" +
	"\tTotal_win\x18\x03 \x01(\x01R\bTotalWin\x12\x1d\n" +
	"\n" +
	"Show_index\x18\x04 \x01(\tR\tShowIndex\x12\x1b\n" +
	"\tNow_money\x18\x05 \x01(\x01R\bNowMoney\x12\x19\n" +
	"\bAck_type\x18\x06 \x01(\x05R\aAckType\x12\x11\n" +
	"\x04RT_p\x18\a \x01(\x01R\x03RTP\x12\x11\n" +
	"\x04LI_d\x18\b \x01(\x05R\x03LID\x12\x11\n" +
	"\x04RI_d\x18\t \x01(\x05R\x03RIDB*Z(serve/servicejili/jili_226_witch/messageb\x06proto3"

var (
	file_tmp_proto_rawDescOnce sync.Once
	file_tmp_proto_rawDescData []byte
)

func file_tmp_proto_rawDescGZIP() []byte {
	file_tmp_proto_rawDescOnce.Do(func() {
		file_tmp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tmp_proto_rawDesc), len(file_tmp_proto_rawDesc)))
	})
	return file_tmp_proto_rawDescData
}

var file_tmp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tmp_proto_goTypes = []any{
	(*Column)(nil),      // 0: message.Column
	(*AwardData)(nil),   // 1: message.AwardData
	(*SinglePlate)(nil), // 2: message.SinglePlate
	(*RoundInfo)(nil),   // 3: message.RoundInfo
	(*FreeData)(nil),    // 4: message.FreeData
	(*SpinAck)(nil),     // 5: message.SpinAck
}
var file_tmp_proto_depIdxs = []int32{
	0, // 0: message.SinglePlate.Symbol:type_name -> message.Column
	1, // 1: message.SinglePlate.Award_data_vec:type_name -> message.AwardData
	0, // 2: message.SinglePlate.Eliminate:type_name -> message.Column
	2, // 3: message.RoundInfo.Plate_queue:type_name -> message.SinglePlate
	3, // 4: message.FreeData.Free_queue:type_name -> message.RoundInfo
	3, // 5: message.SpinAck.Main_game:type_name -> message.RoundInfo
	4, // 6: message.SpinAck.Free_game:type_name -> message.FreeData
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_tmp_proto_init() }
func file_tmp_proto_init() {
	if File_tmp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tmp_proto_rawDesc), len(file_tmp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tmp_proto_goTypes,
		DependencyIndexes: file_tmp_proto_depIdxs,
		MessageInfos:      file_tmp_proto_msgTypes,
	}.Build()
	File_tmp_proto = out.File
	file_tmp_proto_goTypes = nil
	file_tmp_proto_depIdxs = nil
}
