package jilicomm

var ChangeGameMap = map[string]string{
	"csh":       "jili_2_csh",
	"tks":       "jili_4_tks",
	"chilli":    "jili_5_chilli",
	"luckytree": "jili_6_luckytree",
	"kk2":       "jili_16_kk2",
	"bbc":       "jili_36_bbc",
	"ols3":      "jili_40_ols3",
	"fivestar":  "jili_44_fivestar",
	"cbt":       "jili_45_cbt",
	//"nightclub": "jili_76_nightclub",
	"mw": "jili_85_mw",
	//"sr":        "jili_100_sr",
	"rs2":  "jili_102_rs2",
	"aa":   "jili_115_aa",
	"taxi": "jili_116_taxi",
	"me":   "jili_135_me",
	"ge":   "jili_137_ge",
	"ln":   "jili_145_ln",
	"cny":  "jili_176_cny",
	//"phoenix":   "jili_208_phoenix",
	"ctk": "jili_225_ctk",
	"cts": "jili_230_cts",
	"bby": "jili_238_bby",
	"dbg": "jili_239_dbg",
	"mp2": "jili_303_mp2",
}

var ChangeGameMap2 = map[string]string{
	"jili_2_csh":       "csh",
	"jili_4_tks":       "tks",
	"jili_5_chilli":    "chilli",
	"jili_6_luckytree": "luckytree",
	"jili_16_kk2":      "kk2",
	"jili_36_bbc":      "bbc",
	"jili_40_ols3":     "ols3",
	"jili_44_fivestar": "fivestar",
	"jili_45_cbt":      "cbt",
	//"jili_76_nightclub": "nightclub",
	"jili_85_mw": "mw",
	//"jili_100_sr":       "sr",
	"jili_102_rs2":  "rs2",
	"jili_115_aa":   "aa",
	"jili_116_taxi": "taxi",
	"jili_135_me":   "me",
	"jili_137_ge":   "ge",
	"jili_145_ln":   "ln",
	"jili_176_cny":  "cny",
	//"jili_208_phoenix":  "phoenix",
	"jili_225_ctk": "ctk",
	"jili_230_cts": "cts",
	"jili_238_bby": "bby",
	"jili_239_dbg": "dbg",
	"jili_303_mp2": "mp2",
}

var ChangeGameMap3 = map[string]string{
	"gq": "jili_58_gq",
	//"bog":   "jili_87_bog",
	"samba": "jili_136_samba",
	"bh":    "jili_142_bh",
	"cai":   "jili_144_cai",
	"fb":    "jili_146_fb",
	"utaxi": "jili_166_utaxi",
}

var ChangeGameMap33 = map[string]string{
	"jili_58_gq": "gq",
	//"jili_87_bog":    "bog",
	"jili_136_samba": "samba",
	"jili_142_bh":    "bh",
	"jili_144_cai":   "cai",
	"jili_146_fb":    "fb",
	"jili_166_utaxi": "utaxi",
}

var ChangeGameMap4 = map[string]string{
	"mc":          "jili_51_mc",
	"mcp":         "jili_302_mcp",
	"wondershow":  "jili_13_wondershow",
	"starburst":   "jili_14_starburst",
	"sweetheart":  "jili_17_sweetheart",
	"sweetheart3": "jili_26_sweetheart3",
	"pp":          "jili_33_pp",
	"xiyangyang":  "jili_43_xiyangyang",
	"mp":          "jili_67_mp",
	"rxmw":        "jili_517_rxmw",
	"twinwins":    "jili_106_twinwins",
	"bog":         "jili_87_bog",
	"pirate":      "jili_164_pirate",
	"sl":          "jili_198_sl",
	"sc":          "jili_171_sc",
	"bfs2":        "jili_259_bfs2",
	"witch":       "jili_226_witch",
	"fullhouse3":  "jili_403_fullhouse3",
	"tct":         "jili_399_tct",
	"tlp":         "jili_400_tlp",
	"psd":         "jili_375_psd",
	"dts":         "jili_372_dts",
	"mpt":         "jili_379_mpt",
	"ed":          "jili_324_ed",
	"samurai":     "jili_376_samurai",
	"loe":         "jili_180_loe",
	"lj":          "jili_421_lj",
	"jpj":         "jili_301_jpj",
}

var ChangeGameMap44 = map[string]string{
	"jili_51_mc":          "mc",
	"jili_302_mcp":        "mcp",
	"jili_13_wondershow":  "wondershow",
	"jili_14_starburst":   "starburst",
	"jili_17_sweetheart":  "sweetheart",
	"jili_26_sweetheart3": "sweetheart3",
	"jili_33_pp":          "pp",
	"jili_43_xiyangyang":  "xiyangyang",
	"jili_67_mp":          "mp",
	"jili_517_rxmw":       "rxmw",
	"jili_106_twinwins":   "twinwins",
	"jili_87_bog":         "bog",
	"jili_164_pirate":     "pirate",
	"jili_198_sl":         "sl",
	"jili_171_sc":         "sc",
	"jili_259_bfs2":       "bfs2",
	"jili_226_witch":      "witch",
	"jili_403_fullhouse3": "fullhouse3",
	"jili_399_tct":        "tct",
	"jili_400_tlp":        "tlp",
	"jili_375_psd":        "psd",
	"jili_372_dts":        "dts",
	"jili_379_mpt":        "mpt",
	"jili_324_ed":         "ed",
	"jili_376_samurai":    "samurai",
	"jili_180_loe":        "loe",
	"jili_421_lj":         "lj",
	"jili_301_jpj":        "jpj",
}

var AllChangeGameNameMap = map[string]string{
	"jili_2_csh":        "csh",
	"jili_4_tks":        "tks",
	"jili_5_chilli":     "chilli",
	"jili_6_luckytree":  "luckytree",
	"jili_16_kk2":       "kk2",
	"jili_36_bbc":       "bbc",
	"jili_40_ols3":      "ols3",
	"jili_44_fivestar":  "fivestar",
	"jili_45_cbt":       "cbt",
	"jili_76_nightclub": "nightclub",
	"jili_85_mw":        "mw",
	"jili_100_sr":       "sr",
	"jili_102_rs2":      "rs2",
	"jili_115_aa":       "aa",
	"jili_116_taxi":     "taxi",
	"jili_135_me":       "me",
	"jili_137_ge":       "ge",
	"jili_145_ln":       "ln",
	"jili_176_cny":      "cny",
	//"jili_208_phoenix":  "phoenix",
	"jili_225_ctk": "ctk",
	"jili_230_cts": "cts",
	"jili_238_bby": "bby",
	"jili_239_dbg": "dbg",
	"jili_303_mp2": "mp2",

	"jili_58_gq":     "gq",
	"jili_87_bog":    "bog",
	"jili_136_samba": "samba",
	"jili_142_bh":    "bh",
	"jili_144_cai":   "cai",
	"jili_146_fb":    "fb",
	"jili_166_utaxi": "utaxi",

	"jili_51_mc":          "mc",
	"jili_302_mcp":        "mcp",
	"jili_13_wondershow":  "wondershow",
	"jili_14_starburst":   "starburst",
	"jili_17_sweetheart":  "sweetheart",
	"jili_26_sweetheart3": "sweetheart3",
	"jili_33_pp":          "pp",
	"jili_43_xiyangyang":  "xiyangyang",
	"jili_67_mp":          "mp",
	"jili_517_rxmw":       "rxmw",
	"jili_106_twinwins":   "twinwins",

	"jili_164_pirate":     "pirate",
	"jili_198_sl":         "sl",
	"jili_171_sc":         "sc",
	"jili_259_bfs2":       "bfs2",
	"jili_226_witch":      "witch",
	"jili_403_fullhouse3": "fullhouse3",
	"jili_399_tct":        "tct",
	"jili_400_tlp":        "tlp",
	"jili_375_psd":        "psd",
	"jili_372_dts":        "dts",
	"jili_379_mpt":        "mpt",
	"jili_324_ed":         "ed",
	"jili_376_samurai":    "samurai",
	"jili_180_loe":        "loe",
	"jili_421_lj":         "lj",
	"jili_301_jpj":        "jpj",
}

var AllChangeGameMap = map[string]string{
	"csh":       "jili_2_csh",
	"tks":       "jili_4_tks",
	"chilli":    "jili_5_chilli",
	"luckytree": "jili_6_luckytree",
	"kk2":       "jili_16_kk2",
	"bbc":       "jili_36_bbc",
	"ols3":      "jili_40_ols3",
	"fivestar":  "jili_44_fivestar",
	"cbt":       "jili_45_cbt",
	"nightclub": "jili_76_nightclub",
	"mw":        "jili_85_mw",
	"sr":        "jili_100_sr",
	"rs2":       "jili_102_rs2",
	"aa":        "jili_115_aa",
	"taxi":      "jili_116_taxi",
	"me":        "jili_135_me",
	"ge":        "jili_137_ge",
	"ln":        "jili_145_ln",
	"cny":       "jili_176_cny",
	//"phoenix":   "jili_208_phoenix",
	"ctk": "jili_225_ctk",
	"cts": "jili_230_cts",
	"bby": "jili_238_bby",
	"dbg": "jili_239_dbg",
	"mp2": "jili_303_mp2",

	"gq": "jili_58_gq",

	"samba": "jili_136_samba",
	"bh":    "jili_142_bh",
	"cai":   "jili_144_cai",
	"fb":    "jili_146_fb",
	"utaxi": "jili_166_utaxi",

	"mc":          "jili_51_mc",
	"mcp":         "jili_302_mcp",
	"wondershow":  "jili_13_wondershow",
	"starburst":   "jili_14_starburst",
	"sweetheart":  "jili_17_sweetheart",
	"sweetheart3": "jili_26_sweetheart3",
	"pp":          "jili_33_pp",
	"xiyangyang":  "jili_43_xiyangyang",
	"mp":          "jili_67_mp",
	"rxmw":        "jili_517_rxmw",
	"twinwins":    "jili_106_twinwins",
	"bog":         "jili_87_bog",
	"pirate":      "jili_164_pirate",
	"sl":          "jili_198_sl",
	"sc":          "jili_171_sc",
	"bfs2":        "jili_259_bfs2",
	"witch":       "jili_226_witch",
	"fullhouse3":  "jili_403_fullhouse3",
	"tct":         "jili_399_tct",
	"tlp":         "jili_400_tlp",
	"psd":         "jili_375_psd",
	"dts":         "jili_372_dts",
	"mpt":         "jili_379_mpt",
	"ed":          "jili_324_ed",
	"samurai":     "jili_376_samurai",
	"loe":         "jili_180_loe",
	"lj":          "jili_421_lj",
	"jpj":         "jili_301_jpj",
}
