// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pb/stats/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminStatsRpcClient is the client API for AdminStatsRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminStatsRpcClient interface {
	GetLast10DayRunTimeData(ctx context.Context, in *GetLast10DayRunTimeDataReq, opts ...grpc.CallOption) (*JsonData, error)
	// 获取最近n天的总流水与总产出
	GetTotalExpense(ctx context.Context, in *GetTotalExpenseReq, opts ...grpc.CallOption) (*GetTotalExpenseResp, error)
}

type adminStatsRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminStatsRpcClient(cc grpc.ClientConnInterface) AdminStatsRpcClient {
	return &adminStatsRpcClient{cc}
}

func (c *adminStatsRpcClient) GetLast10DayRunTimeData(ctx context.Context, in *GetLast10DayRunTimeDataReq, opts ...grpc.CallOption) (*JsonData, error) {
	out := new(JsonData)
	err := c.cc.Invoke(ctx, "/stats.AdminStatsRpc/GetLast10DayRunTimeData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminStatsRpcClient) GetTotalExpense(ctx context.Context, in *GetTotalExpenseReq, opts ...grpc.CallOption) (*GetTotalExpenseResp, error) {
	out := new(GetTotalExpenseResp)
	err := c.cc.Invoke(ctx, "/stats.AdminStatsRpc/GetTotalExpense", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminStatsRpcServer is the server API for AdminStatsRpc service.
// All implementations should embed UnimplementedAdminStatsRpcServer
// for forward compatibility
type AdminStatsRpcServer interface {
	GetLast10DayRunTimeData(context.Context, *GetLast10DayRunTimeDataReq) (*JsonData, error)
	// 获取最近n天的总流水与总产出
	GetTotalExpense(context.Context, *GetTotalExpenseReq) (*GetTotalExpenseResp, error)
}

// UnimplementedAdminStatsRpcServer should be embedded to have forward compatible implementations.
type UnimplementedAdminStatsRpcServer struct {
}

func (UnimplementedAdminStatsRpcServer) GetLast10DayRunTimeData(context.Context, *GetLast10DayRunTimeDataReq) (*JsonData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLast10DayRunTimeData not implemented")
}
func (UnimplementedAdminStatsRpcServer) GetTotalExpense(context.Context, *GetTotalExpenseReq) (*GetTotalExpenseResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalExpense not implemented")
}

// UnsafeAdminStatsRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminStatsRpcServer will
// result in compilation errors.
type UnsafeAdminStatsRpcServer interface {
	mustEmbedUnimplementedAdminStatsRpcServer()
}

func RegisterAdminStatsRpcServer(s grpc.ServiceRegistrar, srv AdminStatsRpcServer) {
	s.RegisterService(&AdminStatsRpc_ServiceDesc, srv)
}

func _AdminStatsRpc_GetLast10DayRunTimeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLast10DayRunTimeDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminStatsRpcServer).GetLast10DayRunTimeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.AdminStatsRpc/GetLast10DayRunTimeData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminStatsRpcServer).GetLast10DayRunTimeData(ctx, req.(*GetLast10DayRunTimeDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminStatsRpc_GetTotalExpense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalExpenseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminStatsRpcServer).GetTotalExpense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stats.AdminStatsRpc/GetTotalExpense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminStatsRpcServer).GetTotalExpense(ctx, req.(*GetTotalExpenseReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminStatsRpc_ServiceDesc is the grpc.ServiceDesc for AdminStatsRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminStatsRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.AdminStatsRpc",
	HandlerType: (*AdminStatsRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLast10DayRunTimeData",
			Handler:    _AdminStatsRpc_GetLast10DayRunTimeData_Handler,
		},
		{
			MethodName: "GetTotalExpense",
			Handler:    _AdminStatsRpc_GetTotalExpense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/stats/stats.proto",
}
