// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: pb/mail.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Error Status = 0
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Error",
	}
	Status_value = map[string]int32{
		"Error": 0,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_mail_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pb_mail_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_mail_proto_rawDescGZIP(), []int{0}
}

type SubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid int64 `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid"` // PID
}

func (x *SubMessage) Reset() {
	*x = SubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMessage) ProtoMessage() {}

func (x *SubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMessage.ProtoReflect.Descriptor instead.
func (*SubMessage) Descriptor() ([]byte, []int) {
	return file_pb_mail_proto_rawDescGZIP(), []int{0}
}

func (x *SubMessage) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type SendMailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid     int64       `protobuf:"varint,1,opt,name=Pid,proto3" json:"Pid"` // PID
	Title   string      `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title"`
	Content string      `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content"` // content
	Status  Status      `protobuf:"varint,4,opt,name=Status,proto3,enum=Status" json:"Status"`
	Sub     *SubMessage `protobuf:"bytes,5,opt,name=Sub,proto3" json:"Sub"`
}

func (x *SendMailReq) Reset() {
	*x = SendMailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailReq) ProtoMessage() {}

func (x *SendMailReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailReq.ProtoReflect.Descriptor instead.
func (*SendMailReq) Descriptor() ([]byte, []int) {
	return file_pb_mail_proto_rawDescGZIP(), []int{1}
}

func (x *SendMailReq) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SendMailReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendMailReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMailReq) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Error
}

func (x *SendMailReq) GetSub() *SubMessage {
	if x != nil {
		return x.Sub
	}
	return nil
}

type SendMailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendMailResp) Reset() {
	*x = SendMailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailResp) ProtoMessage() {}

func (x *SendMailResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailResp.ProtoReflect.Descriptor instead.
func (*SendMailResp) Descriptor() ([]byte, []int) {
	return file_pb_mail_proto_rawDescGZIP(), []int{2}
}

var File_pb_mail_proto protoreflect.FileDescriptor

var file_pb_mail_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x1e, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x69, 0x64, 0x22,
	0x8f, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1d, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x53, 0x75,
	0x62, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x2a, 0x13, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x32, 0x2f, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x27,
	0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x0c, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x62, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_mail_proto_rawDescOnce sync.Once
	file_pb_mail_proto_rawDescData = file_pb_mail_proto_rawDesc
)

func file_pb_mail_proto_rawDescGZIP() []byte {
	file_pb_mail_proto_rawDescOnce.Do(func() {
		file_pb_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_mail_proto_rawDescData)
	})
	return file_pb_mail_proto_rawDescData
}

var file_pb_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_mail_proto_goTypes = []interface{}{
	(Status)(0),          // 0: Status
	(*SubMessage)(nil),   // 1: SubMessage
	(*SendMailReq)(nil),  // 2: SendMailReq
	(*SendMailResp)(nil), // 3: SendMailResp
}
var file_pb_mail_proto_depIdxs = []int32{
	0, // 0: SendMailReq.Status:type_name -> Status
	1, // 1: SendMailReq.Sub:type_name -> SubMessage
	2, // 2: Mail.SendMail:input_type -> SendMailReq
	3, // 3: Mail.SendMail:output_type -> SendMailResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_mail_proto_init() }
func file_pb_mail_proto_init() {
	if File_pb_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_mail_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_mail_proto_goTypes,
		DependencyIndexes: file_pb_mail_proto_depIdxs,
		EnumInfos:         file_pb_mail_proto_enumTypes,
		MessageInfos:      file_pb_mail_proto_msgTypes,
	}.Build()
	File_pb_mail_proto = out.File
	file_pb_mail_proto_rawDesc = nil
	file_pb_mail_proto_goTypes = nil
	file_pb_mail_proto_depIdxs = nil
}
