package handlers

var loginLang_JILI = map[string]string{
	"en":   "en",
	"da":   "da",
	"de":   "de",
	"es":   "es",
	"fr":   "frFR",
	"id":   "id",
	"it":   "it",
	"ja":   "jp",
	"nl":   "nl",
	"no":   "en",
	"pl":   "en",
	"pt":   "pt",
	"ro":   "ro",
	"ru":   "ruRU",
	"sv":   "se",
	"th":   "th",
	"tr":   "trTR",
	"vi":   "vn",
	"my":   "mm",
	"in":   "hi",
	"ta":   "ta",
	"ms":   "ms",
	"bn":   "bn",
	"urIN": "en",
	"grGR": "grGR",
}
