// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: serve/service_fish/domain/fish/proto/fish.proto

package fish_proto

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	proto1 "serve/service_fish/models/proto"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RoundStart struct {
	Msgid    proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.fish.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
}

func (m *RoundStart) Reset()         { *m = RoundStart{} }
func (m *RoundStart) String() string { return proto.CompactTextString(m) }
func (*RoundStart) ProtoMessage()    {}
func (*RoundStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{0}
}
func (m *RoundStart) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoundStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoundStart.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RoundStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundStart.Merge(m, src)
}
func (m *RoundStart) XXX_Size() int {
	return m.Size()
}
func (m *RoundStart) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundStart.DiscardUnknown(m)
}

var xxx_messageInfo_RoundStart proto.InternalMessageInfo

func (m *RoundStart) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *RoundStart) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

type RoundEnd struct {
	Msgid     proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.fish.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid  string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	NextScene int32         `protobuf:"varint,3,opt,name=next_scene,json=nextScene,proto3" json:"next_scene,omitempty"`
}

func (m *RoundEnd) Reset()         { *m = RoundEnd{} }
func (m *RoundEnd) String() string { return proto.CompactTextString(m) }
func (*RoundEnd) ProtoMessage()    {}
func (*RoundEnd) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{1}
}
func (m *RoundEnd) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RoundEnd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RoundEnd.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RoundEnd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundEnd.Merge(m, src)
}
func (m *RoundEnd) XXX_Size() int {
	return m.Size()
}
func (m *RoundEnd) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundEnd.DiscardUnknown(m)
}

var xxx_messageInfo_RoundEnd proto.InternalMessageInfo

func (m *RoundEnd) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *RoundEnd) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *RoundEnd) GetNextScene() int32 {
	if m != nil {
		return m.NextScene
	}
	return 0
}

type BezierInfo struct {
	Time       int32             `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	StartPoint *BezierInfo_Point `protobuf:"bytes,2,opt,name=start_point,json=startPoint,proto3" json:"start_point,omitempty"`
	EndPoint   *BezierInfo_Point `protobuf:"bytes,3,opt,name=end_point,json=endPoint,proto3" json:"end_point,omitempty"`
	Op1Point   *BezierInfo_Point `protobuf:"bytes,4,opt,name=op1_point,json=op1Point,proto3" json:"op1_point,omitempty"`
	Op2Point   *BezierInfo_Point `protobuf:"bytes,5,opt,name=op2_point,json=op2Point,proto3" json:"op2_point,omitempty"`
}

func (m *BezierInfo) Reset()         { *m = BezierInfo{} }
func (m *BezierInfo) String() string { return proto.CompactTextString(m) }
func (*BezierInfo) ProtoMessage()    {}
func (*BezierInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{2}
}
func (m *BezierInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BezierInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BezierInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BezierInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BezierInfo.Merge(m, src)
}
func (m *BezierInfo) XXX_Size() int {
	return m.Size()
}
func (m *BezierInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BezierInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BezierInfo proto.InternalMessageInfo

func (m *BezierInfo) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BezierInfo) GetStartPoint() *BezierInfo_Point {
	if m != nil {
		return m.StartPoint
	}
	return nil
}

func (m *BezierInfo) GetEndPoint() *BezierInfo_Point {
	if m != nil {
		return m.EndPoint
	}
	return nil
}

func (m *BezierInfo) GetOp1Point() *BezierInfo_Point {
	if m != nil {
		return m.Op1Point
	}
	return nil
}

func (m *BezierInfo) GetOp2Point() *BezierInfo_Point {
	if m != nil {
		return m.Op2Point
	}
	return nil
}

type BezierInfo_Point struct {
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (m *BezierInfo_Point) Reset()         { *m = BezierInfo_Point{} }
func (m *BezierInfo_Point) String() string { return proto.CompactTextString(m) }
func (*BezierInfo_Point) ProtoMessage()    {}
func (*BezierInfo_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{2, 0}
}
func (m *BezierInfo_Point) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BezierInfo_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BezierInfo_Point.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BezierInfo_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BezierInfo_Point.Merge(m, src)
}
func (m *BezierInfo_Point) XXX_Size() int {
	return m.Size()
}
func (m *BezierInfo_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_BezierInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_BezierInfo_Point proto.InternalMessageInfo

func (m *BezierInfo_Point) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BezierInfo_Point) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type BroadcastFishIn struct {
	Msgid    proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.fish.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	Fish     *FishInfo     `protobuf:"bytes,3,opt,name=fish,proto3" json:"fish,omitempty"`
}

func (m *BroadcastFishIn) Reset()         { *m = BroadcastFishIn{} }
func (m *BroadcastFishIn) String() string { return proto.CompactTextString(m) }
func (*BroadcastFishIn) ProtoMessage()    {}
func (*BroadcastFishIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{3}
}
func (m *BroadcastFishIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BroadcastFishIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BroadcastFishIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BroadcastFishIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastFishIn.Merge(m, src)
}
func (m *BroadcastFishIn) XXX_Size() int {
	return m.Size()
}
func (m *BroadcastFishIn) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastFishIn.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastFishIn proto.InternalMessageInfo

func (m *BroadcastFishIn) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *BroadcastFishIn) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *BroadcastFishIn) GetFish() *FishInfo {
	if m != nil {
		return m.Fish
	}
	return nil
}

type BroadcastFishOut struct {
	Msgid    proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.fish.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	Uuid     string        `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type     int32         `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (m *BroadcastFishOut) Reset()         { *m = BroadcastFishOut{} }
func (m *BroadcastFishOut) String() string { return proto.CompactTextString(m) }
func (*BroadcastFishOut) ProtoMessage()    {}
func (*BroadcastFishOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{4}
}
func (m *BroadcastFishOut) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BroadcastFishOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BroadcastFishOut.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BroadcastFishOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastFishOut.Merge(m, src)
}
func (m *BroadcastFishOut) XXX_Size() int {
	return m.Size()
}
func (m *BroadcastFishOut) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastFishOut.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastFishOut proto.InternalMessageInfo

func (m *BroadcastFishOut) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *BroadcastFishOut) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *BroadcastFishOut) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BroadcastFishOut) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type BroadcastGroupIn struct {
	Msgid     proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.fish.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid  string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	GroupFish []*FishInfo   `protobuf:"bytes,3,rep,name=group_fish,json=groupFish,proto3" json:"group_fish,omitempty"`
}

func (m *BroadcastGroupIn) Reset()         { *m = BroadcastGroupIn{} }
func (m *BroadcastGroupIn) String() string { return proto.CompactTextString(m) }
func (*BroadcastGroupIn) ProtoMessage()    {}
func (*BroadcastGroupIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{5}
}
func (m *BroadcastGroupIn) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BroadcastGroupIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BroadcastGroupIn.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BroadcastGroupIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastGroupIn.Merge(m, src)
}
func (m *BroadcastGroupIn) XXX_Size() int {
	return m.Size()
}
func (m *BroadcastGroupIn) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastGroupIn.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastGroupIn proto.InternalMessageInfo

func (m *BroadcastGroupIn) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *BroadcastGroupIn) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *BroadcastGroupIn) GetGroupFish() []*FishInfo {
	if m != nil {
		return m.GroupFish
	}
	return nil
}

type AllFishCall struct {
	Msgid    proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.fish.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
}

func (m *AllFishCall) Reset()         { *m = AllFishCall{} }
func (m *AllFishCall) String() string { return proto.CompactTextString(m) }
func (*AllFishCall) ProtoMessage()    {}
func (*AllFishCall) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{6}
}
func (m *AllFishCall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllFishCall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllFishCall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllFishCall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllFishCall.Merge(m, src)
}
func (m *AllFishCall) XXX_Size() int {
	return m.Size()
}
func (m *AllFishCall) XXX_DiscardUnknown() {
	xxx_messageInfo_AllFishCall.DiscardUnknown(m)
}

var xxx_messageInfo_AllFishCall proto.InternalMessageInfo

func (m *AllFishCall) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *AllFishCall) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

type AllFishRecall struct {
	Msgid    proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.fish.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	AllFish  []*FishInfo   `protobuf:"bytes,3,rep,name=all_fish,json=allFish,proto3" json:"all_fish,omitempty"`
}

func (m *AllFishRecall) Reset()         { *m = AllFishRecall{} }
func (m *AllFishRecall) String() string { return proto.CompactTextString(m) }
func (*AllFishRecall) ProtoMessage()    {}
func (*AllFishRecall) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{7}
}
func (m *AllFishRecall) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllFishRecall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllFishRecall.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllFishRecall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllFishRecall.Merge(m, src)
}
func (m *AllFishRecall) XXX_Size() int {
	return m.Size()
}
func (m *AllFishRecall) XXX_DiscardUnknown() {
	xxx_messageInfo_AllFishRecall.DiscardUnknown(m)
}

var xxx_messageInfo_AllFishRecall proto.InternalMessageInfo

func (m *AllFishRecall) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *AllFishRecall) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *AllFishRecall) GetAllFish() []*FishInfo {
	if m != nil {
		return m.AllFish
	}
	return nil
}

type FishInfo struct {
	Uuid        string        `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SymbolId    int32         `protobuf:"varint,2,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
	Life        int32         `protobuf:"varint,3,opt,name=life,proto3" json:"life,omitempty"`
	ElapsedTime int64         `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	Path        []*BezierInfo `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	RtpId       string        `protobuf:"bytes,6,opt,name=rtpId,proto3" json:"rtpId,omitempty"`
	Group       *GroupInfo    `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
}

func (m *FishInfo) Reset()         { *m = FishInfo{} }
func (m *FishInfo) String() string { return proto.CompactTextString(m) }
func (*FishInfo) ProtoMessage()    {}
func (*FishInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{8}
}
func (m *FishInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FishInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FishInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FishInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FishInfo.Merge(m, src)
}
func (m *FishInfo) XXX_Size() int {
	return m.Size()
}
func (m *FishInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FishInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FishInfo proto.InternalMessageInfo

func (m *FishInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *FishInfo) GetSymbolId() int32 {
	if m != nil {
		return m.SymbolId
	}
	return 0
}

func (m *FishInfo) GetLife() int32 {
	if m != nil {
		return m.Life
	}
	return 0
}

func (m *FishInfo) GetElapsedTime() int64 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

func (m *FishInfo) GetPath() []*BezierInfo {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *FishInfo) GetRtpId() string {
	if m != nil {
		return m.RtpId
	}
	return ""
}

func (m *FishInfo) GetGroup() *GroupInfo {
	if m != nil {
		return m.Group
	}
	return nil
}

type BroadcastFishChange struct {
	Msgid    proto1.EMSGID `protobuf:"varint,1,opt,name=msgid,proto3,enum=common.fish.proto.EMSGID" json:"msgid,omitempty"`
	RoomUuid string        `protobuf:"bytes,2,opt,name=room_uuid,json=roomUuid,proto3" json:"room_uuid,omitempty"`
	Uuid     string        `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SymbolId int32         `protobuf:"varint,4,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
}

func (m *BroadcastFishChange) Reset()         { *m = BroadcastFishChange{} }
func (m *BroadcastFishChange) String() string { return proto.CompactTextString(m) }
func (*BroadcastFishChange) ProtoMessage()    {}
func (*BroadcastFishChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{9}
}
func (m *BroadcastFishChange) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BroadcastFishChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BroadcastFishChange.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BroadcastFishChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastFishChange.Merge(m, src)
}
func (m *BroadcastFishChange) XXX_Size() int {
	return m.Size()
}
func (m *BroadcastFishChange) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastFishChange.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastFishChange proto.InternalMessageInfo

func (m *BroadcastFishChange) GetMsgid() proto1.EMSGID {
	if m != nil {
		return m.Msgid
	}
	return proto1.EMSGID_eReserved
}

func (m *BroadcastFishChange) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *BroadcastFishChange) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *BroadcastFishChange) GetSymbolId() int32 {
	if m != nil {
		return m.SymbolId
	}
	return 0
}

type GroupInfo struct {
	Uuid       string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Separation int32  `protobuf:"varint,2,opt,name=separation,proto3" json:"separation,omitempty"`
}

func (m *GroupInfo) Reset()         { *m = GroupInfo{} }
func (m *GroupInfo) String() string { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()    {}
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5df235dae702271, []int{10}
}
func (m *GroupInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GroupInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInfo.Merge(m, src)
}
func (m *GroupInfo) XXX_Size() int {
	return m.Size()
}
func (m *GroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInfo proto.InternalMessageInfo

func (m *GroupInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GroupInfo) GetSeparation() int32 {
	if m != nil {
		return m.Separation
	}
	return 0
}

func init() {
	proto.RegisterType((*RoundStart)(nil), "fish.proto.RoundStart")
	proto.RegisterType((*RoundEnd)(nil), "fish.proto.RoundEnd")
	proto.RegisterType((*BezierInfo)(nil), "fish.proto.BezierInfo")
	proto.RegisterType((*BezierInfo_Point)(nil), "fish.proto.BezierInfo.Point")
	proto.RegisterType((*BroadcastFishIn)(nil), "fish.proto.BroadcastFishIn")
	proto.RegisterType((*BroadcastFishOut)(nil), "fish.proto.BroadcastFishOut")
	proto.RegisterType((*BroadcastGroupIn)(nil), "fish.proto.BroadcastGroupIn")
	proto.RegisterType((*AllFishCall)(nil), "fish.proto.AllFishCall")
	proto.RegisterType((*AllFishRecall)(nil), "fish.proto.AllFishRecall")
	proto.RegisterType((*FishInfo)(nil), "fish.proto.FishInfo")
	proto.RegisterType((*BroadcastFishChange)(nil), "fish.proto.BroadcastFishChange")
	proto.RegisterType((*GroupInfo)(nil), "fish.proto.GroupInfo")
}

func init() {
	proto.RegisterFile("serve/service_fish/domain/fish/proto/fish.proto", fileDescriptor_e5df235dae702271)
}

var fileDescriptor_e5df235dae702271 = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xed, 0x36, 0x71, 0x1b, 0x4f, 0xca, 0x87, 0x4c, 0x41, 0xa6, 0x05, 0xab, 0x98, 0x4b, 0x04,
	0x6a, 0xa2, 0xa6, 0x27, 0x0e, 0x08, 0xd1, 0x52, 0xaa, 0x1c, 0x10, 0x68, 0x0b, 0x17, 0x38, 0x58,
	0xdb, 0xec, 0x26, 0xb1, 0x64, 0xef, 0x5a, 0xb6, 0x03, 0x0d, 0xbf, 0x00, 0x2e, 0x88, 0x03, 0xfc,
	0x14, 0xfe, 0x03, 0xc7, 0x1e, 0x39, 0x42, 0xfb, 0x47, 0xd0, 0x8e, 0xb7, 0x8d, 0x23, 0x8a, 0xc8,
	0xc1, 0xe2, 0xf6, 0xfc, 0x34, 0xef, 0xed, 0xec, 0x9b, 0xf1, 0xc2, 0xe6, 0x20, 0xcc, 0x46, 0x9b,
	0x43, 0x16, 0x8b, 0xcd, 0x4c, 0xa4, 0x6f, 0x45, 0xda, 0xe1, 0x2a, 0x66, 0xa1, 0xec, 0x68, 0xbe,
	0x93, 0xa4, 0x2a, 0x57, 0x08, 0xdb, 0x08, 0x1d, 0x98, 0xe2, 0xb5, 0xce, 0x1f, 0xd2, 0x58, 0x71,
	0x11, 0x65, 0x46, 0xd5, 0x57, 0x71, 0xac, 0x64, 0x30, 0x15, 0xf8, 0xaf, 0x01, 0xa8, 0x1a, 0x4b,
	0x7e, 0x90, 0xb3, 0x34, 0x77, 0x3a, 0x60, 0xc5, 0xd9, 0x30, 0xe4, 0x2e, 0xd9, 0x20, 0xad, 0xcb,
	0xdd, 0x9b, 0xed, 0x42, 0xd0, 0x9e, 0x0a, 0xda, 0x7b, 0xcf, 0x0e, 0xf6, 0x7b, 0x4f, 0x68, 0x51,
	0xe7, 0xac, 0x83, 0x9d, 0x2a, 0x15, 0x07, 0xe3, 0x71, 0xc8, 0xdd, 0xc5, 0x0d, 0xd2, 0xb2, 0x69,
	0x43, 0x13, 0xaf, 0xc6, 0x21, 0xf7, 0xdf, 0x41, 0x03, 0xbd, 0xf7, 0x24, 0xaf, 0xd6, 0xd9, 0xb9,
	0x0d, 0x20, 0xc5, 0x51, 0x1e, 0x64, 0x7d, 0x21, 0x85, 0x5b, 0xdb, 0x20, 0x2d, 0x8b, 0xda, 0x9a,
	0x39, 0xd0, 0x84, 0xff, 0x6d, 0x11, 0x60, 0x47, 0xbc, 0x0f, 0x45, 0xda, 0x93, 0x03, 0xe5, 0x38,
	0x50, 0xcf, 0xc3, 0x58, 0xe0, 0xd1, 0x16, 0x45, 0xec, 0x3c, 0x84, 0x66, 0xa6, 0xaf, 0x1c, 0x24,
	0x2a, 0x94, 0x39, 0x1e, 0xd0, 0xec, 0xde, 0x2a, 0xb7, 0x33, 0x35, 0x68, 0xbf, 0xd0, 0x35, 0x14,
	0x50, 0x80, 0xd8, 0x79, 0x00, 0xb6, 0x90, 0xdc, 0x88, 0x6b, 0x73, 0x88, 0x1b, 0x42, 0xf2, 0x73,
	0xa9, 0x4a, 0xb6, 0x8c, 0xb4, 0x3e, 0x8f, 0x54, 0x25, 0x5b, 0x25, 0x69, 0xd7, 0x48, 0xad, 0xf9,
	0xa4, 0x5d, 0x44, 0x6b, 0x77, 0xc1, 0x2a, 0x3c, 0x56, 0x80, 0x1c, 0x99, 0x24, 0xc8, 0x91, 0xfe,
	0x9a, 0xe0, 0xe5, 0x2d, 0x4a, 0x26, 0xfe, 0x47, 0x02, 0x57, 0x76, 0x52, 0xc5, 0x78, 0x9f, 0x65,
	0xf9, 0xd3, 0x30, 0x1b, 0xf5, 0x64, 0xc5, 0x83, 0x6b, 0x41, 0x5d, 0x0b, 0x4d, 0x64, 0xab, 0x65,
	0x97, 0xe2, 0xbc, 0x81, 0xa2, 0x58, 0xe1, 0x7f, 0x20, 0x70, 0x75, 0xa6, 0x97, 0xe7, 0xe3, 0x8a,
	0xf7, 0x53, 0xef, 0x05, 0xf2, 0x35, 0xe4, 0x11, 0xe3, 0xae, 0x4c, 0x12, 0x81, 0x83, 0xd1, 0xbb,
	0x32, 0x49, 0x84, 0xff, 0xb5, 0xdc, 0xca, 0x7e, 0xaa, 0xc6, 0x49, 0xe5, 0xb9, 0x6c, 0x03, 0x0c,
	0xb5, 0x71, 0x60, 0xd2, 0xa9, 0xfd, 0x35, 0x1d, 0x1b, 0xeb, 0xf4, 0xa7, 0xff, 0x06, 0x9a, 0x8f,
	0xa3, 0x48, 0xc3, 0x5d, 0x16, 0x45, 0x15, 0xff, 0xbc, 0x9f, 0x08, 0x5c, 0x32, 0xee, 0x54, 0xf4,
	0x2b, 0xf7, 0x77, 0x3a, 0xd0, 0x60, 0x51, 0xf4, 0xef, 0xfb, 0x2e, 0xb3, 0xa2, 0x09, 0xff, 0x17,
	0x81, 0xc6, 0x19, 0x7b, 0x3e, 0x3a, 0x52, 0x1a, 0xdd, 0x3a, 0xd8, 0xd9, 0x24, 0x3e, 0x54, 0x51,
	0x60, 0x8e, 0xb3, 0x68, 0xa3, 0x20, 0x7a, 0x38, 0xd7, 0x28, 0x1c, 0x9c, 0xbd, 0x15, 0x88, 0x9d,
	0x3b, 0xb0, 0x22, 0x22, 0x96, 0x64, 0x82, 0x07, 0xf8, 0x3e, 0xe8, 0x99, 0xd7, 0x68, 0xd3, 0x70,
	0x2f, 0xf5, 0x33, 0x71, 0x0f, 0xea, 0x09, 0xcb, 0x47, 0xae, 0x85, 0x1d, 0xde, 0xb8, 0xf8, 0x67,
	0xa3, 0x58, 0xe3, 0xac, 0x82, 0x95, 0xe6, 0x49, 0x8f, 0xbb, 0x4b, 0xd8, 0x54, 0xf1, 0xe1, 0xdc,
	0x07, 0x0b, 0x27, 0xe6, 0x2e, 0xe3, 0xca, 0x5f, 0x2f, 0x5b, 0x98, 0x5d, 0x1a, 0x28, 0x5a, 0xd4,
	0xf8, 0x5f, 0x08, 0x5c, 0x9b, 0x59, 0xfa, 0xdd, 0x11, 0x93, 0x43, 0xf1, 0x1f, 0xf6, 0x7e, 0x26,
	0xbc, 0xfa, 0x6c, 0x78, 0xfe, 0x23, 0xb0, 0xcf, 0x5b, 0xbd, 0x30, 0x7a, 0x0f, 0x20, 0x13, 0x09,
	0x4b, 0x59, 0x1e, 0x2a, 0x69, 0xb2, 0x2f, 0x31, 0x3b, 0xee, 0xf7, 0x13, 0x8f, 0x1c, 0x9f, 0x78,
	0xe4, 0xe7, 0x89, 0x47, 0x3e, 0x9f, 0x7a, 0x0b, 0xc7, 0xa7, 0xde, 0xc2, 0x8f, 0x53, 0x6f, 0xe1,
	0x70, 0x09, 0xbb, 0xdf, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x6e, 0x10, 0xcb, 0xf4, 0x06,
	0x00, 0x00,
}

func (m *RoundStart) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoundStart) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RoundStart) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RoundEnd) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RoundEnd) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RoundEnd) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextScene != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.NextScene))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BezierInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BezierInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BezierInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Op2Point != nil {
		{
			size, err := m.Op2Point.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFish(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Op1Point != nil {
		{
			size, err := m.Op1Point.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFish(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.EndPoint != nil {
		{
			size, err := m.EndPoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFish(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.StartPoint != nil {
		{
			size, err := m.StartPoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFish(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Time != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Time))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BezierInfo_Point) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BezierInfo_Point) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BezierInfo_Point) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Y != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Y))
		i--
		dAtA[i] = 0x10
	}
	if m.X != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.X))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BroadcastFishIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BroadcastFishIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BroadcastFishIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Fish != nil {
		{
			size, err := m.Fish.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFish(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BroadcastFishOut) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BroadcastFishOut) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BroadcastFishOut) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BroadcastGroupIn) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BroadcastGroupIn) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BroadcastGroupIn) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GroupFish) > 0 {
		for iNdEx := len(m.GroupFish) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GroupFish[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFish(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AllFishCall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllFishCall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllFishCall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AllFishRecall) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllFishRecall) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllFishRecall) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AllFish) > 0 {
		for iNdEx := len(m.AllFish) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AllFish[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFish(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FishInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FishInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FishInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Group != nil {
		{
			size, err := m.Group.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFish(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.RtpId) > 0 {
		i -= len(m.RtpId)
		copy(dAtA[i:], m.RtpId)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RtpId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Path) > 0 {
		for iNdEx := len(m.Path) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Path[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFish(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ElapsedTime != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.ElapsedTime))
		i--
		dAtA[i] = 0x20
	}
	if m.Life != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Life))
		i--
		dAtA[i] = 0x18
	}
	if m.SymbolId != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.SymbolId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BroadcastFishChange) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BroadcastFishChange) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BroadcastFishChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SymbolId != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.SymbolId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RoomUuid) > 0 {
		i -= len(m.RoomUuid)
		copy(dAtA[i:], m.RoomUuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.RoomUuid)))
		i--
		dAtA[i] = 0x12
	}
	if m.Msgid != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GroupInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GroupInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GroupInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Separation != 0 {
		i = encodeVarintFish(dAtA, i, uint64(m.Separation))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintFish(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFish(dAtA []byte, offset int, v uint64) int {
	offset -= sovFish(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RoundStart) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovFish(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	return n
}

func (m *RoundEnd) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovFish(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if m.NextScene != 0 {
		n += 1 + sovFish(uint64(m.NextScene))
	}
	return n
}

func (m *BezierInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Time != 0 {
		n += 1 + sovFish(uint64(m.Time))
	}
	if m.StartPoint != nil {
		l = m.StartPoint.Size()
		n += 1 + l + sovFish(uint64(l))
	}
	if m.EndPoint != nil {
		l = m.EndPoint.Size()
		n += 1 + l + sovFish(uint64(l))
	}
	if m.Op1Point != nil {
		l = m.Op1Point.Size()
		n += 1 + l + sovFish(uint64(l))
	}
	if m.Op2Point != nil {
		l = m.Op2Point.Size()
		n += 1 + l + sovFish(uint64(l))
	}
	return n
}

func (m *BezierInfo_Point) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.X != 0 {
		n += 1 + sovFish(uint64(m.X))
	}
	if m.Y != 0 {
		n += 1 + sovFish(uint64(m.Y))
	}
	return n
}

func (m *BroadcastFishIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovFish(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if m.Fish != nil {
		l = m.Fish.Size()
		n += 1 + l + sovFish(uint64(l))
	}
	return n
}

func (m *BroadcastFishOut) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovFish(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovFish(uint64(m.Type))
	}
	return n
}

func (m *BroadcastGroupIn) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovFish(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if len(m.GroupFish) > 0 {
		for _, e := range m.GroupFish {
			l = e.Size()
			n += 1 + l + sovFish(uint64(l))
		}
	}
	return n
}

func (m *AllFishCall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovFish(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	return n
}

func (m *AllFishRecall) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovFish(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if len(m.AllFish) > 0 {
		for _, e := range m.AllFish {
			l = e.Size()
			n += 1 + l + sovFish(uint64(l))
		}
	}
	return n
}

func (m *FishInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if m.SymbolId != 0 {
		n += 1 + sovFish(uint64(m.SymbolId))
	}
	if m.Life != 0 {
		n += 1 + sovFish(uint64(m.Life))
	}
	if m.ElapsedTime != 0 {
		n += 1 + sovFish(uint64(m.ElapsedTime))
	}
	if len(m.Path) > 0 {
		for _, e := range m.Path {
			l = e.Size()
			n += 1 + l + sovFish(uint64(l))
		}
	}
	l = len(m.RtpId)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if m.Group != nil {
		l = m.Group.Size()
		n += 1 + l + sovFish(uint64(l))
	}
	return n
}

func (m *BroadcastFishChange) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Msgid != 0 {
		n += 1 + sovFish(uint64(m.Msgid))
	}
	l = len(m.RoomUuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if m.SymbolId != 0 {
		n += 1 + sovFish(uint64(m.SymbolId))
	}
	return n
}

func (m *GroupInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovFish(uint64(l))
	}
	if m.Separation != 0 {
		n += 1 + sovFish(uint64(m.Separation))
	}
	return n
}

func sovFish(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFish(x uint64) (n int) {
	return sovFish(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RoundStart) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoundStart: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoundStart: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RoundEnd) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RoundEnd: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RoundEnd: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextScene", wireType)
			}
			m.NextScene = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextScene |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BezierInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BezierInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BezierInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Time", wireType)
			}
			m.Time = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Time |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartPoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StartPoint == nil {
				m.StartPoint = &BezierInfo_Point{}
			}
			if err := m.StartPoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndPoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndPoint == nil {
				m.EndPoint = &BezierInfo_Point{}
			}
			if err := m.EndPoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op1Point", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Op1Point == nil {
				m.Op1Point = &BezierInfo_Point{}
			}
			if err := m.Op1Point.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op2Point", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Op2Point == nil {
				m.Op2Point = &BezierInfo_Point{}
			}
			if err := m.Op2Point.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BezierInfo_Point) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Point: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Point: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			m.X = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.X |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			m.Y = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Y |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BroadcastFishIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BroadcastFishIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BroadcastFishIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fish", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fish == nil {
				m.Fish = &FishInfo{}
			}
			if err := m.Fish.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BroadcastFishOut) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BroadcastFishOut: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BroadcastFishOut: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BroadcastGroupIn) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BroadcastGroupIn: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BroadcastGroupIn: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupFish", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupFish = append(m.GroupFish, &FishInfo{})
			if err := m.GroupFish[len(m.GroupFish)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllFishCall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllFishCall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllFishCall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllFishRecall) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllFishRecall: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllFishRecall: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllFish", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AllFish = append(m.AllFish, &FishInfo{})
			if err := m.AllFish[len(m.AllFish)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FishInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FishInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FishInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SymbolId", wireType)
			}
			m.SymbolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SymbolId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Life", wireType)
			}
			m.Life = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Life |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ElapsedTime", wireType)
			}
			m.ElapsedTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ElapsedTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = append(m.Path, &BezierInfo{})
			if err := m.Path[len(m.Path)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RtpId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RtpId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Group", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Group == nil {
				m.Group = &GroupInfo{}
			}
			if err := m.Group.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BroadcastFishChange) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BroadcastFishChange: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BroadcastFishChange: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= proto1.EMSGID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoomUuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RoomUuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SymbolId", wireType)
			}
			m.SymbolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SymbolId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GroupInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFish
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GroupInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GroupInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFish
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFish
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Separation", wireType)
			}
			m.Separation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFish
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Separation |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFish(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthFish
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFish(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFish
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFish
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFish
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFish
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFish
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFish
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFish        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFish          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFish = fmt.Errorf("proto: unexpected end of group")
)
