// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pb/slots/gamedaystat.proto

package slots

import (
	context "context"
	pb "game/pb/_gen/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SlotsGameDayStatRpcClient is the client API for SlotsGameDayStatRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlotsGameDayStatRpcClient interface {
	IncBoth(ctx context.Context, in *SlotsGameDayStatRecord, opts ...grpc.CallOption) (*pb.Empty, error)
	IncAll(ctx context.Context, in *SlotsGameDayStatRecord, opts ...grpc.CallOption) (*pb.Empty, error)
	Docs(ctx context.Context, in *SlotsGameDayStatDocsReq, opts ...grpc.CallOption) (*SlotsGameDayStatDocsResp, error)
}

type slotsGameDayStatRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSlotsGameDayStatRpcClient(cc grpc.ClientConnInterface) SlotsGameDayStatRpcClient {
	return &slotsGameDayStatRpcClient{cc}
}

func (c *slotsGameDayStatRpcClient) IncBoth(ctx context.Context, in *SlotsGameDayStatRecord, opts ...grpc.CallOption) (*pb.Empty, error) {
	out := new(pb.Empty)
	err := c.cc.Invoke(ctx, "/slots.SlotsGameDayStatRpc/IncBoth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotsGameDayStatRpcClient) IncAll(ctx context.Context, in *SlotsGameDayStatRecord, opts ...grpc.CallOption) (*pb.Empty, error) {
	out := new(pb.Empty)
	err := c.cc.Invoke(ctx, "/slots.SlotsGameDayStatRpc/IncAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotsGameDayStatRpcClient) Docs(ctx context.Context, in *SlotsGameDayStatDocsReq, opts ...grpc.CallOption) (*SlotsGameDayStatDocsResp, error) {
	out := new(SlotsGameDayStatDocsResp)
	err := c.cc.Invoke(ctx, "/slots.SlotsGameDayStatRpc/Docs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlotsGameDayStatRpcServer is the server API for SlotsGameDayStatRpc service.
// All implementations should embed UnimplementedSlotsGameDayStatRpcServer
// for forward compatibility
type SlotsGameDayStatRpcServer interface {
	IncBoth(context.Context, *SlotsGameDayStatRecord) (*pb.Empty, error)
	IncAll(context.Context, *SlotsGameDayStatRecord) (*pb.Empty, error)
	Docs(context.Context, *SlotsGameDayStatDocsReq) (*SlotsGameDayStatDocsResp, error)
}

// UnimplementedSlotsGameDayStatRpcServer should be embedded to have forward compatible implementations.
type UnimplementedSlotsGameDayStatRpcServer struct {
}

func (UnimplementedSlotsGameDayStatRpcServer) IncBoth(context.Context, *SlotsGameDayStatRecord) (*pb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncBoth not implemented")
}
func (UnimplementedSlotsGameDayStatRpcServer) IncAll(context.Context, *SlotsGameDayStatRecord) (*pb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncAll not implemented")
}
func (UnimplementedSlotsGameDayStatRpcServer) Docs(context.Context, *SlotsGameDayStatDocsReq) (*SlotsGameDayStatDocsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Docs not implemented")
}

// UnsafeSlotsGameDayStatRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlotsGameDayStatRpcServer will
// result in compilation errors.
type UnsafeSlotsGameDayStatRpcServer interface {
	mustEmbedUnimplementedSlotsGameDayStatRpcServer()
}

func RegisterSlotsGameDayStatRpcServer(s grpc.ServiceRegistrar, srv SlotsGameDayStatRpcServer) {
	s.RegisterService(&SlotsGameDayStatRpc_ServiceDesc, srv)
}

func _SlotsGameDayStatRpc_IncBoth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotsGameDayStatRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotsGameDayStatRpcServer).IncBoth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slots.SlotsGameDayStatRpc/IncBoth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotsGameDayStatRpcServer).IncBoth(ctx, req.(*SlotsGameDayStatRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotsGameDayStatRpc_IncAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotsGameDayStatRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotsGameDayStatRpcServer).IncAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slots.SlotsGameDayStatRpc/IncAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotsGameDayStatRpcServer).IncAll(ctx, req.(*SlotsGameDayStatRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotsGameDayStatRpc_Docs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotsGameDayStatDocsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotsGameDayStatRpcServer).Docs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slots.SlotsGameDayStatRpc/Docs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotsGameDayStatRpcServer).Docs(ctx, req.(*SlotsGameDayStatDocsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SlotsGameDayStatRpc_ServiceDesc is the grpc.ServiceDesc for SlotsGameDayStatRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlotsGameDayStatRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slots.SlotsGameDayStatRpc",
	HandlerType: (*SlotsGameDayStatRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IncBoth",
			Handler:    _SlotsGameDayStatRpc_IncBoth_Handler,
		},
		{
			MethodName: "IncAll",
			Handler:    _SlotsGameDayStatRpc_IncAll_Handler,
		},
		{
			MethodName: "Docs",
			Handler:    _SlotsGameDayStatRpc_Docs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/slots/gamedaystat.proto",
}
