// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pb/slots/statsbuygame.proto

package slots

import (
	context "context"
	pb "game/pb/_gen/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SlotsStatsBuyGameRpcClient is the client API for SlotsStatsBuyGameRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SlotsStatsBuyGameRpcClient interface {
	Add(ctx context.Context, in *SlotsStatsBuyGame_Doc, opts ...grpc.CallOption) (*pb.Empty, error)
	Query(ctx context.Context, in *SlotsStatsBuyGame_QueryReq, opts ...grpc.CallOption) (*SlotsStatsBuyGame_QueryResp, error)
}

type slotsStatsBuyGameRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewSlotsStatsBuyGameRpcClient(cc grpc.ClientConnInterface) SlotsStatsBuyGameRpcClient {
	return &slotsStatsBuyGameRpcClient{cc}
}

func (c *slotsStatsBuyGameRpcClient) Add(ctx context.Context, in *SlotsStatsBuyGame_Doc, opts ...grpc.CallOption) (*pb.Empty, error) {
	out := new(pb.Empty)
	err := c.cc.Invoke(ctx, "/slots.SlotsStatsBuyGameRpc/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *slotsStatsBuyGameRpcClient) Query(ctx context.Context, in *SlotsStatsBuyGame_QueryReq, opts ...grpc.CallOption) (*SlotsStatsBuyGame_QueryResp, error) {
	out := new(SlotsStatsBuyGame_QueryResp)
	err := c.cc.Invoke(ctx, "/slots.SlotsStatsBuyGameRpc/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlotsStatsBuyGameRpcServer is the server API for SlotsStatsBuyGameRpc service.
// All implementations should embed UnimplementedSlotsStatsBuyGameRpcServer
// for forward compatibility
type SlotsStatsBuyGameRpcServer interface {
	Add(context.Context, *SlotsStatsBuyGame_Doc) (*pb.Empty, error)
	Query(context.Context, *SlotsStatsBuyGame_QueryReq) (*SlotsStatsBuyGame_QueryResp, error)
}

// UnimplementedSlotsStatsBuyGameRpcServer should be embedded to have forward compatible implementations.
type UnimplementedSlotsStatsBuyGameRpcServer struct {
}

func (UnimplementedSlotsStatsBuyGameRpcServer) Add(context.Context, *SlotsStatsBuyGame_Doc) (*pb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedSlotsStatsBuyGameRpcServer) Query(context.Context, *SlotsStatsBuyGame_QueryReq) (*SlotsStatsBuyGame_QueryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}

// UnsafeSlotsStatsBuyGameRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SlotsStatsBuyGameRpcServer will
// result in compilation errors.
type UnsafeSlotsStatsBuyGameRpcServer interface {
	mustEmbedUnimplementedSlotsStatsBuyGameRpcServer()
}

func RegisterSlotsStatsBuyGameRpcServer(s grpc.ServiceRegistrar, srv SlotsStatsBuyGameRpcServer) {
	s.RegisterService(&SlotsStatsBuyGameRpc_ServiceDesc, srv)
}

func _SlotsStatsBuyGameRpc_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotsStatsBuyGame_Doc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotsStatsBuyGameRpcServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slots.SlotsStatsBuyGameRpc/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotsStatsBuyGameRpcServer).Add(ctx, req.(*SlotsStatsBuyGame_Doc))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlotsStatsBuyGameRpc_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotsStatsBuyGame_QueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlotsStatsBuyGameRpcServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/slots.SlotsStatsBuyGameRpc/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlotsStatsBuyGameRpcServer).Query(ctx, req.(*SlotsStatsBuyGame_QueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SlotsStatsBuyGameRpc_ServiceDesc is the grpc.ServiceDesc for SlotsStatsBuyGameRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SlotsStatsBuyGameRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slots.SlotsStatsBuyGameRpc",
	HandlerType: (*SlotsStatsBuyGameRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _SlotsStatsBuyGameRpc_Add_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _SlotsStatsBuyGameRpc_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/slots/statsbuygame.proto",
}
