// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: pb/adminslots/admin_rpc.proto

package adminslots

import (
	context "context"
	pb "game/pb/_gen/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminSlotsRpcClient is the client API for AdminSlotsRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminSlotsRpcClient interface {
	AdminRecoverPan(ctx context.Context, in *AdminRecoverPanReq, opts ...grpc.CallOption) (*JsonData, error)
	GenCombineData(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.Empty, error)
	GenerateData(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.Empty, error)
	GetLast10DayRunTimeData(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*JsonData, error)
	GetPoolStatus(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*JsonData, error)
	ExtractAction(ctx context.Context, in *JsonData, opts ...grpc.CallOption) (*pb.Empty, error)
	SwitchAutoCreateData(ctx context.Context, in *JsonData, opts ...grpc.CallOption) (*pb.Empty, error)
}

type adminSlotsRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminSlotsRpcClient(cc grpc.ClientConnInterface) AdminSlotsRpcClient {
	return &adminSlotsRpcClient{cc}
}

func (c *adminSlotsRpcClient) AdminRecoverPan(ctx context.Context, in *AdminRecoverPanReq, opts ...grpc.CallOption) (*JsonData, error) {
	out := new(JsonData)
	err := c.cc.Invoke(ctx, "/adminslots.AdminSlotsRpc/AdminRecoverPan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSlotsRpcClient) GenCombineData(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.Empty, error) {
	out := new(pb.Empty)
	err := c.cc.Invoke(ctx, "/adminslots.AdminSlotsRpc/GenCombineData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSlotsRpcClient) GenerateData(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*pb.Empty, error) {
	out := new(pb.Empty)
	err := c.cc.Invoke(ctx, "/adminslots.AdminSlotsRpc/GenerateData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSlotsRpcClient) GetLast10DayRunTimeData(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*JsonData, error) {
	out := new(JsonData)
	err := c.cc.Invoke(ctx, "/adminslots.AdminSlotsRpc/GetLast10DayRunTimeData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSlotsRpcClient) GetPoolStatus(ctx context.Context, in *pb.Empty, opts ...grpc.CallOption) (*JsonData, error) {
	out := new(JsonData)
	err := c.cc.Invoke(ctx, "/adminslots.AdminSlotsRpc/GetPoolStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSlotsRpcClient) ExtractAction(ctx context.Context, in *JsonData, opts ...grpc.CallOption) (*pb.Empty, error) {
	out := new(pb.Empty)
	err := c.cc.Invoke(ctx, "/adminslots.AdminSlotsRpc/ExtractAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminSlotsRpcClient) SwitchAutoCreateData(ctx context.Context, in *JsonData, opts ...grpc.CallOption) (*pb.Empty, error) {
	out := new(pb.Empty)
	err := c.cc.Invoke(ctx, "/adminslots.AdminSlotsRpc/SwitchAutoCreateData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminSlotsRpcServer is the server API for AdminSlotsRpc service.
// All implementations should embed UnimplementedAdminSlotsRpcServer
// for forward compatibility
type AdminSlotsRpcServer interface {
	AdminRecoverPan(context.Context, *AdminRecoverPanReq) (*JsonData, error)
	GenCombineData(context.Context, *pb.Empty) (*pb.Empty, error)
	GenerateData(context.Context, *pb.Empty) (*pb.Empty, error)
	GetLast10DayRunTimeData(context.Context, *pb.Empty) (*JsonData, error)
	GetPoolStatus(context.Context, *pb.Empty) (*JsonData, error)
	ExtractAction(context.Context, *JsonData) (*pb.Empty, error)
	SwitchAutoCreateData(context.Context, *JsonData) (*pb.Empty, error)
}

// UnimplementedAdminSlotsRpcServer should be embedded to have forward compatible implementations.
type UnimplementedAdminSlotsRpcServer struct {
}

func (UnimplementedAdminSlotsRpcServer) AdminRecoverPan(context.Context, *AdminRecoverPanReq) (*JsonData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRecoverPan not implemented")
}
func (UnimplementedAdminSlotsRpcServer) GenCombineData(context.Context, *pb.Empty) (*pb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenCombineData not implemented")
}
func (UnimplementedAdminSlotsRpcServer) GenerateData(context.Context, *pb.Empty) (*pb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateData not implemented")
}
func (UnimplementedAdminSlotsRpcServer) GetLast10DayRunTimeData(context.Context, *pb.Empty) (*JsonData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLast10DayRunTimeData not implemented")
}
func (UnimplementedAdminSlotsRpcServer) GetPoolStatus(context.Context, *pb.Empty) (*JsonData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoolStatus not implemented")
}
func (UnimplementedAdminSlotsRpcServer) ExtractAction(context.Context, *JsonData) (*pb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractAction not implemented")
}
func (UnimplementedAdminSlotsRpcServer) SwitchAutoCreateData(context.Context, *JsonData) (*pb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SwitchAutoCreateData not implemented")
}

// UnsafeAdminSlotsRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminSlotsRpcServer will
// result in compilation errors.
type UnsafeAdminSlotsRpcServer interface {
	mustEmbedUnimplementedAdminSlotsRpcServer()
}

func RegisterAdminSlotsRpcServer(s grpc.ServiceRegistrar, srv AdminSlotsRpcServer) {
	s.RegisterService(&AdminSlotsRpc_ServiceDesc, srv)
}

func _AdminSlotsRpc_AdminRecoverPan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRecoverPanReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSlotsRpcServer).AdminRecoverPan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminslots.AdminSlotsRpc/AdminRecoverPan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSlotsRpcServer).AdminRecoverPan(ctx, req.(*AdminRecoverPanReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSlotsRpc_GenCombineData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSlotsRpcServer).GenCombineData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminslots.AdminSlotsRpc/GenCombineData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSlotsRpcServer).GenCombineData(ctx, req.(*pb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSlotsRpc_GenerateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSlotsRpcServer).GenerateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminslots.AdminSlotsRpc/GenerateData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSlotsRpcServer).GenerateData(ctx, req.(*pb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSlotsRpc_GetLast10DayRunTimeData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSlotsRpcServer).GetLast10DayRunTimeData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminslots.AdminSlotsRpc/GetLast10DayRunTimeData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSlotsRpcServer).GetLast10DayRunTimeData(ctx, req.(*pb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSlotsRpc_GetPoolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSlotsRpcServer).GetPoolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminslots.AdminSlotsRpc/GetPoolStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSlotsRpcServer).GetPoolStatus(ctx, req.(*pb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSlotsRpc_ExtractAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSlotsRpcServer).ExtractAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminslots.AdminSlotsRpc/ExtractAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSlotsRpcServer).ExtractAction(ctx, req.(*JsonData))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminSlotsRpc_SwitchAutoCreateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSlotsRpcServer).SwitchAutoCreateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/adminslots.AdminSlotsRpc/SwitchAutoCreateData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSlotsRpcServer).SwitchAutoCreateData(ctx, req.(*JsonData))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminSlotsRpc_ServiceDesc is the grpc.ServiceDesc for AdminSlotsRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminSlotsRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adminslots.AdminSlotsRpc",
	HandlerType: (*AdminSlotsRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminRecoverPan",
			Handler:    _AdminSlotsRpc_AdminRecoverPan_Handler,
		},
		{
			MethodName: "GenCombineData",
			Handler:    _AdminSlotsRpc_GenCombineData_Handler,
		},
		{
			MethodName: "GenerateData",
			Handler:    _AdminSlotsRpc_GenerateData_Handler,
		},
		{
			MethodName: "GetLast10DayRunTimeData",
			Handler:    _AdminSlotsRpc_GetLast10DayRunTimeData_Handler,
		},
		{
			MethodName: "GetPoolStatus",
			Handler:    _AdminSlotsRpc_GetPoolStatus_Handler,
		},
		{
			MethodName: "ExtractAction",
			Handler:    _AdminSlotsRpc_ExtractAction_Handler,
		},
		{
			MethodName: "SwitchAutoCreateData",
			Handler:    _AdminSlotsRpc_SwitchAutoCreateData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/adminslots/admin_rpc.proto",
}
